"""add-ro_url-to-db

Revision ID: c3b6de846953
Revises: 302220fa8bba
Create Date: 2026-06-17 13:49:33.774022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from config import settings

# revision identifiers, used by Alembic.
revision: str = "c3b6de846953"
down_revision: Union[str, Sequence[str], None] = "302220fa8bba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "database",
        sa.Column("read_only_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###

    server = settings.POSTGRES_SERVER
    db = settings.POSTGRES_DB
    conn = op.get_bind()

    conn.execute(
        sa.text("""
                UPDATE database
                SET read_only_url =
                        'postgresql://' ||
                        read_only_username ||
                        '@' ||
                        :server ||
                        '/' ||
                        :db
                """),
        {
            "server": server,
            "db": db,
        },
    )

    op.alter_column(
        "database",
        "read_only_url",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("database", "read_only_url")
    # ### end Alembic commands ###
