"""timezone-in-json-parser

Revision ID: d97c6055955e
Revises: c3b6de846953
Create Date: 2026-06-19 09:14:56.587773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "d97c6055955e"
down_revision: Union[str, Sequence[str], None] = "c3b6de846953"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parser_json",
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parser_json", "timezone")
    # ### end Alembic commands ###
