"""updating_parser_id_sequence

Revision ID: a826f202fb21
Revises: 94a3fd11dd44
Create Date: 2026-07-15 05:12:08.091885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a826f202fb21"
down_revision: Union[str, Sequence[str], None] = "94a3fd11dd44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # updating parser_id sequence to avoid errors with duplicate keys
    op.execute(
        "SELECT setval('parser_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM parser), false)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
