"""add_position_to_quality_control_function

Revision ID: 72352b0b8990
Revises: 2987dd5f50bc
Create Date: 2026-08-26 15:05:13.442299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "72352b0b8990"
down_revision: Union[str, Sequence[str], None] = "2987dd5f50bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quality_control_function",
        sa.Column("position", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("quality_control_function", "position", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quality_control_function", "position")
    # ### end Alembic commands ###
