"""unique-mqtt-username

Revision ID: 94a3fd11dd44
Revises: 55e4894d3a9e
Create Date: 2026-07-01 19:46:24.602552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "94a3fd11dd44"
down_revision: Union[str, Sequence[str], None] = "55e4894d3a9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_ingest_mqtt_username",
        "ingest_mqtt",
        [sa.literal_column("lower(username)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ingest_mqtt_username", table_name="ingest_mqtt")
    # ### end Alembic commands ###
