"""init

Revision ID: 8a0d362c2d34
Revises:
Create Date: 2026-05-04 13:08:18.643455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "8a0d362c2d34"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "neutron_monitor_station",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("parser_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint(
            "parser_type IN ('csv','json','mqtt')", name="ck_parser_type"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parser_parser_type"), "parser", ["parser_type"], unique=False
    )
    op.create_index(op.f("ix_parser_uuid"), "parser", ["uuid"], unique=True)
    op.create_table(
        "permission_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("entitlement", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entitlement"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("given_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("family_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_sub"), "user", ["sub"], unique=True)
    op.create_table(
        "database",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "read_only_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "read_only_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("permission_group_id"),
    )
    op.create_table(
        "ingest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("ingest_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("parser_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "ingest_type IN ('mqtt','sftp','external_api', 'external_sftp')",
            name="ck_ingest_type",
        ),
        sa.ForeignKeyConstraint(
            ["parser_id"],
            ["parser.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingest_ingest_type"), "ingest", ["ingest_type"], unique=False
    )
    op.create_index(
        "ix_ingest_name_permission_group",
        "ingest",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_index(op.f("ix_ingest_uuid"), "ingest", ["uuid"], unique=True)
    op.create_table(
        "parser_detailed",
        sa.Column("parser_id", sa.Integer(), nullable=False),
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["parser_id"], ["parser.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("parser_id"),
    )
    op.create_index(
        "ix_parser_name_permission_group",
        "parser_detailed",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "parser_mqtt",
        sa.Column("parser_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parser_id"],
            ["parser.id"],
        ),
        sa.PrimaryKeyConstraint("parser_id"),
    )
    op.create_table(
        "permission_group_user_link",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("permission_group_id", "user_id"),
    )
    op.create_table(
        "quality_control_setting",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("context_window", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_qcs_name_permission_group",
        "quality_control_setting",
        [sa.literal_column("lower(name)"), sa.literal_column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "ingest_external_api",
        sa.Column("ingest_id", sa.Integer(), nullable=False),
        sa.Column("api_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("sync_interval_in_minutes", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "api_type IN ('bosch','dwd','nm', 'ttn','tsystems','uba')",
            name="ck_api_type",
        ),
        sa.ForeignKeyConstraint(["ingest_id"], ["ingest.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ingest_id"),
    )
    op.create_index(
        op.f("ix_ingest_external_api_api_type"),
        "ingest_external_api",
        ["api_type"],
        unique=False,
    )
    op.create_table(
        "ingest_external_sftp",
        sa.Column("ingest_id", sa.Integer(), nullable=False),
        sa.Column("uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "filename_pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sync_interval_in_minutes", sa.Integer(), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("ssh_private_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ssh_public_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bucket_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "bucket_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "bucket_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(["ingest_id"], ["ingest.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ingest_id"),
    )
    op.create_table(
        "ingest_mqtt",
        sa.Column("ingest_id", sa.Integer(), nullable=False),
        sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "password_hashed", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(["ingest_id"], ["ingest.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ingest_id"),
    )
    op.create_table(
        "ingest_sftp",
        sa.Column("ingest_id", sa.Integer(), nullable=False),
        sa.Column(
            "filename_pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bucket_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fileserver_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["ingest_id"], ["ingest.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ingest_id"),
    )
    op.create_table(
        "parser_csv",
        sa.Column("parser_id", sa.Integer(), nullable=False),
        sa.Column("delimiter", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("encoding", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "headlines_to_exclude", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("footlines_to_exclude", sa.Integer(), nullable=True),
        sa.Column("pandas_read_csv", sa.JSON(), nullable=True),
        sa.Column("comment", sa.JSON(), nullable=True),
        sa.Column("header", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parser_id"], ["parser_detailed.parser_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("parser_id"),
    )
    op.create_table(
        "quality_control_function",
        sa.Column("quality_control_setting_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quality_control_setting_id"],
            ["quality_control_setting.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingest_external_api_bosch",
        sa.Column("ingest_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sensor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bosch_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bosch_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("period_in_minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingest_id"], ["ingest_external_api.ingest_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ingest_id"),
    )
    op.create_table(
        "ingest_external_api_dwd",
        sa.Column("ingest_id", sa.Integer(), nullable=False),
        sa.Column("station_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("period_in_minutes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingest_id"], ["ingest_external_api.ingest_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ingest_id"),
    )
    op.create_table(
        "ingest_external_api_neutron_monitor",
        sa.Column("ingest_id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("time_resolution_in_minutes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingest_id"], ["ingest_external_api.ingest_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["neutron_monitor_station.id"],
        ),
        sa.PrimaryKeyConstraint("ingest_id"),
    )
    op.create_table(
        "ingest_external_api_the_things_network",
        sa.Column("ingest_id", sa.Integer(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("endpoint_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingest_id"], ["ingest_external_api.ingest_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ingest_id"),
    )
    op.create_table(
        "ingest_external_api_tsystems",
        sa.Column("ingest_id", sa.Integer(), nullable=False),
        sa.Column("group", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("station_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "tsystems_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "tsystems_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["ingest_id"], ["ingest_external_api.ingest_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ingest_id"),
    )
    op.create_table(
        "ingest_external_api_uba",
        sa.Column("ingest_id", sa.Integer(), nullable=False),
        sa.Column("station_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingest_id"], ["ingest_external_api.ingest_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ingest_id"),
    )
    op.create_table(
        "parser_csv_timestamp_column",
        sa.Column("parser_csv_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("column", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp_format", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["parser_csv_id"], ["parser_csv.parser_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quality_control_function_argument",
        sa.Column("quality_control_function_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quality_control_function_id"],
            ["quality_control_function.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quality_control_function_argument")
    op.drop_table("parser_csv_timestamp_column")
    op.drop_table("ingest_external_api_uba")
    op.drop_table("ingest_external_api_tsystems")
    op.drop_table("ingest_external_api_the_things_network")
    op.drop_table("ingest_external_api_neutron_monitor")
    op.drop_table("ingest_external_api_dwd")
    op.drop_table("ingest_external_api_bosch")
    op.drop_table("quality_control_function")
    op.drop_table("parser_csv")
    op.drop_table("ingest_sftp")
    op.drop_table("ingest_mqtt")
    op.drop_table("ingest_external_sftp")
    op.drop_index(
        op.f("ix_ingest_external_api_api_type"), table_name="ingest_external_api"
    )
    op.drop_table("ingest_external_api")
    op.drop_index("ix_qcs_name_permission_group", table_name="quality_control_setting")
    op.drop_table("quality_control_setting")
    op.drop_table("permission_group_user_link")
    op.drop_table("parser_mqtt")
    op.drop_index("ix_parser_name_permission_group", table_name="parser_detailed")
    op.drop_table("parser_detailed")
    op.drop_index(op.f("ix_ingest_uuid"), table_name="ingest")
    op.drop_index("ix_ingest_name_permission_group", table_name="ingest")
    op.drop_index(op.f("ix_ingest_ingest_type"), table_name="ingest")
    op.drop_table("ingest")
    op.drop_table("database")
    op.drop_index(op.f("ix_user_sub"), table_name="user")
    op.drop_table("user")
    op.drop_table("permission_group")
    op.drop_index(op.f("ix_parser_uuid"), table_name="parser")
    op.drop_index(op.f("ix_parser_parser_type"), table_name="parser")
    op.drop_table("parser")
    op.drop_table("neutron_monitor_station")
    # ### end Alembic commands ###
