"""created_at optional, name in database tooo

Revision ID: b09bc1ec0794
Revises: ab9ee236aa8c
Create Date: 2026-05-26 10:52:21.160392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b09bc1ec0794"
down_revision: Union[str, Sequence[str], None] = "ab9ee236aa8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("database", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "ingest", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "ingest_sftp", "fileserver_uri", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "parser_detailed",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "quality_control_setting",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.create_unique_constraint(None, "quality_control_setting", ["uuid"])
    op.alter_column(
        "user", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_constraint(None, "quality_control_setting", type_="unique")
    op.alter_column(
        "quality_control_setting",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "parser_detailed",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "ingest_sftp", "fileserver_uri", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "ingest", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("database", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
