"""add_parser_soilcan

Revision ID: 2987dd5f50bc
Revises: a826f202fb21
Create Date: 2026-07-16 12:39:41.971402

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "2987dd5f50bc"
down_revision: Union[str, Sequence[str], None] = "a826f202fb21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parser_soilcan",
        sa.Column("parser_id", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("header", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "type IN ('operating-parameters','sensor-data','weighing-data')",
            name="ck_parser_soilcan_type",
        ),
        sa.ForeignKeyConstraint(
            ["parser_id"], ["parser_detailed.parser_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("parser_id"),
    )
    op.create_index(
        op.f("ix_parser_soilcan_type"), "parser_soilcan", ["type"], unique=False
    )

    # update constraint
    op.drop_constraint(
        "ck_parser_type",
        "parser",
        type_="check",
    )

    op.create_check_constraint(
        "ck_parser_type",
        "parser",
        "parser_type IN ('csv','json','mqtt', 'soilcan')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parser_soilcan_type"), table_name="parser_soilcan")
    op.drop_table("parser_soilcan")

    # downgrade constraint
    op.drop_constraint(
        "ck_parser_type",
        "parser",
        type_="check",
    )

    op.create_check_constraint(
        "ck_parser_type",
        "parser",
        "parser_type IN ('csv','json','mqtt')",
    )
    # ### end Alembic commands ###
