"""add parser JSON

Revision ID: 302220fa8bba
Revises: e9d8bf38a1c9
Create Date: 2026-06-17 11:12:20.956847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "302220fa8bba"
down_revision: Union[str, Sequence[str], None] = "e9d8bf38a1c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parser_json",
        sa.Column("parser_id", sa.Integer(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parser_id"], ["parser_detailed.parser_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("parser_id"),
    )
    op.create_table(
        "parser_json_timestamp_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parser_json_id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("format", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parser_json_id"], ["parser_json.parser_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parser_json_timestamp_key")
    op.drop_table("parser_json")
    # ### end Alembic commands ###
