"""init_data_nmstations_parsermqtt

Revision ID: ab9ee236aa8c
Revises: 8a0d362c2d34
Create Date: 2026-05-04 13:10:01.960336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid as uuid_pkg

# revision identifiers, used by Alembic.
revision: str = "ab9ee236aa8c"
down_revision: Union[str, Sequence[str], None] = "8a0d362c2d34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    neutron_monitor_station = sa.table(
        "neutron_monitor_station",
        sa.column("id", sa.Integer),
        sa.column("station_id", sa.String),
        sa.column("description", sa.String),
    )
    parser = sa.table(
        "parser",
        sa.column("id", sa.Integer),
        sa.column("uuid", sa.Uuid),
        sa.column("parser_type", sa.String),
    )
    parser_mqtt = sa.table(
        "parser_mqtt",
        sa.column("parser_id", sa.Integer),
        sa.column("name", sa.String),
    )

    op.bulk_insert(
        neutron_monitor_station,
        [
            {
                "id": 1,
                "station_id": "AATA",
                "description": "Alma-Ata A (R=5.90, Alt=897 m)",
            },
            {
                "id": 2,
                "station_id": "AATB",
                "description": "Alma-Ata B (R=5.90, Alt=3340 m)",
            },
            {
                "id": 3,
                "station_id": "AHMD",
                "description": "Ahmedabad (R=15.94, Alt=50 m)",
            },
            {
                "id": 4,
                "station_id": "APTY",
                "description": "Apatity (R=0.65, Alt=181 m)",
            },
            {
                "id": 5,
                "station_id": "ARNM",
                "description": "Aragats (R=7.10, Alt=3200 m)",
            },
            {
                "id": 6,
                "station_id": "ATHN",
                "description": "Athens (R=8.53, Alt=260 m)",
            },
            {
                "id": 7,
                "station_id": "BKSN",
                "description": "Baksan (R=5.70, Alt=1700 m)",
            },
            {
                "id": 8,
                "station_id": "CALG",
                "description": "Calgary (R=1.08, Alt=1123 m)",
            },
            {
                "id": 9,
                "station_id": "CALM",
                "description": "NM de Castilla la Mancha (R=6.95, Alt=708 m)",
            },
            {
                "id": 10,
                "station_id": "CLMX",
                "description": "Climax (R=3.00, Alt=3400 m)",
            },
            {
                "id": 11,
                "station_id": "DJON",
                "description": "Daejeon (R=11.20, Alt=200 m)",
            },
            {
                "id": 12,
                "station_id": "DOMB",
                "description": "Dome C mini NM (bare) (R=0.01, Alt=3233 m)",
            },
            {
                "id": 13,
                "station_id": "DOMC",
                "description": "Dome C mini NM (R=0.01, Alt=3233 m)",
            },
            {
                "id": 14,
                "station_id": "DRBS",
                "description": "Dourbes (R=3.18, Alt=225 m)",
            },
            {
                "id": 15,
                "station_id": "ESOI",
                "description": "Emilio Segre Obs. Israel (R=10.75, Alt=2055 m)",
            },
            {
                "id": 16,
                "station_id": "FSMT",
                "description": "Fort Smith (R=0.30, Alt=180 m)",
            },
            {
                "id": 17,
                "station_id": "HRMS",
                "description": "Hermanus (R=4.58, Alt=26 m)",
            },
            {
                "id": 18,
                "station_id": "HUAN",
                "description": "Huancayo (R=12.92, Alt=3400 m)",
            },
            {
                "id": 19,
                "station_id": "INVK",
                "description": "Inuvik (R=0.30, Alt=21 m)",
            },
            {
                "id": 20,
                "station_id": "IRK2",
                "description": "Irkustk 2 (R=3.64, Alt=2000 m)",
            },
            {
                "id": 21,
                "station_id": "IRK3",
                "description": "Irkutsk 3 (R=3.64, Alt=3000 m)",
            },
            {
                "id": 22,
                "station_id": "IRKT",
                "description": "Irkustk (R=3.64, Alt=435 m)",
            },
            {
                "id": 23,
                "station_id": "JBGO",
                "description": "JangBogo (R=0.30, Alt=29 m)",
            },
            {
                "id": 24,
                "station_id": "JUNG",
                "description": "IGY Jungfraujoch (R=4.49, Alt=3570 m)",
            },
            {
                "id": 25,
                "station_id": "JUNG1",
                "description": "NM64 Jungfraujoch (R=4.49, Alt=3475 m)",
            },
            {
                "id": 26,
                "station_id": "KERG",
                "description": "Kerguelen (R=1.14, Alt=33 m)",
            },
            {
                "id": 27,
                "station_id": "KGSN",
                "description": "Kingston (R=1.88, Alt=65 m)",
            },
            {"id": 28, "station_id": "KIEL", "description": "Kiel (R=2.36, Alt=54 m)"},
            {
                "id": 29,
                "station_id": "KIEL2",
                "description": "KielRT (R=2.36, Alt=54 m)",
            },
            {
                "id": 30,
                "station_id": "LMKS",
                "description": "Lomnicky Stit (R=3.84, Alt=2634 m)",
            },
            {
                "id": 31,
                "station_id": "MCMU",
                "description": "Mc Murdo (R=0.30, Alt=48 m)",
            },
            {
                "id": 32,
                "station_id": "MCRL",
                "description": "Mobile Cosmic Ray Laboratory (R=2.46, Alt=200 m)",
            },
            {
                "id": 33,
                "station_id": "MGDN",
                "description": "Magadan (R=2.10, Alt=220 m)",
            },
            {
                "id": 34,
                "station_id": "MOSC",
                "description": "Moscow (R=2.43, Alt=200 m)",
            },
            {"id": 35, "station_id": "MRNY", "description": "Mirny (R=0.03, Alt=30 m)"},
            {
                "id": 36,
                "station_id": "MWSB",
                "description": "Mawson Bare (R=0.22, Alt=30 m)",
            },
            {
                "id": 37,
                "station_id": "MWSN",
                "description": "Mawson (R=0.22, Alt=30 m)",
            },
            {
                "id": 38,
                "station_id": "MXCO",
                "description": "Mexico (R=8.28, Alt=2274 m)",
            },
            {"id": 39, "station_id": "NAIN", "description": "Nain (R=0.30, Alt=46 m)"},
            {
                "id": 40,
                "station_id": "NANM",
                "description": "Nor-Amberd (R=7.10, Alt=2000 m)",
            },
            {
                "id": 41,
                "station_id": "NEU3",
                "description": "Neumayer III mini neutron monitor (R=0.10, Alt=40 m)",
            },
            {
                "id": 42,
                "station_id": "NEWK",
                "description": "Newark (R=2.40, Alt=50 m)",
            },
            {
                "id": 43,
                "station_id": "NRLK",
                "description": "Norilsk (R=0.63, Alt=0 m)",
            },
            {
                "id": 44,
                "station_id": "NVBK",
                "description": "Novosibirsk (R=2.91, Alt=163 m)",
            },
            {"id": 45, "station_id": "OULU", "description": "Oulu (R=0.81, Alt=15 m)"},
            {
                "id": 46,
                "station_id": "PSNM",
                "description": "Doi Inthanon (Princess Sirindhorn NM) (R=16.80, Alt=2565 m)",
            },
            {
                "id": 47,
                "station_id": "PTFM",
                "description": "Potchefstroom (R=6.98, Alt=1351 m)",
            },
            {
                "id": 48,
                "station_id": "PWNK",
                "description": "Peawanuck (R=0.30, Alt=53 m)",
            },
            {"id": 49, "station_id": "ROME", "description": "Rome (R=6.27, Alt=0 m)"},
            {
                "id": 50,
                "station_id": "SANB",
                "description": "Sanae D (R=0.73, Alt=52 m)",
            },
            {
                "id": 51,
                "station_id": "SNAE",
                "description": "Sanae IV (R=0.73, Alt=856 m)",
            },
            {
                "id": 52,
                "station_id": "SOPB",
                "description": "South Pole Bare (R=0.10, Alt=2820 m)",
            },
            {
                "id": 53,
                "station_id": "SOPO",
                "description": "South Pole (R=0.10, Alt=2820 m)",
            },
            {
                "id": 54,
                "station_id": "TERA",
                "description": "Terre Adelie (R=0.01, Alt=32 m)",
            },
            {"id": 55, "station_id": "THUL", "description": "Thule (R=0.30, Alt=26 m)"},
            {
                "id": 56,
                "station_id": "TSMB",
                "description": "Tsumeb (R=9.15, Alt=1240 m)",
            },
            {
                "id": 57,
                "station_id": "TXBY",
                "description": "Tixie Bay (R=0.48, Alt=0 m)",
            },
            {
                "id": 58,
                "station_id": "UFSZ",
                "description": "Zugspitze (R=4.10, Alt=2650 m)",
            },
            {
                "id": 59,
                "station_id": "YKTK",
                "description": "Yakutsk (R=1.65, Alt=105 m)",
            },
            {
                "id": 60,
                "station_id": "ZUGS",
                "description": "Zugspitze (R=4.24, Alt=2960 m)",
            },
        ],
    )

    op.bulk_insert(
        parser,
        [
            {
                "id": 1,
                "uuid": uuid_pkg.UUID("4163d425-254a-495f-b7cd-61516017c82b"),
                "parser_type": "mqtt",
            },
            {
                "id": 2,
                "uuid": uuid_pkg.UUID("64dff22a-e472-4292-8b9f-d0836e68ba67"),
                "parser_type": "mqtt",
            },
            {
                "id": 3,
                "uuid": uuid_pkg.UUID("2b882a37-5dec-48b7-9c2a-341ae9cc25c8"),
                "parser_type": "mqtt",
            },
        ],
    )
    op.bulk_insert(
        parser_mqtt,
        [
            {"parser_id": 1, "name": "campbell_cr6"},
            {"parser_id": 2, "name": "ydoc_ml417"},
            {"parser_id": 3, "name": "chirpstack_generic"},
        ],
    )

    # updating parser_id sequence to avoid errors with duplicate keys
    op.execute(
        "SELECT setval('parser_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM parser), false)"
    )
    # updating neutron_monitor_station_id_seq sequence to avoid errors with duplicate keys if new would be added
    op.execute(
        "SELECT setval('neutron_monitor_station_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM neutron_monitor_station), false)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM parser WHERE id in (SELECT parser_id FROM mqtt_parser )")
    op.execute("DELETE FROM mqtt_parser WHERE id >= 1")
    op.execute("DELETE FROM neutron_monitor_station WHERE id >= 1")
    # ### end Alembic commands ###
