"""adding_sensoto_api

Revision ID: 55e4894d3a9e
Revises: 99c357d1b3b3
Create Date: 2026-06-30 13:23:01.577861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "55e4894d3a9e"
down_revision: Union[str, Sequence[str], None] = "99c357d1b3b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingest_external_api_sensoto",
        sa.Column("ingest_id", sa.Integer(), nullable=False),
        sa.Column("network", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("device", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingest_id"], ["ingest_external_api.ingest_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ingest_id"),
    )

    # update constraint
    op.drop_constraint(
        "ck_api_type",
        "ingest_external_api",
        type_="check",
    )

    op.create_check_constraint(
        "ck_api_type",
        "ingest_external_api",
        "api_type IN ('bosch', 'dwd', 'nm', 'ttn', 'tsystems', 'uba', 'sensoto')",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingest_external_api_sensoto")

    op.drop_constraint(
        "ck_api_type",
        "ingest_external_api",
        type_="check",
    )

    op.create_check_constraint(
        "ck_api_type",
        "ingest_external_api",
        "api_type IN ('bosch', 'dwd', 'nm', 'ttn', 'tsystems', 'uba')",
    )
    # ### end Alembic commands ###
