apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  POSTGRES_HOST: "{{  .Values.global.secrets.FRONTEND_POSTGRES_HOST }}"
  POSTGRES_PORT: "{{  .Values.global.secrets.FRONTEND_POSTGRES_PORT }}"
  POSTGRES_NAME: "{{  .Values.global.secrets.FRONTEND_POSTGRES_DB }}"
  POSTGRES_USER: "{{  .Values.global.secrets.FRONTEND_POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{  .Values.global.secrets.FRONTEND_POSTGRES_PASS }}"
  PUBLISH_THING_TO_BROKER: "True"
  CREATEDB_POSTGRES_HOST: "{{  .Values.global.secrets.CREATEDB_POSTGRES_HOST }}"
  CREATEDB_POSTGRES_DATABASE: "{{  .Values.global.secrets.CREATEDB_POSTGRES_DATABASE }}"
  MQTT_BROKER_HOST: "{{  .Values.global.secrets.FRONTEND_MQTT_HOST }}"
  MQTT_BROKER_PORT: "{{  .Values.global.secrets.FRONTEND_MQTT_PORT }}"
  MQTT_USER: "{{  .Values.global.secrets.FRONTEND_MQTT_USER }}"
  MQTT_PASSWORD: "{{  .Values.global.secrets.FRONTEND_MQTT_PASS }}"
  DJANGO_SUPERUSER_USERNAME: "{{  .Values.global.secrets.FRONTEND_DJANGO_SUPERUSER_USERNAME }}"
  DJANGO_SUPERUSER_PASSWORD: "{{  .Values.global.secrets.FRONTEND_DJANGO_SUPERUSER_PASSWORD }}"
  DJANGO_SUPERUSER_EMAIL: "{{  .Values.global.secrets.FRONTEND_DJANGO_SUPERUSER_EMAIL }}"
  DJANGO_SECRET_KEY: "{{  .Values.global.secrets.DJANGO_SECRET_KEY }}"
  DJANGO_DEBUG: "{{  .Values.global.secrets.DJANGO_DEBUG }}"
  DJANGO_TRUSTED_ORIGINS: "{{  .Values.global.secrets.PROXY_URL }}"
  DJANGO_BASE_PATH: "{{  .Values.global.secrets.DJANGO_BASE_PATH }}"
  DJANGO_ALLOWED_HOSTS: "{{  .Values.global.secrets.DJANGO_ALLOWED_HOSTS }}"
  POSTGRES_SSLMODE: "{{  .Values.global.secrets.DJANGO_POSTGRES_SSLMODE }}"
  DJANGO_HELMHOLTZ_CLIENT_ID: "{{  .Values.global.secrets.OIDC_CLIENT_ID }}"
  DJANGO_HELMHOLTZ_CLIENT_SECRET: "{{  .Values.global.secrets.OIDC_CLIENT_SECRET }}"
  DJANGO_HELMHOLTZ_AAI_CONF_URL: "{{  .Values.global.secrets.OIDC_CONF_URL }}"
  MINIO_FTP_PORT: "{{  .Values.global.secrets.MINIO_FTP_PORT }}"
  MINIO_SFTP_PORT: "{{  .Values.global.secrets.MINIO_SFTP_PORT }}"
  PROXY_URL: "{{  .Values.global.secrets.PROXY_URL }}"
  ALLOWED_VOS: "{{  .Values.global.secrets.ALLOWED_VOS }}"