apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  LOG_LEVEL: "{{  .Values.global.secrets.LOG_LEVEL }}"
  TOPIC: "object_storage_notification"
  MQTT_BROKER: "mqtt-broker:1883"
  MQTT_USER: "{{  .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{  .Values.global.secrets.MQTT_PASSWORD }}"
  MQTT_CLIENT_ID: ""
  MQTT_CLEAN_SESSION: "{{  .Values.global.secrets.MQTT_CLEAN_SESSION }}"
  MQTT_QOS: "{{  .Values.global.secrets.MQTT_QOS }}"
  MINIO_SECURE: "{{  .Values.global.secrets.MINIO_SECURE }}"
  MINIO_URL: "{{  .Values.global.secrets.MINIO_HOST }}"
  MINIO_ACCESS_KEY: "{{  .Values.global.secrets.MINIO_ROOT_USER }}"
  MINIO_SECURE_KEY: "{{  .Values.global.secrets.MINIO_ROOT_PASSWORD }}"
  S3MAP_DB_URL: "postgresql://{{  .Values.global.secrets.S3MAP_POSTGRES_USER }}:{{  .Values.global.secrets.S3MAP_POSTGRES_PASS }}@{{  .Values.global.secrets.S3MAP_POSTGRES_HOST }}/{{  .Values.global.secrets.S3MAP_POSTGRES_DB }}"
  SCHEDULER: "{{  .Values.global.secrets.SCHEDULER }}"
  SCHED_HOST: "{{  .Values.global.secrets.SCHED_HOST }}"
  SCHED_MQTT_BROKER: "{{  .Values.global.secrets.MQTT_BROKER }}"
  SCHED_MQTT_USER: "{{  .Values.global.secrets.MQTT_USER }}"
  SCHED_MQTT_PASSWORD: "{{  .Values.global.secrets.MQTT_PASSWORD }}"
  SCHED_JOB_LOG_LEVEL: "{{  .Values.global.secrets.SCHED_JOB_LOG_LEVEL }}"
  SCHED_SLURM_RESTAPI_VERSION: "{{  .Values.global.secrets.SCHED_SLURM_RESTAPI_VERSION }}"
  SCHED_SLURM_USER: "{{  .Values.global.secrets.SCHED_SLURM_USER }}"
  SCHED_SLURM_JWT_TOKEN: "{{  .Values.global.secrets.SCHED_SLURM_JWT_TOKEN }}"