replicaCount: 1

image:
  repository: " registry.hzdr.de/ufz-tsm/thing-management/backend/thing-management-api"
  tag: latest
  pullPolicy: Always
name: thing-management-api
port: 8002

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: []
  runAsUser: 0
  runAsNonRoot: false
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""