apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-envvars
data:
  POSTGRES_HOST: "{{  .Values.global.envvars.FRONTEND_POSTGRES_HOST }}"
  POSTGRES_PORT: "{{  .Values.global.envvars.FRONTEND_POSTGRES_PORT }}"
  POSTGRES_NAME: "{{  .Values.global.envvars.FRONTEND_POSTGRES_DB }}"
  PUBLISH_THING_TO_BROKER: "True"
  CREATEDB_POSTGRES_HOST: "{{  .Values.global.envvars.CREATEDB_POSTGRES_HOST }}"
  CREATEDB_POSTGRES_DATABASE: "{{  .Values.global.envvars.CREATEDB_POSTGRES_DATABASE }}"
  MQTT_BROKER_HOST: "{{  .Values.global.envvars.FRONTEND_MQTT_HOST }}"
  MQTT_BROKER_PORT: "{{  .Values.global.envvars.FRONTEND_MQTT_PORT }}"
  DJANGO_SUPERUSER_EMAIL: "{{  .Values.global.envvars.FRONTEND_DJANGO_SUPERUSER_EMAIL }}"
  DJANGO_DEBUG: "{{  .Values.global.envvars.DJANGO_DEBUG }}"
  DJANGO_TRUSTED_ORIGINS: "{{  .Values.global.ingress.url }}"
  DJANGO_BASE_PATH: "{{  .Values.global.envvars.DJANGO_BASE_PATH }}"
  DJANGO_ALLOWED_HOSTS: "{{  .Values.global.envvars.DJANGO_ALLOWED_HOSTS }},{{ .Values.global.envvars.PROXY_HOST }}"
  POSTGRES_SSLMODE: "{{  .Values.global.envvars.DJANGO_POSTGRES_SSLMODE }}"
  DJANGO_HELMHOLTZ_AAI_CONF_URL: "{{  .Values.global.envvars.OIDC_CONF_URL }}"
  MINIO_FTP_PORT: "{{  .Values.global.envvars.MINIO_FTP_PORT }}"
  MINIO_SFTP_PORT: "{{  .Values.global.envvars.MINIO_SFTP_PORT }}"
  PROXY_URL: "{{  .Values.global.ingress.url }}"
  ALLOWED_VOS: "{{  .Values.global.envvars.ALLOWED_VOS }}"