{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  POSTGRES_USER: "{{  .Values.global.secrets.FRONTEND_POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{  .Values.global.secrets.FRONTEND_POSTGRES_PASS }}"
  MQTT_USER: "{{  .Values.global.secrets.FRONTEND_MQTT_USER }}"
  MQTT_PASSWORD: "{{  .Values.global.secrets.FRONTEND_MQTT_PASS }}"
  DJANGO_SUPERUSER_USERNAME: "{{  .Values.global.secrets.FRONTEND_DJANGO_SUPERUSER_USERNAME }}"
  DJANGO_SUPERUSER_PASSWORD: "{{  .Values.global.secrets.FRONTEND_DJANGO_SUPERUSER_PASSWORD }}"
  DJANGO_SECRET_KEY: "{{  .Values.global.secrets.DJANGO_SECRET_KEY }}"
  DJANGO_HELMHOLTZ_CLIENT_ID: "{{  .Values.global.secrets.OIDC_CLIENT_ID }}"
  DJANGO_HELMHOLTZ_CLIENT_SECRET: "{{  .Values.global.secrets.OIDC_CLIENT_SECRET }}"
  FERNET_ENCRYPTION_SECRET: {{ .Values.global.secrets.FERNET_ENCRYPTION_SECRET | quote }}
{{- end }}