apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxy.name }}
spec:
  selector:
    app: {{ .Values.proxy.name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: frontend
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: s3
      protocol: TCP
      port: 9000
      targetPort: 9000