replicaCount: 1

image:
  repository: "registry.hzdr.de/ufz-tsm/thing-management/frontend/thing-management"
  tag: latest
  pullPolicy: Always
name: thing-management-frontend
port: 80

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: []
  runAsUser: 0
  runAsNonRoot: false
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""