FROM node:24.21.0-slim

RUN npm i -g @quasar/cli

WORKDIR /home/node/app

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]