{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  DB_URL: "postgresql://{{ .Values.global.secrets.THING_MANAGEMENT_DB_USER}}:{{ .Values.global.secrets.THING_MANAGEMENT_DB_PASSWORD}}@{{ .Values.global.envvars.CREATEDB_POSTGRES_HOST }}/{{ .Values.global.envvars.CREATEDB_POSTGRES_DATABASE }}"
  FERNET_ENCRYPTION_SECRET: "{{ .Values.global.secrets.FERNET_ENCRYPTION_SECRET }}"
  MQT_USER: "{{ .Values.global.secrets.MQTT_USER }}"
  OIDC_CLIENT_ID: "{{ .Values.global.secrets.KEYCLOAK_LOCAL_OIDC_CLIENT }}"
  OIDC_CLIENT_SECRET: ""
  OIDC_ADMIN_USERNAME: "{{ .Values.global.secrets.THING_MANAGEMENT_DB_USER }}"
  OIDC_ADMIN_PASSWORD: "{{ .Values.global.secrets.THING_MANAGEMENT_DB_PASSWORD }}"
{{- end }}