#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $FRONTEND_POSTGRES_USER WITH LOGIN PASSWORD '$FRONTEND_POSTGRES_PASS';
    GRANT $FRONTEND_POSTGRES_USER TO postgres;
    CREATE SCHEMA IF NOT EXISTS $FRONTEND_POSTGRES_USER AUTHORIZATION $FRONTEND_POSTGRES_USER;
    SET search_path TO $FRONTEND_POSTGRES_USER;
    GRANT CONNECT ON DATABASE postgres TO $FRONTEND_POSTGRES_USER;
    ALTER ROLE $FRONTEND_POSTGRES_USER SET search_path to $FRONTEND_POSTGRES_USER;
    GRANT USAGE ON SCHEMA $FRONTEND_POSTGRES_USER TO $FRONTEND_POSTGRES_USER;
    GRANT ALL ON SCHEMA $FRONTEND_POSTGRES_USER TO $FRONTEND_POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $FRONTEND_POSTGRES_USER TO $FRONTEND_POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA $FRONTEND_POSTGRES_USER TO $FRONTEND_POSTGRES_USER;
EOSQL