{{- if .Values.enabled }}
{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  ENV_OIDC_CLIENT_ID_PLACEHOLDER: "{{ .Values.global.secrets.KEYCLOAK_DSM_CLIENT_ID }}"
{{- end }}
{{- end }}