stages:
  - test
  - build
  - push

variables:
  HELM_PACKAGE_NAME: "timeio"
  PACKAGE_REGISTRY: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm"
  PACKAGE_REGISTRY_TOKEN: "${CI_JOB_TOKEN}"
  HELM_IMAGE_TAG: "latest"

lint:
  image:
    name: alpine/helm:${HELM_IMAGE_TAG}
    entrypoint: [""]
  stage: test
  script:
    - helm lint timeio

template:
  image:
    name: alpine/helm:${HELM_IMAGE_TAG}
    entrypoint: [""]
  stage: test
  script:
    - helm dependency build timeio || exit 1
    - helm template timeio > /dev/null || exit 1


build:
  image: 
    name: alpine/helm:${HELM_IMAGE_TAG}
    entrypoint: [""]
  stage: build
  script:
    - apk add yq
    - CI_JOB_DATE=$(date +%Y-%m-%d-%H%M%S)
    - helm dependency build timeio
    - VERSION=$(helm show chart timeio | yq .version | tr -d '\n')
    - FULL_VERSION="${VERSION}"
    - echo "Building chart version $FULL_VERSION"
    - helm package timeio --version $FULL_VERSION
  artifacts:
    paths:
      - "./*.tgz"
  only:
    - main


push:
  image: alpine
  stage: push
  before_script:
    - apk add curl
    - CHART=$(ls ./*.tgz)
  script:
    - curl --fail-with-body --request POST --user gitlab-ci-token:${CI_JOB_TOKEN} --form chart=@${CHART} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts
  only:
    - main
