stages:
  - test
  - freeze
  - build

black:
  stage: test
  needs: []
  image: python:3-slim
  before_script:
    - pip install black
  script:
    - black --check api/app/

npm-lint:
  stage: test
  needs: []
  image: node:25
  before_script:
    - cd frontend/app
    - npm ci
  script:
    - npm run lint

freeze:
  stage: freeze
  needs: []
  image: alpine
  artifacts:
    expire_in: 6 weeks
    reports:
      dotenv: date.env
  script:
    - echo "BUILD_DATE=$(date +%Y-%m-%d-%H%M%S)" > date.env

build:
  stage: build
  needs:
    - freeze
    # when black and npm lint are no longer failing, we have to include them here
  image: docker
  services:
    - docker:dind
  before_script: 
    - apk add jq
    - export DSM_API_IMAGE_NAME=$(docker compose config api --format json | jq -r .name)
    - export DSM_FRONTEND_IMAGE_NAME=$(docker compose config frontend --format json | jq -r .name)
  script:
    - docker compose build
    - export DSM_API_IMAGE_ID=$(docker images -f reference=${DSM_API_IMAGE_NAME} -q)
    - export DSM_FRONTEND_IMAGE_ID=$(docker images -f reference=${DSM_FRONTEND_IMAGE_NAME} -q)
    - docker tag ${DSM_API_IMAGE_ID} ${CI_REGISTRY}/${DSM_API_IMAGE_NAME}:${BUILD_DATE}
    - docker tag ${DSM_FRONTEND_IMAGE_ID} ${CI_REGISTRY}/${DSM_FRONTEND_IMAGE_NAME}:${BUILD_DATE}
    - docker tag ${DSM_API_IMAGE_ID} ${CI_REGISTRY}/${DSM_API_IMAGE_NAME}:${CI_COMMIT_REF_NAME}
    - docker tag ${DSM_FRONTEND_IMAGE_ID} ${CI_REGISTRY}/${DSM_FRONTEND_IMAGE_NAME}:${CI_COMMIT_REF_NAME}
    - docker images
    - docker push ${CI_REGISTRY}/${DSM_API_IMAGE_NAME}:${BUILD_DATE}
    - docker push ${CI_REGISTRY}/${DSM_FRONTEND_IMAGE_NAME}:${BUILD_DATE}
    - docker push ${CI_REGISTRY}/${DSM_API_IMAGE_NAME}:${CI_COMMIT_REF_NAME}
    - docker push ${CI_REGISTRY}/${DSM_FRONTEND_IMAGE_NAME}:${CI_COMMIT_REF_NAME}