---
version: "3.9"

include:
  - "docker-compose-base.yml"
  - "docker-compose-worker.yml"
  - "docker-compose-frontend.yml"

services:

  mqtt-cat:
    restart: "${RESTART:-on-failure}"
    image: "eclipse-mosquitto:${MQTT_CAT_IMAGE_TAG:-latest}"
    depends_on:
      mqtt-broker:
        condition: "service_started"
    logging:
      options:
        max-size: "${MQTT_CAT_LOG_SIZE:-100K}"
        max-file: "${MQTT_CAT_FILE_COUNT:-10}"
    command:
      - "mosquitto_sub"
      - "-h"
      - "mqtt-broker"
      - "--pretty"
      - "-u"
      - "${MQTT_USER:?Please define a mqtt user!}"
      - "-P"
      - "${MQTT_PASSWORD:?Please define a mqtt password!}"
      - "-t"
      - "#"
      - "-v"

  monitoring:
    image: "gcr.io/cadvisor/cadvisor:${MONITORING_IMAGE_TAG:-latest}"
    restart: "${RESTART:-on-failure}"
    container_name: "cadvisor"
    ports:
      - "${CADVISOR_PORT:-127.0.0.1:8080}:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
