---
services:

  worker-configdb-updater:
    volumes:
      - ./src:/usr/src/app

  worker-object-storage-setup:
    volumes:
      - ./src:/home/appuser/app/src

  worker-db-setup:
    volumes:
      - ./src:/home/appuser/app/src

  worker-file-ingest:
    volumes:
      - ./src:/home/appuser/app/src

  worker-frost-setup:
    volumes:
      - ./src:/home/appuser/app/src

  worker-run-qaqc:
    volumes:
      - ./src:/home/appuser/app/src

  worker-mqtt-ingest:
    volumes:
      - ./src:/home/appuser/app/src

  worker-mqtt-user-creation:
    volumes:
      - ./src:/home/appuser/app/src

  worker-grafana-dashboard:
    volumes:
      - ./src:/home/appuser/app/src

  worker-grafana-user-orgs:
    volumes:
      - ./src:/home/appuser/app/src

  worker-crontab-setup:
    volumes:
      - ./src:/home/appuser/app/src

  worker-sync-extsftp:
    volumes:
      - ./src:/home/appuser/app/src

  worker-sync-extapis:
    volumes:
      - ./src:/home/appuser/app/src

  worker-sync-sms:
    volumes:
      - ./src:/home/appuser/app/src

  frontend:
    environment:
      - "DJANGO_HELMHOLTZ_CLIENT_ID=${THING_MANAGEMENT_DJANGO_HELMHOLTZ_CLIENT_ID:-timeIO-client}"
      - "DJANGO_HELMHOLTZ_CLIENT_SECRET=${THING_MANAGEMENT_DJANGO_HELMHOLTZ_CLIENT_SECRET:-pUolEnz1Ve5djx9oUpw1KBgB0YgIlUOQ}"
      - "DJANGO_HELMHOLTZ_AAI_CONF_URL=${THING_MANAGEMENT_DJANGO_HELMHOLTZ_AAI_CONF_URL:-http://keycloak:8081/keycloak/realms/demo/.well-known/openid-configuration}"
    volumes:
      - "${DEV_FRONTEND_DIR:-../tsm-frontend}:/home/appuser/app"

  visualization:
    environment:
      - "GF_AUTH_GENERIC_OAUTH_SCOPES=openid email profile eduperson_principal_name"
      - "GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${THING_MANAGEMENT_DJANGO_HELMHOLTZ_CLIENT_ID:-timeIO-client}"
      - "GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${THING_MANAGEMENT_DJANGO_HELMHOLTZ_CLIENT_SECRET:-pUolEnz1Ve5djx9oUpw1KBgB0YgIlUOQ}"
      - "GF_AUTH_GENERIC_OAUTH_AUTH_URL=${VISUALIZATION_GENERIC_OAUTH_AUTH_URL:-http://localhost/keycloak/realms/demo/protocol/openid-connect/auth}"
      - "GF_AUTH_GENERIC_OAUTH_TOKEN_URL=${VISUALIZATION_GENERIC_OAUTH_TOKEN_URL:-http://keycloak:8081/keycloak/realms/demo/protocol/openid-connect/token}"
      - "GF_AUTH_GENERIC_OAUTH_API_URL=${VISUALIZATION_GENERIC_OAUTH_API_URL:-http://keycloak:8081/keycloak/realms/demo/protocol/openid-connect/userinfo}"

  keycloak:
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    volumes:
      - "./keycloak/keycloak-init-dev.template.json:/opt/keycloak/data/import/keycloak-init.json"

  timeio-db-api:
    ports:
      - "127.0.0.1:8001:8001"

  thing-management-api:
    volumes:
      - "${DEV_THING_MANAGEMENT_API_DIR:-../thing-management/backend}/app:/app"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8002
    restart: "no"  

volumes:
  keycloak-data:

