---
version: "3.9"
services:

  # =================================================================
  # SETUP worker (topic: thing_creation)
  # =================================================================

  worker-object-storage-setup:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG:-latest}"
    restart: "${RESTART:-on-failure}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      object-storage:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      MINIO_SECURE: "${MINIO_SECURE:-False}"
      MINIO_URL: "${MINIO_HOST:-minio:9000}"
      MINIO_ACCESS_KEY: "${MINIO_ROOT_USER:?Please define an minio root user!}"
      MINIO_SECURE_KEY: "${MINIO_ROOT_PASSWORD:?Please define an minio root user password!}"
      S3MAP_DB_URL: "postgresql://\
        ${S3MAP_POSTGRES_USER:?Please define an postgres user!}:\
        ${S3MAP_POSTGRES_PASS:?Please define an postgres password!}@\
        ${S3MAP_POSTGRES_HOST:-database}/\
        ${S3MAP_POSTGRES_DB:-postgres}"
    command:
      - "run-create-thing-on-minio-action-service"


  worker-db-setup:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG:-latest}"
    restart: "${RESTART:-on-failure}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      database:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      DATABASE_URL: "postgresql://\
        ${CREATEDB_POSTGRES_USER:?Please define an postgres user!}:\
        ${CREATEDB_POSTGRES_PASSWORD:?Please define an postgres password!}@\
        ${CREATEDB_POSTGRES_HOST:-database}/\
        ${CREATEDB_POSTGRES_DATABASE:-postgres}"
      SMS_URL: "${SMS_URL}"
      CV_URL: "${CV_URL}"
    command:
      - "run-create-database-schema-action-service"


  worker-frost-setup:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG:-latest}"
    restart: "${RESTART:-on-failure}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      database:
        condition: "service_healthy"
    volumes:
      - "./data/tomcat/context:/home/appuser/app/src/CreateNewFrostInstanceAction/tomcat/context_files:rw"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      TOMCAT_PROXY_URL: "${TOMCAT_PROXY_URL:-http://localhost/sta/}"
    command:
      - "run-create-new-frost-server-service"


  worker-mqtt-user-creation:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG:-latest}"
    restart: on-failure
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      database:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      DATABASE_URL: "postgresql://\
        ${CREATEDB_POSTGRES_USER:?Please define an postgres user!}:\
        ${CREATEDB_POSTGRES_PASSWORD:?Please define an postgres password!}@\
        ${CREATEDB_POSTGRES_HOST:-database}/\
        ${CREATEDB_POSTGRES_DATABASE:-postgres}"
    command:
      - run-create-mqtt-user-action-service


  worker-grafana-dashboard:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG:-latest}"
    restart: "${RESTART:-on-failure}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      visualization:
        condition: "service_started"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      GRAFANA_URL: "${GRAFANA_URL:-http://visualization:3000}"
      GRAFANA_USER: "${GRAFANA_USER:?Please define a grafana user!}"
      GRAFANA_PASSWORD: "${GRAFANA_PASSWORD:?Please define a grafana password!}"
      GRAFANA_DEFAULT_DATASOURCE_SSLMODE: "${GRAFANA_DEFAULT_DATASOURCE_SSLMODE:-disable}"
    command:
      - "run-create-grafana-dashboard-service"


  # =================================================================
  # Ingest worker (incoming observations)
  # =================================================================

  worker-file-ingest:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG:-latest}"
    restart: "on-failure"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      object-storage:
        condition: "service_healthy"
      basic-demo-scheduler:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "object_storage_notification"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      MINIO_SECURE: "${MINIO_SECURE:-False}"
      MINIO_URL: "${MINIO_HOST:-minio:9000}"
      MINIO_ACCESS_KEY: "${MINIO_ROOT_USER:?Please define an minio root user!}"
      MINIO_SECURE_KEY: "${MINIO_ROOT_PASSWORD:?Please define an minio root user password!}"
      S3MAP_DB_URL: "postgresql://\
        ${S3MAP_POSTGRES_USER:?Please define an postgres user!}:\
        ${S3MAP_POSTGRES_PASS:?Please define an postgres password!}@\
        ${S3MAP_POSTGRES_HOST:-database}/\
        ${S3MAP_POSTGRES_DB:-postgres}"
      SCHEDULER: "${SCHEDULER:-BasicScheduler}"
      SCHED_HOST: "${SCHED_HOST:-http://basic-demo-scheduler:5000}"
      SCHED_MQTT_BROKER: "${SCHED_MQTT_BROKER:-None}"
      SCHED_MQTT_USER: "${SCHED_MQTT_USER:-None}"
      SCHED_MQTT_PASSWORD: "${SCHED_MQTT_PASSWORD:-None}"
      SCHED_JOB_LOG_LEVEL: "${SCHED_JOB_LOG_LEVEL:-INFO}"
      SCHED_SLURM_RESTAPI_VERSION: "${SCHED_SLURM_RESTAPI_VERSION:-None}"
      SCHED_SLURM_USER: "${SCHED_SLURM_USER:-None}"
      SCHED_SLURM_JWT_TOKEN: "${SCHED_SLURM_JWT_TOKEN:-None}"
      # replaced by SCHED_HOST; remove after dispatcher/MR73 is merged
      SCHED_ENDPOINT_URL: "http://basic-demo-scheduler:5000/extractor/run"
    command:
      - "run-process-new-file-service"


  worker-run-qaqc:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG:-latest}"
    restart: "on-failure"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      basic-demo-scheduler:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "data_parsed"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      SCHEDULER: "${SCHEDULER:-BasicScheduler}"
      SCHED_HOST: "${SCHED_HOST:-http://basic-demo-scheduler:5000}"
      SCHED_MQTT_BROKER: "${SCHED_MQTT_BROKER:-None}"
      SCHED_MQTT_USER: "${SCHED_MQTT_USER:-None}"
      SCHED_MQTT_PASSWORD: "${SCHED_MQTT_PASSWORD:-None}"
      SCHED_JOB_LOG_LEVEL: "${SCHED_JOB_LOG_LEVEL:-INFO}"
      SCHED_SLURM_RESTAPI_VERSION: "${SCHED_SLURM_RESTAPI_VERSION:-None}"
      SCHED_SLURM_USER: "${SCHED_SLURM_USER:-None}"
      SCHED_SLURM_JWT_TOKEN: "${SCHED_SLURM_JWT_TOKEN:-None}"
      # replaced by SCHED_HOST; remove after dispatcher/MR73 is merged
      SCHED_ENDPOINT_URL: "http://basic-demo-scheduler:5000/qaqc/run"
    command:
      - "run-qaqc"


  worker-mqtt-ingest:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG:-latest}"
    restart: on-failure
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      database:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "mqtt_ingest/#"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_INGEST_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_INGEST_PASSWORD:?Please define a mqtt password!}"
    command:
      - parse-data
      - --target-uri
      - "postgresql://\
        ${CREATEDB_POSTGRES_USER:?Please define an postgres user!}:\
        ${CREATEDB_POSTGRES_PASSWORD:?Please define an postgres password!}@\
        ${CREATEDB_POSTGRES_HOST:-database}/\
        ${CREATEDB_POSTGRES_DATABASE:-postgres}"


  # =================================================================
  # other worker
  # =================================================================

  worker-grafana-user-orgs:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG:-latest}"
    restart: "${RESTART:-on-failure}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      visualization:
        condition: "service_started"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "user_login"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      GRAFANA_URL: "${GRAFANA_URL:-http://visualization:3000}"
      GRAFANA_USER: "${GRAFANA_USER:?Please define a grafana user!}"
      GRAFANA_PASSWORD: "${GRAFANA_PASSWORD:?Please define a grafana password!}"
    command:
      - "run-create-grafana-user-orgs-service"


  basic-demo-scheduler:
    image: "registry.hzdr.de/ufz-tsm/tsm-basic-demo-scheduler/basic_demo_scheduler:${SCHEDULER_IMAGE_TAG:-latest}"
    restart: "${RESTART:-on-failure}"
    # prevent blocking/slowing-down of other services
    # if many scheduler jobs occur at the same time
    cpu_count: ${SCHEDULER_CPU_COUNT:-1}
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1" ]
      interval: 10s
      timeout: 2s
      retries: 5
    environment:
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
    command:
      - "--verbose"

  cron-scheduler:
    build:
        context: "cron"
        args:
            UID: "${UID:-1000}"
    restart: "${RESTART:-on-failure}"
    environment:
      SETUP_SERVICE: "${CRON_SETUP_SERVICE}"
      CREATEDB_POSTGRES_USER: "${CRON_CREATEDB_POSTGRES_USER}"
      CREATEDB_POSTGRES_PASSWORD: "${CRON_CREATEDB_POSTGRES_PASSWORD}"
      CREATEDB_POSTGRES_HOST: "${CRON_CREATEDB_POSTGRES_HOST}"
      CREATEDB_POSTGRES_DATABASE: "${CRON_CREATEDB_POSTGRES_DATABASE}"
      SMS_API_ACCESS: "${CRON_SMS_API_ACCESS}"
      SMS_API_URL: "${CRON_SMS_API_URL}"
      SMS_API_TOKEN: "${CRON_SMS_API_TOKEN}"
      CV_API_ACCESS: "${CRON_CV_API_ACCESS}"
      CV_API_URL: "${CRON_CV_API_URL}"
    healthcheck:
      test: ["CMD-SHELL", "service cron status || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - "./cron/crontab.txt:/tmp/crontab.txt:ro"
      - "./cron/scripts:/home/tsm/scripts:ro"