---
version: "3.9"
services:

  init:
    build:
      context: "init"
      args:
        UID: "${UID}"
        GID: "${GID}"
    restart: "no"
    user: "${UID}:${GID}"
    volumes:
      - "./data/minio/certs/:/tmp/certs"


  database:
    restart: "${RESTART:-on-failure}"
    # image: timescale/timescaledb:latest-pg14
    build:
      context: "data/postgres"
      args:
        UID: "${UID}"
    ports:
      - "${POSTGRES_PORT:-127.0.0.1:5432}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:\
                     ?Please define an postgres user!}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:\
                         ?Please define an postgres password!}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      MQTT_AUTH_POSTGRES_USER: "${MQTT_AUTH_POSTGRES_USER:?\
                               Please define a mqtt auth database user!}"
      MQTT_AUTH_POSTGRES_PASS: "${MQTT_AUTH_POSTGRES_PASS:?\
                               Please define a mqtt auth database password!}"
      FRONTEND_POSTGRES_USER: "${FRONTEND_POSTGRES_USER:?\
                               Please define a frontend database user!}"
      FRONTEND_POSTGRES_PASS: "${FRONTEND_POSTGRES_PASS:?\
                               Please define a frontend database password!}"
    volumes:
      - "./mosquitto/mosquitto-go-auth.sh:/docker-entrypoint-initdb.d/mosquitto-go-auth.sh:ro"
      - "./frontend/frontend-database.sh:/docker-entrypoint-initdb.d/frontend-database.sh:ro"
      - "./data/postgres/data:/var/lib/postgresql/data"
      - "./data/postgres/postgres-force-ssl.sh:\
      /docker-entrypoint-initdb.d/postgres-force-ssl.sh"
      - "${POSTGRES_TLS_CERT_PATH:-/tmp/c8cf2d92-\
      73cd-11ec-b035-54e1ad7c5c19}:/var/lib/postgresql/server.crt"
      - "${POSTGRES_TLS_KEY_PATH:-/tmp/c8cf2d92-\
      73cd-11ec-b035-54e1ad7c5c19}:/var/lib/postgresql/server.key"
    user: "${UID}:${GID}"
    command: "${POSTGRES_EXTRA_PARAMS:-}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: "${POSTGRES_HEALTHCHECK_INTERVAL:-10s}"
      timeout: 5s
      retries: 5


  object-storage:
    image: "minio/minio"
    restart: "${RESTART:-on-failure}"
    ports:
      - "${MINIO_SFTP_PORT:-127.0.0.1:40022}:22"
      - "${MINIO_FTP_PORT:-127.0.0.1:40021}:21"
      - "${MINIO_FTP_PASV_PORTS:-127.0.0.1:30000-30010:30000-30010}"
    depends_on:
      mqtt-broker:
        condition: "service_started"
      init:
        condition: "service_completed_successfully"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:?Please define an minio root user!}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:?\
      Please define an minio root user password!}"
      MINIO_BROWSER_REDIRECT_URL: "${MINIO_BROWSER_REDIRECT_URL}"
      MINIO_NOTIFY_MQTT_ENABLE_LOCAL_BROKER: "on"
      MINIO_NOTIFY_MQTT_BROKER_LOCAL_BROKER: "tcp://mqtt-broker:1883"
      MINIO_NOTIFY_MQTT_TOPIC_LOCAL_BROKER: "object_storage_notification"
      MINIO_NOTIFY_MQTT_USERNAME_LOCAL_BROKER: "${MQTT_USER:\
      ?Please define a mqtt user!}"
      MINIO_NOTIFY_MQTT_PASSWORD_LOCAL_BROKER: "${MQTT_PASSWORD:\
      ?Please define a mqtt password!}"
      MINIO_NOTIFY_MQTT_KEEP_ALIVE_INTERVAL_LOCAL_BROKER: "60s"
      #      MINIO_NOTIFY_MQTT_QOS_LOCAL_BROKER: "<string>"
      MINIO_NOTIFY_MQTT_RECONNECT_INTERVAL_LOCAL_BROKER: "60s"
      #      MINIO_NOTIFY_MQTT_QUEUE_DIR_LOCAL_BROKER: "<string>"
      #      MINIO_NOTIFY_MQTT_QUEUE_LIMIT_LOCAL_BROKER: "<string>"
      #      MINIO_NOTIFY_MQTT_COMMENT_LOCAL_BROKER: "<string>"
      MINIO_SERVER_URL: "${MINIO_SERVER_URL:-}"
    volumes:
      - "./data/minio/vol0:/vol0"
      - "./data/minio/vol1:/vol1"
      - "./data/minio/vol2:/vol2"
      - "./data/minio/vol3:/vol3"
      # FTP server tls key and cert
      - "${MINIO_FTP_TLS_CRT:-./data/minio/certs/minio-ftp.crt}:/certs/minio-ftp.crt:ro"
      - "${MINIO_FTP_TLS_KEY:-./data/minio/certs/minio-ftp.key}:/certs/minio-ftp.key:ro"
      # SSH Server key to provide constant ssh host key
      - "${MINIO_SFTP_HOSTKEY:-./data/minio/certs/id_ed25519}:/certs/id_ed25519:ro"
    user: "${UID}:${GID}"
    command:
      - "server"
      - "/vol{0...3}"
      - "--console-address"
      - ":9001"
      - "--ftp"
      - "address=:21"
      - "--ftp"
      - "passive-port-range=30000-30010"
      - "--sftp"
      - "address=:22"
      - "--sftp"
      - "ssh-private-key=/certs/id_ed25519"
      - "--ftp"
      - "tls-private-key=/certs/minio-ftp.key"
      - "--ftp"
      - "tls-public-cert=/certs/minio-ftp.crt"
      - "--json"
    healthcheck:
      test: ["CMD", "curl", "-f", "${MINIO_SERVER_URL\
      :-http://localhost:9000}/minio/health/live"]
      interval: "${MINIO_HEALTHCHECK_INTERVAL:-2s}"
      timeout: 5s
      retries: 15


  worker-object-storage-setup:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:latest"
    restart: "${RESTART:-on-failure}"
    depends_on:
      mqtt-broker:
        condition: "service_started"
      object-storage:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      MINIO_SECURE: "${MINIO_SECURE:-False}"
      MINIO_URL: "${MINIO_HOST:-minio:9000}"
      MINIO_ACCESS_KEY: "${MINIO_ROOT_USER:?Please define an minio root user!}"
      MINIO_SECURE_KEY: "${MINIO_ROOT_PASSWORD:?Please define an minio root user password!}"
    command:
      - "run-create-thing-on-minio-action-service"


  worker-db-setup:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:latest"
    restart: "${RESTART:-on-failure}"
    depends_on:
      - "mqtt-broker"
      - "database"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      DATABASE_URL: "postgresql://\
        ${CREATEDB_POSTGRES_USER:?Please define an postgres user!}:\
        ${CREATEDB_POSTGRES_PASSWORD:?Please define an postgres password!}@\
        ${CREATEDB_POSTGRES_HOST:-database}/\
        ${CREATEDB_POSTGRES_DATABASE:-postgres}"
    command:
      - "run-create-database-schema-action-service"


  worker-file-ingest:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:latest"
    restart: "on-failure"
    depends_on:
      mqtt-broker:
        condition: "service_started"
      object-storage:
        condition: "service_healthy"
      basic-demo-scheduler:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "object_storage_notification"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      MINIO_SECURE: "${MINIO_SECURE:-False}"
      MINIO_URL: "${MINIO_HOST:-minio:9000}"
      MINIO_ACCESS_KEY: "${MINIO_ROOT_USER:?Please define an minio root user!}"
      MINIO_SECURE_KEY: "${MINIO_ROOT_PASSWORD:?Please define an minio root user password!}"
      SCHEDULER_ENDPOINT_URL: "http://basic-demo-scheduler:5000/extractor/run"
    command:
      - "run-process-new-file-service"


  worker-run-qaqc:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:latest"
    restart: "on-failure"
    depends_on:
      mqtt-broker:
        condition: "service_started"
      object-storage:
        condition: "service_healthy"
      basic-demo-scheduler:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "data_parsed"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      SCHEDULER_ENDPOINT_URL: "http://basic-demo-scheduler:5000/qaqc/run"
    command:
      - "run-qaqc"


  worker-mqtt-ingest:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:latest"
    restart: on-failure
    depends_on:
      - mqtt-broker
      - database
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "mqtt_ingest/#"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_INGEST_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_INGEST_PASSWORD:?Please define a mqtt password!}"
    command:
      - parse-data
      - --target-uri
      - "postgresql://\
        ${CREATEDB_POSTGRES_USER:?Please define an postgres user!}:\
        ${CREATEDB_POSTGRES_PASSWORD:?Please define an postgres password!}@\
        ${CREATEDB_POSTGRES_HOST:-database}/\
        ${CREATEDB_POSTGRES_DATABASE:-postgres}"


  worker-mqtt-user-creation:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:latest"
    restart: on-failure
    depends_on:
      - mqtt-broker
      - database
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      DATABASE_URL: "postgresql://\
        ${CREATEDB_POSTGRES_USER:?Please define an postgres user!}:\
        ${CREATEDB_POSTGRES_PASSWORD:?Please define an postgres password!}@\
        ${CREATEDB_POSTGRES_HOST:-database}/\
        ${CREATEDB_POSTGRES_DATABASE:-postgres}"
    command:
      - run-create-mqtt-user-action-service


  basic-demo-scheduler:
    image: "registry.hzdr.de/ufz-tsm/tsm-basic-demo-scheduler/basic_demo_scheduler:latest"
    restart: "${RESTART:-on-failure}"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1" ]
      interval: 10s
      timeout: 2s
      retries: 5
    environment:
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
    command:
      - "--verbose"


  mqtt-broker:
    restart: "${RESTART:-on-failure}"
    image: "iegomez/mosquitto-go-auth:latest"
    depends_on:
      - "database"
    command:
      - "/usr/sbin/mosquitto"
      - "-c"
      - "/var/lib/mosquitto/mosquitto.conf"
    entrypoint:
      - "/docker-entrypoint.sh"
    user: "${UID}:${GID}"
    environment:
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      MQTT_INGEST_USER: "${MQTT_INGEST_USER:?Please define a mqtt user!}"
      MQTT_INGEST_PASSWORD: "${MQTT_INGEST_PASSWORD:?\
                            Please define a mqtt password!}"
      MQTT_AUTH_POSTGRES_HOST: "${MQTT_AUTH_POSTGRES_HOST:?\
                               Please define a mqtt auth database host!}"
      MQTT_AUTH_POSTGRES_PORT: "${MQTT_AUTH_POSTGRES_PORT:?\
                               Please define a mqtt auth database portt!}"
      MQTT_AUTH_POSTGRES_USER: "${MQTT_AUTH_POSTGRES_USER:?\
                               Please define a mqtt auth database user!}"
      MQTT_AUTH_POSTGRES_PASS: "${MQTT_AUTH_POSTGRES_PASS:?\
                               Please define a mqtt auth database password!}"
      MQTT_AUTH_POSTGRES_DB: "${MQTT_AUTH_POSTGRES_DB\
                               :?Please define a mqtt auth database name!}"
      MQTT_AUTH_PG_TLSMODE: "${MQTT_AUTH_PG_TLSMODE\
                              :?Please define a mqtt auth database connection\
                               tls mode!}"
      FRONTEND_MQTT_USER: "${FRONTEND_MQTT_USER\
                            :?Please define a frontend mqtt user!}"
      FRONTEND_MQTT_PASS: "${FRONTEND_MQTT_PASS\
                            :?Please define a frontend mqtt password!}"
    ports:
      - "${MOSQUITTO_PORT:-127.0.0.1:1883}:1883"
      - "${MOSQUITTO_PORT_SECURE:-127.0.0.1:8883}:8883"
    volumes:
      - "${MOSQUITTO_CONFIG:-./mosquitto/mosquitto.dev.conf}\
      :/etc/mosquitto/config/mosquitto.conf:ro"
      - "./data/mosquitto/auth:/mosquitto-auth/"
      - "${MOSQUITTO_TLS_CERT_PATH:-/tmp/c8cf2d92\
      -73cd-11ec-b035-54e1ad7c5c19}:\
      /mosquitto/config/certs/server.crt:ro"
      - "${MOSQUITTO_TLS_KEY_PATH:-/tmp/c8cf2d92\
      -73cd-11ec-b035-54e1ad7c5c19}:\
      /mosquitto/config/certs/server.key:ro"
      - "${MOSQUITTO_TLS_CA_PATH:-/tmp/c8cf2d92\
      -73cd-11ec-b035-54e1ad7c5c19}:/mosquitto/config/certs/ca.crt:ro"
      - "./mosquitto/docker-entrypoint.sh:/docker-entrypoint.sh"
    tmpfs:
      - "/var/lib/mosquitto/:uid=${UID}"
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -t \
      '$$SYS/broker/version' -C 1 -u $${MQTT_USER} \
      -P $${MQTT_PASSWORD} --id docker-compose-healthcheck"]
      interval: "${MQTT_BROKER_HEALTHCHECK_INTERVAL:-10s}"
      timeout: 10s
      retries: 6
    logging:
      options:
        max-size: "${MQTT_BROKER_LOG_SIZE:-100K}"
        max-file: "${MQTT_BROKER_FILE_COUNT:-10}"


  mqtt-cat:
    restart: "${RESTART:-on-failure}"
    image: "eclipse-mosquitto:latest"
    logging:
      options:
        max-size: "${MQTT_CAT_LOG_SIZE:-100K}"
        max-file: "${MQTT_CAT_FILE_COUNT:-10}"
    command:
      - "mosquitto_sub"
      - "-h"
      - "mqtt-broker"
      - "--pretty"
      - "-u"
      - "${MQTT_USER:?Please define a mqtt user!}"
      - "-P"
      - "${MQTT_PASSWORD:?Please define a mqtt password!}"
      - "-t"
      - "#"
      - "-v"


  visualization:
    restart: "${RESTART:-on-failure}"
    image: "grafana/grafana:latest"
    user: "${UID}:${GID}"
    environment:
      - "GF_SECURITY_ADMIN_USER=\
      ${GRAFANA_USER:?Please define a grafana user}"
      - "GF_SECURITY_ADMIN_PASSWORD=\
      ${GRAFANA_PASSWORD:?Please define a grafana password}"
      - "GRAFANA_DEFAULT_DATASOURCE_URL=\
      ${GRAFANA_DEFAULT_DATASOURCE_URL:-database:5432}"
      - "GRAFANA_DEFAULT_DATASOURCE_DATABASE=\
      ${GRAFANA_DEFAULT_DATASOURCE_DATABASE:-postgres}"
      - "GRAFANA_DEFAULT_DATASOURCE_USER=\
      ${GRAFANA_DEFAULT_DATASOURCE_USER:-postgres}"
      - "GRAFANA_DEFAULT_DATASOURCE_PASSWORD=\
      ${GRAFANA_DEFAULT_DATASOURCE_PASSWORD:-postgres}"
      - "GRAFANA_DEFAULT_DATASOURCE_SSLMODE=\
      ${GRAFANA_DEFAULT_DATASOURCE_SSLMODE:-disable}"
      - "GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/visualization/"
      - "GF_SERVER_SERVE_FROM_SUB_PATH=True"
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning/"
      - "./data/grafana/:/var/lib/grafana"


  frontend:
    image: "registry.hzdr.de/ufz-tsm/tsm-frontend/tsm-frontend:latest"
    restart: "${RESTART:-on-failure}"
    command: >
      bash -c "python3 manage.py migrate
      && python3 manage.py loaddata admin_interface_theme_foundation.json
      && python3 manage.py loaddata ufz_theme.json
      && python3 manage.py createsuperuser --noinput
      || echo 'Speruser already created'
      && python3 manage.py collectstatic --noinput
      && gunicorn main.wsgi:application --bind 0.0.0.0:8000 -w 6"
    user: "appuser"
    volumes:
      - "frontend-statics:/home/appuser/app/static"
    entrypoint: ""
    # ports:
    #   - "127.0.0.1:8000:8000"
    environment:
      - "POSTGRES_HOST=${FRONTEND_POSTGRES_HOST}"
      - "POSTGRES_NAME=${FRONTEND_POSTGRES_DB:-postgres}"
      - "POSTGRES_USER=${FRONTEND_POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${FRONTEND_POSTGRES_PASS}"
      - "PUBLISH_THING_TO_BROKER=True"
      - "CREATEDB_POSTGRES_HOST=${CREATEDB_POSTGRES_HOST}"
      - "CREATEDB_POSTGRES_DATABASE=${CREATEDB_POSTGRES_DATABASE}"
      - "MQTT_BROKER_HOST=${FRONTEND_MQTT_HOST}"
      - "MQTT_USER=${FRONTEND_MQTT_USER}"
      - "MQTT_PASSWORD=${FRONTEND_MQTT_PASS}"
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
      - "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-example@example.com}"
      - "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:?Please define a unique and\
        secure Django secret key!}"
      - "DJANGO_DEBUG=${DJANGO_DEBUG:-0}"
      - "DJANGO_TRUSTED_ORIGINS=${DJANGO_TRUSTED_ORIGINS:-http://localhost:80}"
      - "DJANGO_BASE_PATH=${DJANGO_BASE_PATH:-/frontend/}"
      - "DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-}"
      - "POSTGRES_SSLMODE=${DJANGO_POSTGRES_SSLMODE:-verify-full}"
    depends_on:
      database:
        condition: service_healthy
      mqtt-broker:
        condition: service_started


  tsmdl:
    image: "registry.hzdr.de/ufz-tsm/tsm-ufz-tsmdl/tsm-ufz-tsmdl:latest"
    restart: "${RESTART:-on-failure}"
    entrypoint: "/app/start.sh"
    environment:
      DB_URL: "postgresql://\
      ${CREATEDB_POSTGRES_USER:?Please define an postgres user!}:\
      ${CREATEDB_POSTGRES_PASSWORD:?Please define an postgres password!}@\
      ${CREATEDB_POSTGRES_HOST:-database}/\
      ${CREATEDB_POSTGRES_DATABASE:-postgres}"
      WEB_CONCURRENCY: 10
      UVICORN_ARGS: "${UVICORN_ARGS:-} --root-path /tsmdl"
    depends_on:
      database:
        condition: service_healthy


  proxy:
    image: nginx
    restart: "${RESTART:-on-failure}"
    ports:
      - "${PROXY_PLAIN_PORT:-127.0.0.1:80:80}"
      - "${PROXY_TLS_PORT:-127.0.0.1:443:443}"
      - "${PROXY_MINIO_PORT:-127.0.0.1:9000:9000}"
    volumes:
      - "frontend-statics:/home/appuser/app/static"
      - "./nginx/${PROXY_SITE_CONFIG_FILE:-tsm.dev.conf}:/etc/nginx/conf.d/default.conf:ro"
      - "${PROXY_TLS_CERT_PATH:-/tmp/c8cf2d92-73cd-11ec-b035-54e1ad7c5c19}:/etc/ssl/public.crt:ro"
      - "${PROXY_TLS_KEY_PATH:-/tmp/c8cf2d92-73cd-11ec-b035-54e1ad7c5c19}:/etc/ssl/private.key:ro"
    depends_on:
      - "frontend"
      - "visualization"
      - "object-storage"
      - "tsmdl"


  monitoring:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: "cadvisor"
    ports:
    - "${CADVISOR_PORT:-127.0.0.1:8080}:8080"
    volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:ro"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"


volumes:
  frontend-statics:
