---
services:

  worker-configdb-updater:
    volumes:
      - ./src:/usr/src/app

  worker-object-storage-setup:
    volumes:
      - ./src:/home/appuser/app/src

  worker-db-setup:
    volumes:
      - ./src:/home/appuser/app/src

  worker-file-ingest:
    volumes:
      - ./src:/home/appuser/app/src

  worker-frost-setup:
    volumes:
      - ./src:/home/appuser/app/src

  worker-run-qaqc:
    volumes:
      - ./src:/home/appuser/app/src

  worker-mqtt-ingest:
    volumes:
      - ./src:/home/appuser/app/src

  worker-mqtt-user-creation:
    volumes:
      - ./src:/home/appuser/app/src

  worker-grafana-dashboard:
    volumes:
      - ./src:/home/appuser/app/src

  worker-grafana-user-orgs:
    volumes:
      - ./src:/home/appuser/app/src

  worker-crontab-setup:
    volumes:
      - ./src:/home/appuser/app/src

  frontend:
    environment:
      - "DJANGO_HELMHOLTZ_CLIENT_ID=${THING_MANAGEMENT_DJANGO_HELMHOLTZ_CLIENT_ID:-timeIO-client}"
      - "DJANGO_HELMHOLTZ_CLIENT_SECRET=${THING_MANAGEMENT_DJANGO_HELMHOLTZ_CLIENT_SECRET:-pUolEnz1Ve5djx9oUpw1KBgB0YgIlUOQ}"
      - "DJANGO_HELMHOLTZ_AAI_CONF_URL=${THING_MANAGEMENT_DJANGO_HELMHOLTZ_AAI_CONF_URL:-http://keycloak:8081/keycloak/realms/demo/.well-known/openid-configuration}"
    volumes:
      - "${DEV_FRONTEND_DIR:-../tsm-frontend}:/home/appuser/app"

  visualization:
    environment:
      - "GF_AUTH_GENERIC_OAUTH_SCOPES=openid email profile eduperson_principal_name"
      - "GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${THING_MANAGEMENT_DJANGO_HELMHOLTZ_CLIENT_ID:-timeIO-client}"
      - "GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${THING_MANAGEMENT_DJANGO_HELMHOLTZ_CLIENT_SECRET:-pUolEnz1Ve5djx9oUpw1KBgB0YgIlUOQ}"
      - "GF_AUTH_GENERIC_OAUTH_AUTH_URL=${VISUALIZATION_GENERIC_OAUTH_AUTH_URL:-http://localhost/keycloak/realms/demo/protocol/openid-connect/auth}"
      - "GF_AUTH_GENERIC_OAUTH_TOKEN_URL=${VISUALIZATION_GENERIC_OAUTH_TOKEN_URL:-http://keycloak:8081/keycloak/realms/demo/protocol/openid-connect/token}"
      - "GF_AUTH_GENERIC_OAUTH_API_URL=${VISUALIZATION_GENERIC_OAUTH_API_URL:-http://keycloak:8081/keycloak/realms/demo/protocol/openid-connect/userinfo}"

  proxy:
    volumes:
      - "./nginx/tsm.dev.keycloak.conf:/etc/nginx/conf.d/default.conf:ro"

  keycloak:
    image: "quay.io/keycloak/keycloak:24.0.3"
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    user: "${KEYCLOAK_UID:-1000}:${KEYCLOAK_GID:-1000}"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://keycloak-postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_RELATIVE_PATH: ${KC_HTTP_RELATIVE_PATH:-/keycloak}
      KC_PROXY_HEADERS: ${KC_PROXY_HEADERS:-xforwarded}
      KC_HOSTNAME_URL: ${KEYCLOAK_HOSTNAME_URL}
    volumes:
      - "./keycloak/keycloak-init.json:/opt/keycloak/data/import/keycloak-init.json"
    command:
      - start-dev
      - --import-realm
      - --http-port=${KEYCLOAK_PORT}
    depends_on:
      keycloak-postgres:
        condition: service_healthy

  keycloak-postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - "keycloak-data:/var/lib/postgresql/data/"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: "${DATABASE_HEALTHCHECK_INTERVAL}"
      timeout: 5s
      retries: 5

  thing-management-api:
    depends_on:
      keycloak:
        condition: service_started

  timeio-db-api:
    ports:
      - "127.0.0.1:8001:8001"

volumes:
  keycloak-data:

