---
version: "3.9"
services:

  # =================================================================
  # SETUP worker (topic: thing_creation)
  # =================================================================

  worker-object-storage-setup:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG}"
    restart: "${RESTART}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      object-storage:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
      MINIO_SECURE: "${MINIO_SECURE}"
      MINIO_URL: "${MINIO_HOST}"
      MINIO_ACCESS_KEY: "${MINIO_ROOT_USER}"
      MINIO_SECURE_KEY: "${MINIO_ROOT_PASSWORD}"
      S3MAP_DB_URL: "postgresql://\
        ${S3MAP_POSTGRES_USER}:\
        ${S3MAP_POSTGRES_PASS}@\
        ${S3MAP_POSTGRES_HOST}/\
        ${S3MAP_POSTGRES_DB}"
    command:
      - "run-create-thing-on-minio-action-service"


  worker-db-setup:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG}"
    restart: "${RESTART}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      database:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
      DATABASE_URL: "postgresql://\
        ${CREATEDB_POSTGRES_USER}:\
        ${CREATEDB_POSTGRES_PASSWORD}@\
        ${CREATEDB_POSTGRES_HOST}/\
        ${CREATEDB_POSTGRES_DATABASE}"
      SMS_URL: "${SMS_URL}"
      CV_URL: "${CV_URL}"
    command:
      - "run-create-database-schema-action-service"


  worker-frost-setup:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG}"
    restart: "${RESTART}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      database:
        condition: "service_healthy"
    volumes:
      - "./data/tomcat/context:/home/appuser/app/src/CreateNewFrostInstanceAction/tomcat/context_files:rw"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
      TOMCAT_PROXY_URL: "${TOMCAT_PROXY_URL}"
    command:
      - "run-create-new-frost-server-service"


  worker-mqtt-user-creation:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG}"
    restart: on-failure
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      database:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
      DATABASE_URL: "postgresql://\
        ${CREATEDB_POSTGRES_USER}:\
        ${CREATEDB_POSTGRES_PASSWORD}@\
        ${CREATEDB_POSTGRES_HOST}/\
        ${CREATEDB_POSTGRES_DATABASE}"
    command:
      - run-create-mqtt-user-action-service


  worker-grafana-dashboard:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG}"
    restart: "${RESTART}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      visualization:
        condition: "service_started"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
      GRAFANA_URL: "${GRAFANA_URL}"
      GRAFANA_USER: "${GRAFANA_USER}"
      GRAFANA_PASSWORD: "${GRAFANA_PASSWORD}"
      GRAFANA_DEFAULT_DATASOURCE_SSLMODE: "${GRAFANA_DEFAULT_DATASOURCE_SSLMODE}"
    command:
      - "run-create-grafana-dashboard-service"


  # =================================================================
  # Ingest worker (incoming observations)
  # =================================================================

  worker-file-ingest:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG}"
    restart: "on-failure"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      object-storage:
        condition: "service_healthy"
      basic-demo-scheduler:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      TOPIC: "object_storage_notification"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
      MINIO_SECURE: "${MINIO_SECURE}"
      MINIO_URL: "${MINIO_HOST}"
      MINIO_ACCESS_KEY: "${MINIO_ROOT_USER}"
      MINIO_SECURE_KEY: "${MINIO_ROOT_PASSWORD}"
      S3MAP_DB_URL: "postgresql://\
        ${S3MAP_POSTGRES_USER}:\
        ${S3MAP_POSTGRES_PASS}@\
        ${S3MAP_POSTGRES_HOST}/\
        ${S3MAP_POSTGRES_DB}"
      SCHEDULER: "${SCHEDULER}"
      SCHED_HOST: "${SCHED_HOST}"
      SCHED_MQTT_BROKER: "${SCHED_MQTT_BROKER}"
      SCHED_MQTT_USER: "${SCHED_MQTT_USER}"
      SCHED_MQTT_PASSWORD: "${SCHED_MQTT_PASSWORD}"
      SCHED_JOB_LOG_LEVEL: "${SCHED_JOB_LOG_LEVEL}"
      SCHED_SLURM_RESTAPI_VERSION: "${SCHED_SLURM_RESTAPI_VERSION}"
      SCHED_SLURM_USER: "${SCHED_SLURM_USER}"
      SCHED_SLURM_JWT_TOKEN: "${SCHED_SLURM_JWT_TOKEN}"
    command:
      - "run-process-new-file-service"


  worker-run-qaqc:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG}"
    restart: "on-failure"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      basic-demo-scheduler:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      TOPIC: "data_parsed"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
      SCHEDULER: "${SCHEDULER}"
      SCHED_HOST: "${SCHED_HOST}"
      SCHED_MQTT_BROKER: "${SCHED_MQTT_BROKER}"
      SCHED_MQTT_USER: "${SCHED_MQTT_USER}"
      SCHED_MQTT_PASSWORD: "${SCHED_MQTT_PASSWORD}"
      SCHED_JOB_LOG_LEVEL: "${SCHED_JOB_LOG_LEVEL}"
      SCHED_SLURM_RESTAPI_VERSION: "${SCHED_SLURM_RESTAPI_VERSION}"
      SCHED_SLURM_USER: "${SCHED_SLURM_USER}"
      SCHED_SLURM_JWT_TOKEN: "${SCHED_SLURM_JWT_TOKEN}"
    command:
      - "run-qaqc"


  worker-mqtt-ingest:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG}"
    restart: on-failure
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      database:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      TOPIC: "mqtt_ingest/#"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_INGEST_USER}"
      MQTT_PASSWORD: "${MQTT_INGEST_PASSWORD}"
    command:
      - parse-data
      - --target-uri
      - "postgresql://\
        ${CREATEDB_POSTGRES_USER}:\
        ${CREATEDB_POSTGRES_PASSWORD}@\
        ${CREATEDB_POSTGRES_HOST}/\
        ${CREATEDB_POSTGRES_DATABASE}"


  # =================================================================
  # other worker
  # =================================================================

  worker-grafana-user-orgs:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG}"
    restart: "${RESTART}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      visualization:
        condition: "service_started"
    environment:
      LOG_LEVEL: "${LOG_LEVEL}"
      TOPIC: "user_login"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
      GRAFANA_URL: "${GRAFANA_URL}"
      GRAFANA_USER: "${GRAFANA_USER}"
      GRAFANA_PASSWORD: "${GRAFANA_PASSWORD}"
      ALLOWED_VOS: "${ALLOWED_VOS}"
    command:
      - "run-create-grafana-user-orgs-service"


  basic-demo-scheduler:
    image: "registry.hzdr.de/ufz-tsm/tsm-basic-demo-scheduler/basic_demo_scheduler:${SCHEDULER_IMAGE_TAG}"
    restart: "${RESTART}"
    # prevent blocking/slowing-down of other services
    # if many scheduler jobs occur at the same time
    cpu_count: ${SCHEDULER_CPU_COUNT}
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1" ]
      interval: 10s
      timeout: 2s
      retries: 5
    environment:
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
    command:
      - "--verbose"
