---
version: "3.9"

services:

  mqtt-cat:
    restart: "${RESTART}"
    image: "eclipse-mosquitto:${MQTT_CAT_IMAGE_TAG}"
    depends_on:
      mqtt-broker:
        condition: "service_started"
    logging:
      options:
        max-size: "${MQTT_CAT_LOG_SIZE}"
        max-file: "${MQTT_CAT_FILE_COUNT}"
    command:
      - "mosquitto_sub"
      - "-h"
      - "mqtt-broker"
      - "--pretty"
      - "-u"
      - "${MQTT_USER}"
      - "-P"
      - "${MQTT_PASSWORD}"
      - "-t"
      - "#"
      - "-v"

  monitoring:
    image: "gcr.io/cadvisor/cadvisor:${MONITORING_IMAGE_TAG}"
    restart: "${RESTART}"
    container_name: "cadvisor"
    ports:
      - "${CADVISOR_PORT}:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"