---
version: "2.4"
services:
  database:
    restart: "${RESTART:-on-failure}"
    # image: timescale/timescaledb:latest-pg14
    build:
      context: "data/postgres"
      args:
        UID: "${UID}"
    ports:
      - "${POSTGRES_PORT:-127.0.0.1:5432}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:\
                     ?Please define an postgres user!}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:\
                         ?Please define an postgres password!}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      MQTT_AUTH_POSTGRES_USER: "${MQTT_AUTH_POSTGRES_USER:?\
                               Please define a mqtt auth database user!}"
      MQTT_AUTH_POSTGRES_PASS: "${MQTT_AUTH_POSTGRES_PASS:?\
                               Please define a mqtt auth database password!}"
    volumes:
      - "./mosquitto/mosquitto-go-auth.sh:/docker-entrypoint-initdb.d/mosquitto-go-auth.sh:ro"
      - "./data/postgres/data:/var/lib/postgresql/data"
      - "./data/postgres/postgres-force-ssl.sh:\
      /docker-entrypoint-initdb.d/postgres-force-ssl.sh"
      - "${POSTGRES_TLS_CERT_PATH:-/tmp/c8cf2d92-\
      73cd-11ec-b035-54e1ad7c5c19}:/var/lib/postgresql/server.crt"
      - "${POSTGRES_TLS_KEY_PATH:-/tmp/c8cf2d92-\
      73cd-11ec-b035-54e1ad7c5c19}:/var/lib/postgresql/server.key"
    user: "${UID}:${GID}"
    command: "${POSTGRES_EXTRA_PARAMS:-}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  object-storage:
    image: "minio/minio"
    restart: "${RESTART:-on-failure}"
    depends_on:
      - "mqtt-broker"
    ports:
      - "${MINIO_API_PORT:-127.0.0.1:9000}:9000"
      - "${MINIO_CONSOLE_PORT:-127.0.0.1:9001}:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:?Please define an minio root user!}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:?\
      Please define an minio root user password!}"
      MINIO_NOTIFY_MQTT_ENABLE_LOCAL_BROKER: "on"
      MINIO_NOTIFY_MQTT_BROKER_LOCAL_BROKER: "tcp://mqtt-broker:1883"
      MINIO_NOTIFY_MQTT_TOPIC_LOCAL_BROKER: "object_storage_notification"
      MINIO_NOTIFY_MQTT_USERNAME_LOCAL_BROKER: "${MQTT_USER:\
      ?Please define a mqtt user!}"
      MINIO_NOTIFY_MQTT_PASSWORD_LOCAL_BROKER: "${MQTT_PASSWORD:\
      ?Please define a mqtt password!}"
      MINIO_NOTIFY_MQTT_KEEP_ALIVE_INTERVAL_LOCAL_BROKER: "60s"
      #      MINIO_NOTIFY_MQTT_QOS_LOCAL_BROKER: "<string>"
      MINIO_NOTIFY_MQTT_RECONNECT_INTERVAL_LOCAL_BROKER: "60s"
      #      MINIO_NOTIFY_MQTT_QUEUE_DIR_LOCAL_BROKER: "<string>"
      #      MINIO_NOTIFY_MQTT_QUEUE_LIMIT_LOCAL_BROKER: "<string>"
      #      MINIO_NOTIFY_MQTT_COMMENT_LOCAL_BROKER: "<string>"
      MINIO_SERVER_URL: "${MINIO_SERVER_URL:-}"
    volumes:
      - "./data/minio/vol0:/vol0"
      - "./data/minio/vol1:/vol1"
      - "./data/minio/vol2:/vol2"
      - "./data/minio/vol3:/vol3"
      - "${MINIO_TLS_CERT_PATH:-/tmp/c8cf2d92\
      -73cd-11ec-b035-54e1ad7c5c19}:/.minio/certs/public.crt:ro"
      - "${MINIO_TLS_KEY_PATH:-/tmp/c8cf2d92\
      -73cd-11ec-b035-54e1ad7c5c19}:/.minio/certs/private.key:ro"
    user: "${UID}:${GID}"
    command:
      - "server"
      - "/vol{0...3}"
      - "--console-address"
      - ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "${MINIO_SERVER_URL\
      :-http://localhost:9000}/minio/health/live"]
      interval: 2s
      timeout: 5s
      retries: 15

  worker-object-storage-setup:
    build:
      context: ../tsm-dispatcher
    restart: "${RESTART:-on-failure}"
    depends_on:
      mqtt-broker:
        condition: "service_started"
      object-storage:
        condition: "service_healthy"
    command:
      - "--verbose"
      - "--topic"
      - "thing_creation"
      - "--mqtt-broker"
      - "mqtt-broker:1883"
      - "--mqtt-user"
      - "${MQTT_USER:?Please define a mqtt user!}"
      - "--mqtt-password"
      - "${MQTT_PASSWORD:?Please define a mqtt password!}"
      - "run-create-thing-on-minio-action-service"
      - "--minio_secure"
      - "${MINIO_SECURE:-False}"
      - "${MINIO_HOST:-object-storage:9000}"
      - "${MINIO_ROOT_USER:?Please define an minio root user!}"
      - "${MINIO_ROOT_PASSWORD:?Please define an minio root user password!}"

  worker-db-setup:
    build:
      context: ../tsm-dispatcher
    restart: "${RESTART:-on-failure}"
    depends_on:
      - "mqtt-broker"
      - "database"
    command:
      - "--topic"
      - "thing_creation"
      - "--mqtt-broker"
      - "mqtt-broker:1883"
      - "--mqtt-user"
      - "${MQTT_USER:?Please define a mqtt user!}"
      - "--mqtt-password"
      - "${MQTT_PASSWORD:?Please define a mqtt password!}"
      - "run-create-database-schema-action-service"
      - "postgresql://${CREATEDB_POSTGRES_USER:\
      ?Please define an postgres user!}:${CREATEDB_POSTGRES_PASSWORD:\
      ?Please define an postgres password!}@${CREATEDB_POSTGRES_HOST:\
      -database}/${CREATEDB_POSTGRES_DATABASE:-postgres}"

  worker-file-ingest:
    build:
      context: ../tsm-dispatcher
    restart: "on-failure"
    depends_on:
      mqtt-broker:
        condition: "service_started"
      object-storage:
        condition: "service_healthy"
    command:
      - "--topic"
      - "object_storage_notification"
      - "--mqtt-broker"
      - "mqtt-broker:1883"
      - "--mqtt-user"
      - "${MQTT_USER:?Please define a mqtt user!}"
      - "--mqtt-password"
      - "${MQTT_PASSWORD:?Please define a mqtt password!}"
      - "run-process-new-file-service"
      - "--minio_secure"
      - "${MINIO_SECURE:-False}"
      - "${MINIO_HOST:-minio:9000}"
      - "${MINIO_ROOT_USER:?Please define an minio root user!}"
      - "${MINIO_ROOT_PASSWORD:?Please define an minio root user password!}"
      - "http://basic-demo-scheduler:5000/extractor/run"

  worker-mqtt-ingest:
    build:
      context: ../tsm-dispatcher
    restart: on-failure
    depends_on:
      - mqtt-broker
      - database
    command:
      - --topic
      - mqtt_ingest/#
      - --mqtt-broker
      - mqtt-broker:1883
      - --mqtt-user
      - ${MQTT_INGEST_USER:?Please define a mqtt user!}
      - --mqtt-password
      - ${MQTT_INGEST_PASSWORD:?Please define a mqtt password!}
      - parse-data
      - --target-uri
      - "postgresql://${CREATEDB_POSTGRES_USER:\
        ?Please define an postgres user!}:${CREATEDB_POSTGRES_PASSWORD:\
        ?Please define an postgres password!}@${CREATEDB_POSTGRES_HOST:\
        -database}/${CREATEDB_POSTGRES_DATABASE:-postgres}"

  extractor:
    # only used for building the extractor image
    build:
      context: ../tsm-extractor
    image: "extractor:local"
    entrypoint: ["echo", "Service 'extractor' is not intended to run."]

  basic-demo-scheduler:
    build:
      context: ../tsm-basic-demo-scheduler
    image: "basic-demo-scheduler:local"
    restart: "${RESTART:-on-failure}"
    command:
      - "--mqtt-broker"
      - "mqtt-broker:1883"
      - "--mqtt-user"
      - "${MQTT_USER:?Please define a mqtt user!}"
      - "--mqtt-password"
      - "${MQTT_PASSWORD:?Please define a mqtt password!}"
      - "--verbose"

  mqtt-broker:
    restart: "${RESTART:-on-failure}"
    image: "iegomez/mosquitto-go-auth:latest"
    depends_on:
      - "database"
    command:
      - "/usr/sbin/mosquitto"
      - "-c"
      - "/var/lib/mosquitto/mosquitto.conf"
    entrypoint:
      - "/docker-entrypoint.sh"
    user: "${UID}:${GID}"
    environment:
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      MQTT_INGEST_USER: "${MQTT_INGEST_USER:?Please define a mqtt user!}"
      MQTT_INGEST_PASSWORD: "${MQTT_INGEST_PASSWORD:?\
                            Please define a mqtt password!}"
      MQTT_AUTH_POSTGRES_HOST: "${MQTT_AUTH_POSTGRES_HOST:?\
                               Please define a mqtt auth database host!}"
      MQTT_AUTH_POSTGRES_PORT: "${MQTT_AUTH_POSTGRES_PORT:?\
                               Please define a mqtt auth database portt!}"
      MQTT_AUTH_POSTGRES_USER: "${MQTT_AUTH_POSTGRES_USER:?\
                               Please define a mqtt auth database user!}"
      MQTT_AUTH_POSTGRES_PASS: "${MQTT_AUTH_POSTGRES_PASS:?\
                               Please define a mqtt auth database password!}"
      MQTT_AUTH_POSTGRES_DB: "${MQTT_AUTH_POSTGRES_DB\
                               :?Please define a mqtt auth database name!}"
      MQTT_AUTH_PG_TLSMODE: "${MQTT_AUTH_PG_TLSMODE\
                              :?Please define a mqtt auth database connection\
                               tls mode!}"
    ports:
      - "${MOSQUITTO_PORT:-127.0.0.1:1883}:1883"
      - "${MOSQUITTO_PORT_SECURE:-127.0.0.1:8883}:8883"
    volumes:
      - "${MOSQUITTO_CONFIG:-./mosquitto/mosquitto.dev.conf}\
      :/etc/mosquitto/config/mosquitto.conf:ro"
      - "./data/mosquitto/auth:/mosquitto-auth/"
      - "${MOSQUITTO_TLS_CERT_PATH:-/tmp/c8cf2d92\
      -73cd-11ec-b035-54e1ad7c5c19}:\
      /mosquitto/config/certs/server.crt:ro"
      - "${MOSQUITTO_TLS_KEY_PATH:-/tmp/c8cf2d92\
      -73cd-11ec-b035-54e1ad7c5c19}:\
      /mosquitto/config/certs/server.key:ro"
      - "${MOSQUITTO_TLS_CA_PATH:-/tmp/c8cf2d92\
      -73cd-11ec-b035-54e1ad7c5c19}:/mosquitto/config/certs/ca.crt:ro"
      - "./mosquitto/docker-entrypoint.sh:/docker-entrypoint.sh"
    tmpfs:
      - "/var/lib/mosquitto/:uid=${UID}"
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -t \
      '$$SYS/broker/version' -C 1 -u $${MQTT_USER} \
      -P $${MQTT_PASSWORD} --id docker-compose-healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 6
    logging:
      options:
        max-size: "${MQTT_BROKER_LOG_SIZE:-100K}"
        max-file: "${MQTT_BROKER_FILE_COUNT:-10}"

  mqtt-cat:
    restart: "${RESTART:-on-failure}"
    image: "eclipse-mosquitto:latest"
    logging:
      options:
        max-size: "${MQTT_CAT_LOG_SIZE:-100K}"
        max-file: "${MQTT_CAT_FILE_COUNT:-10}"
    command:
      - "mosquitto_sub"
      - "-h"
      - "mqtt-broker"
      - "--pretty"
      - "-u"
      - "${MQTT_USER:?Please define a mqtt user!}"
      - "-P"
      - "${MQTT_PASSWORD:?Please define a mqtt password!}"
      - "-t"
      - "#"
      - "-v"

