---
version: "3.9"
services:

  worker-object-storage-setup:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-db-setup:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-file-ingest:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-frost-setup:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-run-qaqc:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-mqtt-ingest:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-mqtt-user-creation:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-grafana-dashboard:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  basic-demo-scheduler:
    volumes:
      - "${DEV_SCHEDULER_SRC_DIR:-../tsm-basic-demo-scheduler/src}:/home/appuser/app/src"
    ports:
      - "127.0.0.1:5000:5000"

  frontend:
    volumes:
      - "${DEV_FRONTEND_DIR:-../tsm-frontend}:/home/appuser/app"

  tsmdl:
    volumes:
      - "${DEV_TSMDL_SRC_DIR:-../tsm-ufz-tsmdl/app}:/app"
