services:

  api:
    image: time-io-datasource-management-api:dev
    build:
      context: ./api
      dockerfile: docker/Dockerfile-Dev
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8000:8000"
    environment:
      POSTGRES_SERVER: "${POSTGRES_SERVER:-api-db}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-db_dev}"
    volumes:
      - ./api/app:/app:rw,cached
    depends_on:
      - api-db
    command: "fastapi dev --host 0.0.0.0 --port 8000 main.py"

  frontend:
    image: time-io-datasource-management-frontend:dev
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile-Dev
    user: "node"
    working_dir: /home/node/app
    ports:
      - "3000:9000"
    environment:
      OIDC_CLIENT_ID: "${OIDC_CLIENT_ID:-dev-client}"
      OIDC_IDP_URL: "${OIDC_IDP_URL:-http://localhost:8080/keycloak/realms/local-dev}" #url to idp without .well-known
      OIDC_REDIRECT_URI: "${OIDC_REDIRECT_URI:-http://localhost:3000/login-callback}"
      OIDC_SCOPE: "${OIDC_SCOPE:-openid profile eduperson_principal_name eduperson_entitlement eduperson_unique_id email offline_access}"
      OIDC_POST_LOGOUT_REDIRECT_URI: "${OIDC_POST_LOGOUT_REDIRECT_URI:-http://localhost:3000}"
    volumes:
      - ./frontend/app:/home/node/app:rw,cached
    command: "quasar dev"

  keycloak:
    image: "quay.io/keycloak/keycloak:24.0.3"
    ports:
      - "${KEYCLOAK_PORT:-8080}:${KEYCLOAK_PORT:-8080}"
    user: "${KEYCLOAK_UID:-1000}:${KEYCLOAK_GID:-1000}"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: ${KC_DB:-postgres}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE:-keycloak}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA:-public}
      KC_DB_URL: ${KC_DB_URL:-jdbc:postgresql://keycloak-db/keycloak}
      KC_DB_USERNAME: ${KC_DB_USERNAME:-keycloak}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-password}
      KC_HTTP_RELATIVE_PATH: ${KC_HTTP_RELATIVE_PATH:-/keycloak}
#      KC_PROXY_HEADERS: ${KC_PROXY_HEADERS:-xforwarded}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT:-false}
      KC_HOSTNAME_URL: ${KC_HOSTNAME_URL:-http://localhost:${KEYCLOAK_PORT:-8080}/keycloak}
    volumes:
      - "./keycloak/keycloak-init.json:/opt/keycloak/data/import/keycloak-init.json"
    command:
      - start-dev
      - --import-realm
      - --http-port=${KEYCLOAK_PORT:-8080}
    depends_on:
      - keycloak-db

  keycloak-db:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_POSTGRES_PASSWORD:-password}
    volumes:
      - "keycloak-data:/var/lib/postgresql/data/"

  api-db:
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${API_DB_POSTGRES_DB:-db_dev}"
      POSTGRES_USER: "${API_DB_POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${API_DB_POSTGRES_PASSWORD:-postgres}"
    volumes:
      - "api-data:/var/lib/postgresql/data/"

volumes:
  keycloak-data:
  api-data: