---
version: "3.9"
services:

  frontend:
    image: "registry.hzdr.de/ufz-tsm/tsm-frontend/tsm-frontend:${FRONTEND_IMAGE_TAG:-latest}"
    restart: "${RESTART:-on-failure}"
    command: >
      bash -c "python3 manage.py migrate
      && python3 manage.py loaddata admin_interface_theme_foundation.json
      && python3 manage.py loaddata ufz_theme.json
      && python3 manage.py createsuperuser --noinput
      || echo 'Superuser already created'
      && python3 manage.py collectstatic --noinput
      && gunicorn main.wsgi:application --bind 0.0.0.0:8000 -w 6"
    user: "appuser"
    volumes:
      - "frontend-statics:/home/appuser/app/static"
      - "./frontend/user.json:/home/appuser/app/tsm/fixtures/user.json"
      - "./frontend/thing.json:/home/appuser/app/tsm/fixtures/thing.json"
    entrypoint: ""
    # ports:
    #   - "127.0.0.1:8000:8000"
    environment:
      - "POSTGRES_HOST=${FRONTEND_POSTGRES_HOST}"
      - "POSTGRES_NAME=${FRONTEND_POSTGRES_DB:-postgres}"
      - "POSTGRES_USER=${FRONTEND_POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${FRONTEND_POSTGRES_PASS}"
      - "PUBLISH_THING_TO_BROKER=True"
      - "CREATEDB_POSTGRES_HOST=${CREATEDB_POSTGRES_HOST}"
      - "CREATEDB_POSTGRES_DATABASE=${CREATEDB_POSTGRES_DATABASE}"
      - "MQTT_BROKER_HOST=${FRONTEND_MQTT_HOST}"
      - "MQTT_USER=${FRONTEND_MQTT_USER}"
      - "MQTT_PASSWORD=${FRONTEND_MQTT_PASS}"
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
      - "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-example@example.com}"
      - "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:?Please define a unique and\
        secure Django secret key!}"
      - "DJANGO_DEBUG=${DJANGO_DEBUG:-0}"
      - "DJANGO_TRUSTED_ORIGINS=${DJANGO_TRUSTED_ORIGINS:-http://localhost:80}"
      - "DJANGO_BASE_PATH=${DJANGO_BASE_PATH:-/frontend/}"
      - "DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-}"
      - "POSTGRES_SSLMODE=${DJANGO_POSTGRES_SSLMODE:-verify-full}"
      - "DJANGO_HELMHOLTZ_CLIENT_ID=${DJANGO_HELMHOLTZ_CLIENT_ID:-ufz-tsm}"
      - "DJANGO_HELMHOLTZ_CLIENT_SECRET=${DJANGO_HELMHOLTZ_CLIENT_SECRET:-00000000000000000000}"
      - "DJANGO_HELMHOLTZ_AAI_CONF_URL=${DJANGO_HELMHOLTZ_AAI_CONF_URL:\
            -https://login-dev.helmholtz.de/oauth2/.well-known/openid-configuration}"
      - "MINIO_FTP_PORT=${MINIO_FTP_PORT:-127.0.0.1:40021}"
      - "MINIO_SFTP_PORT=${MINIO_SFTP_PORT:-127.0.0.1:40022}"
      - "PROXY_URL=${PROXY_URL:-http://localhost:80}"
    depends_on:
      database:
        condition: service_healthy
      mqtt-broker:
        condition: service_healthy


  proxy:
    image: "nginx:${NGINX_IMAGE_TAG:-latest}"
    restart: "${RESTART:-on-failure}"
    ports:
      - "${PROXY_PLAIN_PORT:-127.0.0.1:80:80}"
      - "${PROXY_TLS_PORT:-127.0.0.1:443:443}"
      - "${PROXY_MINIO_PORT:-127.0.0.1:9000:9000}"
    volumes:
      - "frontend-statics:/home/appuser/app/static"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/${PROXY_SITE_CONFIG_FILE:-tsm.dev.conf}:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/locations:/etc/nginx/locations:ro"
      - "${PROXY_TLS_CERT_PATH:-/tmp/c8cf2d92-73cd-11ec-b035-54e1ad7c5c19}:/etc/ssl/public.crt:ro"
      - "${PROXY_TLS_KEY_PATH:-/tmp/c8cf2d92-73cd-11ec-b035-54e1ad7c5c19}:/etc/ssl/private.key:ro"
    depends_on:
      frontend:
        condition: "service_started"
      visualization:
        condition: "service_started"
      object-storage:
        condition: "service_started"
      tsmdl:
        condition: "service_started"
      frost:
        condition: "service_started"
      init:
        condition: "service_completed_successfully"


volumes:
  frontend-statics:
