---
version: "3.9"
services:

  worker-object-storage-setup:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-db-setup:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-file-ingest:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-frost-setup:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-run-qaqc:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-mqtt-ingest:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-mqtt-user-creation:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-grafana-dashboard:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-grafana-user-orgs:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"

  worker-crontab-setup:
    volumes:
      - "${DEV_DISPATCHER_SRC_DIR:-../tsm-dispatcher/src}:/home/appuser/app/src"


  basic-demo-scheduler:
    volumes:
      - "${DEV_EXTRACTOR_SRC_DIR:-../tsm-extractor/src}:/home/appuser/app/src"
      - "${DEV_SCHEDULER_SRC_DIR:-../tsm-basic-demo-scheduler/src}:/home/appuser/app/basic_demo_scheduler"
    ports:
      - "127.0.0.1:5000:5000"

  frontend:
    volumes:
      - "${DEV_FRONTEND_DIR:-../tsm-frontend}:/home/appuser/app"

  tsmdl:
    volumes:
      - "${DEV_TSMDL_SRC_DIR:-../tsm-ufz-tsmdl/app}:/app"

  keycloak:
    image: "quay.io/keycloak/keycloak:24.0.3"
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    user: "${KEYCLOAK_UID:-1000}:${KEYCLOAK_GID:-1000}"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://keycloak-postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    volumes:
      - "./keycloak/keycloak-init.json:/opt/keycloak/data/import/keycloak-init.json"
    command:
      - start-dev
      - --import-realm
      - --http-port=${KEYCLOAK_PORT}
    depends_on:
      keycloak-postgres:
        condition: service_healthy

  keycloak-postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - "keycloak-data:/var/lib/postgresql/data/"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: "${POSTGRES_HEALTHCHECK_INTERVAL}"
      timeout: 5s
      retries: 5

volumes:
  keycloak-data:

