---
version: "3.9"

include:
  - "docker-compose-base.yml"
  - "docker-compose-worker.yml"

services:

  mqtt-cat:
    restart: "${RESTART:-on-failure}"
    image: "eclipse-mosquitto:${MQTT_CAT_IMAGE_TAG:-latest}"
    depends_on:
      mqtt-broker:
        condition: "service_started"
    logging:
      options:
        max-size: "${MQTT_CAT_LOG_SIZE:-100K}"
        max-file: "${MQTT_CAT_FILE_COUNT:-10}"
    command:
      - "mosquitto_sub"
      - "-h"
      - "mqtt-broker"
      - "--pretty"
      - "-u"
      - "${MQTT_USER:?Please define a mqtt user!}"
      - "-P"
      - "${MQTT_PASSWORD:?Please define a mqtt password!}"
      - "-t"
      - "#"
      - "-v"

  monitoring:
    image: "gcr.io/cadvisor/cadvisor:${MONITORING_IMAGE_TAG:-latest}"
    restart: "${RESTART:-on-failure}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      database:
        condition: "service_healthy"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TOPIC: "thing_creation"
      MQTT_BROKER: "mqtt-broker:1883"
      MQTT_USER: "${MQTT_USER:?Please define a mqtt user!}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:?Please define a mqtt password!}"
      DATABASE_URL: "postgresql://\
        ${CREATEDB_POSTGRES_USER:?Please define an postgres user!}:\
        ${CREATEDB_POSTGRES_PASSWORD:?Please define an postgres password!}@\
        ${CREATEDB_POSTGRES_HOST:-database}/\
        ${CREATEDB_POSTGRES_DATABASE:-postgres}"
      SMS_URL: "${SMS_URL}"
      CV_URL: "${CV_URL}"
    command:
      - "run-create-database-schema-action-service"


  worker-frost-setup:
    image: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher:${DISPATCHER_IMAGE_TAG:-latest}"
    restart: "${RESTART:-on-failure}"
    depends_on:
      mqtt-broker:
        condition: "service_healthy"
      database:
        condition: "service_healthy"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
