apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-certs
data:
  id_ed25519: {{ .Files.Get "conf/id_ed25519" | quote}}
  id_ed25519.pub: {{ .Files.Get "conf/id_ed25519.pub" | quote}}
  minio-ftp.crt: {{ .Files.Get "conf/minio-ftp.crt" | quote }}
  minio-ftp.key: {{ .Files.Get "conf/minio-ftp.key" | quote}}