apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "minio"
            - "server"
            - "--console-address"
            - ":9001"
            - "--ftp"
            - "address=:40021"
            - "--ftp"
            - "passive-port-range=30000-30009"
            - "--sftp"
            - "address=:40022"
            - "--sftp"
            - "ssh-private-key=/certs/id_ed25519"
            - "--ftp"
            - "tls-private-key=/certs/minio-ftp.key"
            - "--ftp"
            - "tls-public-cert=/certs/minio-ftp.crt"
            - "--json"
            - "/vol0"
          envFrom:
            - secretRef:
                name: {{ .Values.name }}-secret
          volumeMounts:
            - mountPath: /vol0
              name: {{ .Values.name }}-pv
            - mountPath: /certs
              name: {{ .Values.name }}-certs
      volumes:
        - name: {{ .Values.name }}-pv
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-pvc
        - name: {{ .Values.name }}-certs
          configMap:
            name: {{ .Values.name }}-certs
