apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-envvars
data:
  MQTT_CLEAN_SESSION: "{{ .Values.global.envvars.MQTT_CLEAN_SESSION }}"
  MQTT_SUBSCRIBE_TOPIC: "frontend_thing_update"
  MQTT_SUBSCRIBE_QOS: "{{ .Values.global.envvars.MQTT_QOS }}"
  MQTT_PUBLISH_TOPIC: "configdb_update"
  MQTT_PUBLISH_QOS: "{{ .Values.global.envvars.MQTT_QOS }}"
  CONFIGDB_CONNECTION_INITIAL_TIMEOUT: "10"
  MQTT_CLIENT_ID: "configdb-updater"
  LOG_LEVEL: "{{ .Values.global.envvars.LOG_LEVEL }}"
  MQTT_BROKER_HOST: "mqtt-broker"
  MQTT_BROKER_PORT: "1883"
  JOURNALING: "{{ .Values.global.envvars.JOURNALING }}"