{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  MQTT_USER: "{{ .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{ .Values.global.secrets.MQTT_PASSWORD }}"
  CONFIGDB_DSN: "postgresql://{{-  .Values.global.secrets.CREATEDB_POSTGRES_USER -}}:{{-  .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD -}}@{{-  .Values.global.envvars.CREATEDB_POSTGRES_HOST -}}/{{-  .Values.global.envvars.CREATEDB_POSTGRES_DATABASE -}}"
  FERNET_ENCRYPTION_SECRET: {{ .Values.global.secrets.FERNET_ENCRYPTION_SECRET | quote }}
{{- end }}