apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-certs
data:
  id_ed25519: {{ .Files.Get "conf/id_ed25519" | b64enc }}
  id_ed25519.pub: {{ .Files.Get "conf/id_ed25519.pub" | b64enc }}
  minio-ftp.crt: {{ .Files.Get "conf/minio-ftp.crt" | b64enc }}
  minio-ftp.key: {{ .Files.Get "conf/minio-ftp.key" | b64enc }}