apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "minio"
            - "server"
            - "--console-address"
            - ":9001"
            - "--json"
            - "/vol0"
          envFrom:
            - secretRef:
                name: {{ .Values.name }}-secret
          volumeMounts:
            - mountPath: /vol0
              name: {{ .Values.name }}-pv
            - mountPath: /certs
              name: {{ .Values.name }}-certs
      volumes:
        - name: {{ .Values.name }}-pv
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-data-pvc
        - name: {{ .Values.name }}-certs
          secret:
            secretName: {{ .Values.name }}-certs
