apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  MINIO_ROOT_USER: "{{  .Values.global.secrets.MINIO_ROOT_USER }}"
  MINIO_ROOT_PASSWORD: "{{  .Values.global.secrets.MINIO_ROOT_PASSWORD }}"
  MINIO_SERVER_URL: "{{  .Values.global.ingress.url }}:9000"
  MINIO_BROWSER_REDIRECT_URL: "{{  .Values.global.ingress.url }}/object-storage/"
  MINIO_NOTIFY_MQTT_ENABLE_LOCAL_BROKER: "{{  .Values.global.secrets.MINIO_NOTIFY_MQTT_ENABLE_LOCAL_BROKER }}"
  MINIO_NOTIFY_MQTT_BROKER_LOCAL_BROKER: "{{  .Values.global.secrets.MINIO_NOTIFY_MQTT_BROKER_LOCAL_BROKER }}"
  MINIO_NOTIFY_MQTT_TOPIC_LOCAL_BROKER: "{{  .Values.global.secrets.MINIO_NOTIFY_MQTT_TOPIC_LOCAL_BROKER }}"
  MINIO_NOTIFY_MQTT_USERNAME_LOCAL_BROKER: "{{  .Values.global.secrets.MINIO_NOTIFY_MQTT_USERNAME_LOCAL_BROKER }}"
  MINIO_NOTIFY_MQTT_PASSWORD_LOCAL_BROKER: "{{  .Values.global.secrets.MINIO_NOTIFY_MQTT_PASSWORD_LOCAL_BROKER }}"
  MINIO_NOTIFY_MQTT_QOS_LOCAL_BROKER: "{{  .Values.global.secrets.MINIO_NOTIFY_MQTT_QOS_LOCAL_BROKER }}"
  MINIO_NOTIFY_MQTT_KEEP_ALIVE_INTERVAL_LOCAL_BROKER: "{{  .Values.global.secrets.MINIO_NOTIFY_MQTT_KEEP_ALIVE_INTERVAL_LOCAL_BROKER }}"
  MINIO_NOTIFY_MQTT_RECONNECT_INTERVAL_LOCAL_BROKER: "{{  .Values.global.secrets.MINIO_NOTIFY_MQTT_RECONNECT_INTERVAL_LOCAL_BROKER }}"