replicaCount: 1

image:
  repository: "registry.hzdr.de/ufz-tsm/tsm-orchestration/dispatcher"
  tag: "2025-07-29-064436"
  pullPolicy: Always
name: worker-file-ingest

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""