{{- if .Values.enabled }}
{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "{{ .Values.global.secrets.KEYCLOAK_ADMIN_USER }}"
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.global.secrets.KEYCLOAK_ADMIN_PASS }}"
  KEYCLOAK_DSM_CLIENT_ID: "{{ .Values.global.secrets.KEYCLOAK_DSM_CLIENT_ID }}"
  KEYCLOAK_GRAFANA_CLIENT_ID: "{{ .Values.global.secrets.KEYCLOAK_GRAFANA_CLIENT_ID}}"
  KEYCLOAK_GRAFANA_CLIENT_SECRET: "{{ .Values.global.secrets.KEYCLOAK_GRAFANA_CLIENT_SECRET }}"
  KEYCLOAK_GENERIC_OIDC_CLIENT_ID: "{{ .Values.global.secrets.KEYCLOAK_GENERIC_OIDC_CLIENT }}"
  KC_DB_USERNAME: "{{ .Values.global.secrets.KEYCLOAK_DB_USER }}"
  KC_DB_PASSWORD: "{{ .Values.global.secrets.KEYCLOAK_DB_PASSWORD }}"
  MQTT_USER: "{{ .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{ .Values.global.secrets.MQTT_PASSWORD }}"
{{- end }}
{{- end }}