apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-entrypoint
data:
  postgres-force-ssl.sh: {{ .Files.Get "conf/sh/postgres-force-ssl.sh" | quote }}
  postgis.sh: {{ .Files.Get "conf/sh/postgis.sh" | quote }}
  sms_init_tables.sh: {{ .Files.Get "conf/sh/sms_init_tables.sh" | quote }}
  sms_cv_init_tables.sh: {{ .Files.Get "conf/sh/sms_cv_init_tables.sh" | quote }}
  frontend-database.sh: {{ .Files.Get "conf/sh/frontend-database.sh" | quote }}
  mosquitto-go-auth.sh: {{ .Files.Get "conf/sh/mosquitto-go-auth.sh" | quote }}
  s3_to_db.sh: {{ .Files.Get "conf/sh/s3_to_db.sh" | quote }}