apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-envvars
data:
  PGDATA: "{{  .Values.global.envvars.PGDATA }}"
  POSTGRES_PORT: "{{  .Values.global.envvars.POSTGRES_PORT }}"
  POSTGRES_TLS_CERT_PATH: "{{  .Values.global.envvars.POSTGRES_TLS_CERT_PATH }}"
  POSTGRES_TSL_KEY_PATH: "{{  .Values.global.envvars.POSTGRES_TSL_KEY_PATH }}"
  CREATEDB_POSTGRES_HOST: "{{  .Values.global.envvars.CREATEDB_POSTGRES_HOST }}"
  CREATEDB_POSTGRES_PORT: "{{  .Values.global.envvars.CREATEDB_POSTGRES_PORT }}"
  CREATEDB_POSTGRES_DATABASE: "{{  .Values.global.envvars.CREATEDB_POSTGRES_DATABASE }}"
  MQTT_AUTH_POSTGRES_HOST: "{{  .Values.global.envvars.MQTT_AUTH_POSTGRES_HOST }}"
  MQTT_AUTH_POSTGRES_PORT: "{{  .Values.global.envvars.MQTT_AUTH_POSTGRES_PORT }}"
  MQTT_AUTH_POSTGRES_DB: "{{  .Values.global.envvars.MQTT_AUTH_POSTGRES_DB }}"
  MQTT_AUTH_PG_TLSMODE: "{{  .Values.global.envvars.MQTT_AUTH_PG_TLSMODE }}"
  FRONTEND_POSTGRES_HOST: "{{  .Values.global.envvars.FRONTEND_POSTGRES_HOST }}"
  FRONTEND_POSTGRES_PORT: "{{  .Values.global.envvars.FRONTEND_POSTGRES_PORT }}"
  FRONTEND_POSTGRES_DB: "{{  .Values.global.envvars.FRONTEND_POSTGRES_DB }}"
  S3MAP_POSTGRES_HOST: "{{  .Values.global.envvars.S3MAP_POSTGRES_HOST }}"
  S3MAP_POSTGRES_PORT: "{{  .Values.global.envvars.S3MAP_POSTGRES_PORT }}"
  S3MAP_POSTGRES_DB: "{{  .Values.global.envvars.S3MAP_POSTGRES_DB }}"
  SMS_DB_PORT: "{{  .Values.global.envvars.SMS_DB_PORT }}"
  SMS_DB_DB: "{{  .Values.global.envvars.SMS_DB_DB }}"
  SMS_DB_HOST: "{{  .Values.global.envvars.SMS_DB_HOST }}"
  SMS_URL: "{{  .Values.global.envvars.SMS_URL }}"
  SMS_ACCESS_TYPE: "{{  .Values.global.envvars.SMS_ACCESS_TYPE }}"
  CV_DB_PORT: "{{  .Values.global.envvars.CV_DB_PORT }}"
  CV_DB_DB: "{{  .Values.global.envvars.CV_DB_DB }}"
  CV_DB_HOST: "{{  .Values.global.envvars.CV_DB_HOST }}"
  CV_URL: "{{  .Values.global.envvars.CV_URL }}"
  CV_ACCESS_TYPE: "{{  .Values.global.envvars.CV_ACCESS_TYPE }}"