apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-envvars
data:
  PGDATA: "{{  .Values.global.envvars.PGDATA }}"
  POSTGRES_PORT: "{{  .Values.global.envvars.POSTGRES_PORT }}"
  POSTGRES_TLS_CERT_PATH: "{{  .Values.global.envvars.POSTGRES_TLS_CERT_PATH }}"
  POSTGRES_TSL_KEY_PATH: "{{  .Values.global.envvars.POSTGRES_TSL_KEY_PATH }}"
  CREATEDB_POSTGRES_HOST: "{{  .Values.global.envvars.CREATEDB_POSTGRES_HOST }}"
  CREATEDB_POSTGRES_PORT: "{{  .Values.global.envvars.CREATEDB_POSTGRES_PORT }}"
  CREATEDB_POSTGRES_DATABASE: "{{  .Values.global.envvars.CREATEDB_POSTGRES_DATABASE }}"