{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  POSTGRES_USER: "{{  .Values.global.secrets.CREATEDB_POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{  .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD }}"
  CREATEDB_POSTGRES_USER: "{{  .Values.global.secrets.CREATEDB_POSTGRES_USER }}"
  CREATEDB_POSTGRES_PASSWORD: "{{  .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD }}"
  MQTT_AUTH_POSTGRES_USER: "{{  .Values.global.secrets.MQTT_AUTH_POSTGRES_USER }}"
  MQTT_AUTH_POSTGRES_PASS: "{{  .Values.global.secrets.MQTT_AUTH_POSTGRES_PASS }}"
  FRONTEND_POSTGRES_USER: "{{  .Values.global.secrets.FRONTEND_POSTGRES_USER }}"
  FRONTEND_POSTGRES_PASS: "{{  .Values.global.secrets.FRONTEND_POSTGRES_PASS }}"
  S3MAP_POSTGRES_USER: "{{  .Values.global.secrets.S3MAP_POSTGRES_USER }}"
  S3MAP_POSTGRES_PASS: "{{  .Values.global.secrets.S3MAP_POSTGRES_PASS }}"
  SMS_DB_USER: "{{  .Values.global.secrets.CREATEDB_POSTGRES_USER }}"
  SMS_DB_PASSWORD: "{{  .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD }}"
  CV_DB_USER: "{{  .Values.global.secrets.CREATEDB_POSTGRES_USER }}"
  CV_DB_PASSWORD: "{{  .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD }}"
{{- end }}