apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  SETUP_SERVICE: "{{ .Values.envvars.CRON_SETUP_SERVICE }}"
  CREATEDB_POSTGRES_USER: "{{ .Values.envvars.CREATEDB_POSTGRES_USER }}"
  CREATEDB_POSTGRES_PASSWORD: "{{ .Values.envvars.CREATEDB_POSTGRES_PASSWORD }}"
  CREATEDB_POSTGRES_HOST: "{{ .Values.envvars.CREATEDB_POSTGRES_HOST }}"
  CREATEDB_POSTGRES_DATABASE: "{{ .Values.envvars.CREATEDB_POSTGRES_DATABASE }}"
  SMS_ACCESS_TYPE: "{{ .Values.envvars.SMS_ACCESS_TYPE }}"
  SMS_API_URL: "{{ .Values.envvars.SMS_URL }}backend/api/v1/"
  SMS_API_TOKEN: "{{ .Values.envvars.SMS_API_TOKEN }}"
  CV_ACCESS_TYPE: "{{ .Values.envvars.CV_ACCESS_TYPE }}"
  CV_API_URL: "{{ .Values.envvars.CV_API_URL }}api/v1/"
  LOG_LEVEL: "{{ .Values.envvars.LOG_LEVEL }}"
  MINIO_URL: "{{ .Values.envvars.MINIO_HOST }}"
  MIINO_SECURE: "{{ .Values.envvars.MINIO_SECURE }}"
  FTP_AUTH_DB_DSN: "postgresql://{{ .Values.envvars.FRONTEND_POSTGRES_USER }}:{{ .Values.envvars.FRONTEND_POSTGRES_PASS }}@{{ .Values.envvars.FRONTEND_POSTGRES_HOST }}/{{ .Values.envvars.FRONTEND_POSTGRES_DB }}"