apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  SETUP_SERVICE: "{{  .Values.global.secrets.CRON_SETUP_SERVICE }}"
  CREATEDB_POSTGRES_USER: "{{  .Values.global.secrets.CREATEDB_POSTGRES_USER }}"
  CREATEDB_POSTGRES_PASSWORD: "{{  .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD }}"
  CREATEDB_POSTGRES_HOST: "{{  .Values.global.secrets.CREATEDB_POSTGRES_HOST }}"
  CREATEDB_POSTGRES_DATABASE: "{{  .Values.global.secrets.CREATEDB_POSTGRES_DATABASE }}"
  SMS_ACCESS_TYPE: "{{  .Values.global.secrets.SMS_ACCESS_TYPE }}"
  SMS_API_URL: "{{  .Values.global.secrets.SMS_URL }}backend/api/v1/"
  SMS_API_TOKEN: "{{  .Values.global.secrets.SMS_API_TOKEN }}"
  CV_ACCESS_TYPE: "{{  .Values.global.secrets.CV_ACCESS_TYPE }}"
  CV_API_URL: "{{  .Values.global.secrets.CV_API_URL }}api/v1/"
  LOG_LEVEL: "{{  .Values.global.secrets.LOG_LEVEL }}"
  MINIO_URL: "{{  .Values.global.secrets.MINIO_HOST }}"
  MIINO_SECURE: "{{  .Values.global.secrets.MINIO_SECURE }}"
  FTP_AUTH_DB_DSN: "postgresql://{{  .Values.global.secrets.FRONTEND_POSTGRES_USER }}:{{  .Values.global.secrets.FRONTEND_POSTGRES_PASS }}@{{  .Values.global.secrets.FRONTEND_POSTGRES_HOST }}/{{  .Values.global.secrets.FRONTEND_POSTGRES_DB }}"