{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  FLYWAY_USER: {{  .Values.global.secrets.CREATEDB_POSTGRES_USER | quote }}
  FLYWAY_PASSWORD: {{ .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD | quote }}
  FLYWAY_PLACEHOLDERS_CONFIGDB_USER: {{ .Values.global.secrets.CONFIGDB_POSTGRES_USER | quote }}
  FLYWAY_PLACEHOLDERS_CONFIGDB_PASSWORD: {{ .Values.global.secrets.CONFIGDB_POSTGRES_PASSWORD | quote }}
  FLYWAY_PLACEHOLDERS_MQTT_AUTH_DB_USER: {{ .Values.global.secrets.MQTT_AUTH_POSTGRES_USER | quote }}
  FLYWAY_PLACEHOLDERS_MQTT_AUTH_DB_PASSWORD: {{ .Values.global.secrets.MQTT_AUTH_POSTGRES_PASS | quote }}
  FLYWAY_PLACEHOLDERS_SMS_DB_USER: {{ .Values.global.secrets.SMS_DB_USER | quote }}
  FLYWAY_PLACEHOLDERS_SMS_DB_PASSWORD: {{ .Values.global.secrets.SMS_DB_PASSWORD | quote }}
  FLYWAY_PLACEHOLDERS_CV_DB_USER: {{ .Values.global.secrets.SMS_DB_USER | quote }}
  FLYWAY_PLACEHOLDERS_CV_DB_PASSWORD: {{ .Values.global.secrets.SMS_DB_PASSWORD | quote }}
  FLYWAY_PLACEHOLDERS_KEYCLOAK_DB_USER: {{ .Values.global.secrets.KEYCLOAK_DB_USER | quote }}
  FLYWAY_PLACEHOLDERS_KEYCLOAK_DB_PASSWORD: {{ .Values.global.secrets.KEYCLOAK_DB_PASSWORD | quote }}
  FLYWAY_PLACEHOLDERS_MONITORING_DB_USER: {{ .Values.global.secrets.MONITORING_DB_USER | quote }}
  FLYWAY_PLACEHOLDERS_MONITORING_DB_PASSWORD: {{ .Values.global.secrets.MONITORING_DB_PASSWORD | quote }}
  FLYWAY_PLACEHOLDERS_DSM_DB_USER: {{ .Values.global.secrets.DSM_API_DATABASE_USER | quote }}
  FLYWAY_PLACEHOLDERS_DSM_DB_PASSWORD: {{ .Values.global.secrets.DSM_API_DATABASE_PASS | quote }}
{{- end }}