{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  MQTT_USER: "{{  .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{  .Values.global.secrets.MQTT_PASSWORD }}"
  GRAFANA_USER: "{{  .Values.global.secrets.GRAFANA_USER }}"
  GRAFANA_PASSWORD: "{{  .Values.global.secrets.GRAFANA_PASSWORD }}"
{{- end }}