{{- if and .Values.enabled .Values.global.createConfigMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-envvars
data:
  LOG_LEVEL: "{{ .Values.global.envvars.LOG_LEVEL }}"
  TOPIC: "sync_sms"
  MQTT_BROKER: "mosquitto:1883"
  MQTT_CLIENT_ID: "sync-sms"
  MQTT_CLEAN_SESSION: "{{ .Values.global.envvars.MQTT_CLEAN_SESSION }}"
  MQTT_QOS: "{{ .Values.global.envvars.MQTT_QOS }}"
  JOURNALING: "{{ .Values.global.envvars.JOURNALING }}"
  CV_API_URL: "{{ .Values.global.envvars.CV_URL }}api/v1/"
{{- end }}
