replicaCount: 1

enabled: true

image:
  repository: "registry.hzdr.de/ufz-tsm/tsm-orchestration/keycloak-prod"
  tag: 26.4
  pullPolicy: Always
name: keycloak
port: 8081

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""