SET search_path to config_db;

ALTER TABLE "thing"
    ADD COLUMN mqtt_sub_id BIGINT UNIQUE NULL;

CREATE TABLE "mqtt_sub"
(
    "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "external_mqtt_address" VARCHAR(255)     NOT NULL,
    "external_mqtt_port"    INTEGER          NOT NULL,
    "external_mqtt_username" VARCHAR(255)    NULL,
    "external_mqtt_password" VARCHAR(255)    NULL,
    "external_mqtt_ca_cert" TEXT             NULL,
    "external_mqtt_client_cert" TEXT         NULL,
    "external_mqtt_client_key" TEXT          NULL,
    "external_mqtt_topic"   VARCHAR(255)     NOT NULL
);
