CREATE TABLE "ingest_external_mqtt"
(
    "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "external_mqtt_address" VARCHAR(255)     NOT NULL,
    "external_mqtt_port"    INTEGER          NOT NULL,
    "external_mqtt_username" VARCHAR(255)    NULL,
    "external_mqtt_password" VARCHAR(255)    NULL,
    "external_mqtt_ca_cert" TEXT             NULL,
    "external_mqtt_client_cert" TEXT         NULL,
    "external_mqtt_client_key" TEXT          NULL,
    "external_mqtt_topic"   VARCHAR(255)     NOT NULL,
    "enabled"   BOOLEAN    NOT NULL
);

CREATE TABLE "ingest_http"
(
    "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "path_for_posts" VARCHAR(255)    NULL,
    "file_type" VARCHAR(255)    NULL,
    "enabled"   BOOLEAN     NOT NULL
);