apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /usr/local/tomcat/conf/Catalina/localhost
              name: {{ .Values.name }}-context
            - mountPath: /usr/local/tomcat/webapps/ROOT/index.jsp
              name: {{ .Values.name }}-index
              subPath: index.jsp
        - name: {{ .Values.worker.name }}
          image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command:
            - python3
            - main.py
            - create-frost-instance
          envFrom:
            - secretRef:
                name: {{ .Values.worker.name }}-secret
          volumeMounts:
            - mountPath: /home/appuser/app/src/CreateNewFrostInstanceAction/tomcat/context_files
              name: {{ .Values.name }}-context
      volumes:
        - name: {{ .Values.name }}-context
          persistentVolumeClaim:
            claimName: tomcat-context-pvc
        - name: {{ .Values.name }}-index
          configMap:
            name: {{ .Values.name }}-index