## HTTP - INPUT
## Allows Bento to save stream-configs - in case of restart, ...

# All config fields, showing default values
input:
  http_server:
    address: "0.0.0.0:4200"
    path: /streams/
    # expects somthing like /streams/{ingest-type}/{thing-uuid}
    ws_path: /streams/ws
    ws_welcome_message: ""
    ws_rate_limit_message: ""
    allowed_verbs:
      - POST
      - PUT
      - DELETE
    timeout: 5s
    rate_limit: ""
    cert_file: ""
    key_file: ""
    cors:
      enabled: false
      allowed_origins: []
    sync_response:
      status: "200"
      headers:
        Content-Type: application/octet-stream
      metadata_headers:
        include_prefixes: []
        include_patterns: []

buffer:
  type: none

pipeline:
  processors:
    - mapping: |
        root = content()
        verb = metadata("http_server_request_method")   # POST / DELETE
        req_path = metadata("http_server_request_path") # /streams/... 
        meta.verb = verb
        meta.req_path = req_path
        # same path you used to persist
        meta.file_path = "/data/streams" + req_path + ".json"
        meta.api_path = req_path.replace("/streams/*/", "/streams/")

    - switch:
      cases:
        - cond: 'meta("verb") == "DELETE"'
          pipeline:
            processors:
              - file:
                  operation: delete
                  path: '${! meta("file_path") }'
            outputs: []   # drop the message, nothing to forward
        - cond: 'true'
          pipeline:
            processors:
              # replace your file output with a file processor write
              - file:
                  operation: write
                  path: '${! meta("file_path") }'

    - mapping: |
        root = content()
        # ignores * for external_mqtt and http
        meta path_for_api = metadata("http_server_request_path").replace("/streams/*/", "/streams/")

output:
  broker:
    pattern: fan_out
    outputs:
    - http_client:
        url: 'http://localhost:4195${! metadata("path_for_api") }'
        verb: POST
        headers: {}
        rate_limit: "" # No default (optional)
        timeout: 5s
        max_in_flight: 64
        batching:
          count: 0
          byte_size: 0
          period: ""
          jitter: 0
          check: ""
#    - file:
#        path: '${! metadata("http_server_request_path") }.json'
#        codec: all-bytes