apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-envvars
data:
  LOG_LEVEL: "{{  .Values.global.envvars.LOG_LEVEL }}"
  MQTT_CLIENT_ID: ""
  MQTT_CLEAN_SESSION: "{{  .Values.global.envvars.MQTT_CLEAN_SESSION }}"
  MQTT_QOS: "{{  .Values.global.envvars.MQTT_QOS }}"
  MQTT_BROKER_HOST: "mqtt-broker"
  MQTT_BROKER_PORT: "1883"
  MQTT_SUBSCRIBE_TOPIC: "data_parsed"
  MQTT_SUBSCRIBE_QOS: "1"
  MQTT_PUBLISH_TOPIC: "qaqc_done"
  MQTT_PUBLISH_QOS: "1"
  CONFIGDB_CONNECTION_INITIAL_TIMEOUT: "10"
  DB_API_BASE_URL: "{{ .Values.global.envvars.DB_API_BASE_URL }}"
