{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  MQTT_USER: "{{  .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{  .Values.global.secrets.MQTT_PASSWORD }}"
  SCHED_MQTT_USER: "{{  .Values.global.secrets.MQTT_USER }}"
  SCHED_MQTT_PASSWORD: "{{  .Values.global.secrets.MQTT_PASSWORD }}"
  SCHED_SLURM_USER: "{{  .Values.global.secrets.SCHED_SLURM_USER }}"
  SCHED_SLURM_JWT_TOKEN: "{{  .Values.global.secrets.SCHED_SLURM_JWT_TOKEN }}"
{{- end }}