apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-migrations
data:
  {{- $files := .Files.Glob "conf/migrations/*" }}
  {{- range $path, $file := $files }}
  {{ $base := base $path }}
  {{ $base }}: {{ $file | quote }}
  {{- end }}