apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: mqtt
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
{{- if .Values.tls.enabled }}
    - name: mqtts
      protocol: TCP
      port: {{ .Values.tls.port }}
      targetPort: {{ .Values.tls.port }}
{{- end }}