{{- if .Values.enabled }}
{{- $secretName := "" }}
{{- if .Values.global.createSecrets }}
  {{- $secretName = printf "%s-secret" .Values.name }}
{{- else }}
  {{- $secretName = index .Values.global .Values.name "existingSecret" }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        checksum/envvars: {{ include (print $.Template.BasePath "/envvars.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: "mqtt-connection-check"
        image: "eclipse-mosquitto:2.0"
        command: [ "sh", "/tmp/init-mqtt-worker/init-mqtt-worker.sh" ]
        volumeMounts:
          - name: init-mqtt-worker
            mountPath: /tmp/init-mqtt-worker
        envFrom:
          - configMapRef:
              name: {{ .Values.name }}-envvars
          - secretRef:
              name: {{ $secretName }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          capabilities:
            drop: {{ .Values.securityContext.capabilities.drop }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          seccompProfile:
            type: {{ .Values.securityContext.seccompProfile.type }}
        command: ["python3", "run_mqtt_ingest.py"]
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-envvars
        - secretRef:
            name: {{ $secretName }}
      volumes:
        - name: init-mqtt-worker
          configMap:
            name: init-mqtt-worker
{{- end }}
