apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "{{ .Values.envvars.GRAFANA_USER}}"
  GF_SECURITY_ADMIN_PASSWORD: "{{ .Values.envvars.GRAFANA_PASSWORD}}"
  GF_SERVER_ROOT_URL: "{{ .Values.envvars.PROXY_URL}}/{{ .Values.name }}/"
  GF_SERVER_SERVE_FROM_SUB_PATH: "true"
  GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
  GF_AUTH_GENERIC_OAUTH_NAME: "OpenID Connect"
  GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .Values.envvars.OIDC_CLIENT_ID }}"
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .Values.envvars.OIDC_CLIENT_SECRET }}"
  GF_AUTH_GENERIC_OAUTH_SCOPES: "email profile eduperson_principal_name"
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: "{{ .Values.envvars.OIDC_AUTH_URL }}"
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "{{ .Values.envvars.OIDC_TOKEN_URL }}"
  GF_AUTH_GENERIC_OAUTH_API_URL: "{{ .Values.envvars.OIDC_API_URL }}"
  GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: "eduperson_principal_name"
  GF_AUTH_OAUTH_SKIP_ORG_ROLE_UPDATE_SYNC: "true"