apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          capabilities:
            drop: {{ .Values.securityContext.capabilities.drop }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          seccompProfile:
            type: {{ .Values.securityContext.seccompProfile.type }}
        volumeMounts:
        - mountPath: /usr/local/tomcat/conf/Catalina/localhost
          name: {{ .Values.name }}-context
          readOnly: true
        - mountPath: /usr/local/tomcat/webapps/ROOT/index.jsp
          name: {{ .Values.name }}-index
          subPath: index.jsp
      - name: {{ .Values.worker.name }}
        image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.worker.securityContext.allowPrivilegeEscalation }}
          capabilities:
            drop: {{ .Values.worker.securityContext.capabilities.drop }}
          runAsUser: {{ .Values.worker.securityContext.runAsUser }}
          runAsNonRoot: {{ .Values.worker.securityContext.runAsNonRoot }}
          seccompProfile:
            type: {{ .Values.worker.securityContext.seccompProfile.type }}
        command: ["python3", "setup_frost.py"]
        envFrom:
        - configMapRef:
            name: {{ .Values.worker.name }}-envvars
        - secretRef:
            name: {{ if .Values.global.createSecrets }}{{ printf "%s-secret" .Values.worker.name }}{{ else }}{{ index .Values.global .Values.name "worker" "existingSecret" }}{{ end }}
        volumeMounts:
        - mountPath: /home/appuser/app/src/CreateNewFrostInstanceAction/tomcat/context_files
          name: {{ .Values.name }}-context
      volumes:
      - name: {{ .Values.name }}-context
        persistentVolumeClaim:
          claimName: tomcat-context-pvc
      - name: {{ .Values.name }}-index
        configMap:
          name: {{ .Values.name }}-index