apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /app/start.sh
          envFrom:
            - secretRef:
                name: {{ .Values.name }}-secret
          volumeMounts:
            - mountPath: /scripts/sms_sync
              name: {{ .Values.name }}-sms-sync
              readOnly: true
            - mountPath: /scripts/sftp_sync
              name: {{ .Values.name }}-sftp-sync
              readOnly: true
            - mountPath: /scripts/ext_api_sync
              name: {{ .Values.name }}-ext-api
              readOnly: true
            - mountPath: /tmp/crontab.txt
              name: {{ .Values.name }}-crontab
              subPath: crontab.txt
              readOnly: true
            - mountPath: /sftp-private-keys
              name: {{ .Values.name }}-sftp-private-keys
              readOnly: true
      volumes:
        - name: {{ .Values.name }}-sms-sync
          configMap:
            name: {{ .Values.name }}-sms-sync
            defaultMode: 0775
        - name: {{ .Values.name }}-sftp-sync
          configMap:
            name: {{ .Values.name }}-sftp-sync
            defaultMode: 0775
        - name: {{ .Values.name }}-ext-api
          configMap:
            name: {{ .Values.name }}-ext-api
            defaultMode: 0775
        - name: {{ .Values.name }}-crontab
          persistentVolumeClaim:
            claimName: crontab-pvc
        - name: {{ .Values.name }}-sftp-private-keys
          persistentVolumeClaim:
            claimName: sftp-private-keys-pvc