apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-statics-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10M
  storageClassName: {{ .Values.pvc.storageClassName }}
