{{ if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timeio-ingress
  annotations:
    {{- range $key, $value := .Values.global.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
  {{- range .Values.global.ingress.hosts }}
  - host: {{ default .host (include "timeio.publicHost" $) | quote }}
    http:
      paths:
      {{- range .paths}}
      - pathType: {{ .pathType | quote }}
        path: {{ .path }}
        backend:
          service:
            name: {{ .serviceName | quote }}
            port:
              number: {{ .servicePort | int }}
      {{- end }}
  {{- end }}
  {{ if .Values.global.ingress.enableTLS }}
  tls:
  {{- range .Values.global.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ default . (include "timeio.publicHost" $) | quote }}
    {{- end }}
    secretName: {{ .secretName | quote }}
    {{- end }}
  {{- end }}
{{- end }}
