replicaCount: 1

enabled: true

image:
  repository: "registry.hzdr.de/ufz-tsm/tsm-orchestration/dispatcher"
  tag: "prod-2025-10-17"
  pullPolicy: Always
name: worker-mqtt-ingest

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: True
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""