replicaCount: 1

image:
  repository: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher"
  tag: latest
  pullPolicy: Always
name: worker-mqtt-ingest

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: True
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""