apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  DB_URL: "postgresql://{{-  .Values.global.secrets.POSTGRES_USER -}}:{{-  .Values.global.secrets.POSTGRES_PASSWORD -}}@{{-  .Values.global.secrets.CREATEDB_POSTGRES_HOST -}}/{{-  .Values.global.secrets.CREATEDB_POSTGRES_DATABASE -}}"
  WEB_CONCURRENCY: "20"
  UVICORN_ARGS: ""