apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  DB_URL: "postgresql://{{- .Values.envvars.CREATEDB_POSTGRES_USER -}}:{{- .Values.envvars.CREATEDB_POSTGRES_PASSWORD -}}@{{- .Values.envvars.CREATEDB_POSTGRES_HOST -}}/{{- .Values.envvars.CREATEDB_POSTGRES_DATABASE -}}"
  WEB_CONCURRENCY: "20"
  UVICORN_ARGS: ""