name: timeio
description: A Helm chart wrapper of time.IO for the UFZ staging cluster
version: 0.3.2
apiVersion: v2

dependencies:
- name: timeio
  version: "0.3.2"
  repository: "oci://registry.hzdr.de/ufz-tsm/helm-deployment"
