replicaCount: 1

image:
  repository: "registry.hzdr.de/ufz-tsm/timeio-db-api/timeio-db-api"
  tag: "latest"
  pullPolicy: Always
name: timeio-db-api

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""