flyway.baselineOnMigrate=true
flyway.locations=filesystem:/flyway/sql
flyway.defaultSchema=${FLYWAY_PLACEHOLDERS_THING_MANAGEMENT_DB_USER}
flyway.schemas=${FLYWAY_PLACEHOLDERS_THING_MANAGEMENT_DB_USER}
flyway.jdbcProperties.sslrootcert=/etc/ssl/certs/ca-certificates.crt