apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  MQTT_AUTH_POSTGRES_USER: "{{ .Values.envvars.MQTT_AUTH_POSTGRES_USER }}"
  MQTT_AUTH_POSTGRES_PASS: "{{ .Values.envvars.MQTT_AUTH_POSTGRES_PASS }}"
  MQTT_AUTH_POSTGRES_HOST: "{{ .Values.envvars.MQTT_AUTH_POSTGRES_HOST }}"
  MQTT_AUTH_POSTGRES_PORT: "{{ .Values.envvars.MQTT_AUTH_POSTGRES_PORT }}"
  MQTT_AUTH_POSTGRES_DB: "{{ .Values.envvars.MQTT_AUTH_POSTGRES_DB }}"
  MQTT_AUTH_PG_TLSMODE: "{{ .Values.envvars.MQTT_AUTH_PG_TLSMODE }}"
  MQTT_BROKER_IMAGE_TAG: "{{ .Values.envvars.MQTT_BROKER_IMAGE_TAG }}"
  MOSQUITTO_PORT: "{{ .Values.envvars.MOSQUITTO_PORT }}"
  MOSQUITTO_PORT_SECURE: "{{ .Values.envvars.MOSQUITTO_PORT_SECURE }}"
  MQTT_USER: "{{ .Values.envvars.MQTT_USER }}"
  MQTT_PASSWORD: "{{ .Values.envvars.MQTT_PASSWORD }}"
  MQTT_QOS: "{{ .Values.envvars.MQTT_QOS }}"
  MQTT_CLEAN_SESSION: "{{ .Values.envvars.MQTT_CLEAN_SESSION }}"
  MQTT_BROKER_LOG_SIZE: "{{ .Values.envvars.MQTT_BROKER_LOG_SIZE }}"
  MQTT_BROKER_FILE_COUNT: "{{ .Values.envvars.MQTT_BROKER_FILE_COUNT }}"
  MQTT_CAT_LOG_SIZE: "{{ .Values.envvars.MQTT_CAT_LOG_SIZE }}"
  MQTT_CAT_FILE_COUNT: "{{ .Values.envvars.MQTT_CAT_FILE_COUNT }}"
  MQTT_INGEST_USER: "{{ .Values.envvars.MQTT_INGEST_USER }}"
  MQTT_INGEST_PASSWORD: "{{ .Values.envvars.MQTT_INGEST_PASSWORD }}"
  MOSQUITTO_CONFIG: "{{ .Values.envvars.MOSQUITTO_CONFIG }}"
  MOSQUITTO_TLS_CONFIG: "{{ .Values.envvars.MOSQUITTO_TLS_CONFIG }}"
  MOSQUITTO_TLS_CERT_PATH: "{{ .Values.envvars.MOSQUITTO_TLS_CERT_PATH }}"
  MOSQUITTO_TLS_KEY_PATH: "{{ .Values.envvars.MOSQUITTO_TLS_KEY_PATH }}"
  MOSQUITTO_TLS_CA_PATH: "{{ .Values.envvars.MOSQUITTO_TLS_CA_PATH }}"
  FRONTEND_MQTT_HOST: "{{ .Values.envvars.FRONTEND_MQTT_HOST }}"
  FRONTEND_MQTT_PORT: "{{ .Values.envvars.FRONTEND_MQTT_PORT }}"
  FRONTEND_MQTT_USER: "{{ .Values.envvars.FRONTEND_MQTT_USER }}"
  FRONTEND_MQTT_PASS: "{{ .Values.envvars.FRONTEND_MQTT_PASS }}"