apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-envvars
data:
  FLYWAY_URL: "jdbc:postgresql://{{-  .Values.global.envvars.CREATEDB_POSTGRES_HOST -}}/{{-  .Values.global.envvars.CREATEDB_POSTGRES_DATABASE -}}"