{{- $globalValues := .Values.global | default dict }}
{{- $globalChartValues := index $globalValues .Values.name | default dict }}
{{- $secretName := "" }}
{{- if .Values.global.createSecrets }}
  {{- $secretName = printf "%s-secret" .Values.name }}
{{- else }}
  {{- $secretName = default .Values.existingSecret (index $globalChartValues "existingSecret") }}
{{- end }}

{{- $configMapName := "" }}
{{- if .Values.global.createConfigMaps }}
  {{- $configMapName = printf "%s-envvars" .Values.name }}
{{- else }}
  {{- $configMapName = default .Values.existingConfigMap (index $globalChartValues "existingConfigMap") }}
{{- end }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        checksum/conf-cm: {{ include (print $.Template.BasePath "/conf-CM.yaml") . | sha256sum }}
        checksum/envvars: {{ include (print $.Template.BasePath "/envvars.yaml") . | sha256sum }}
        checksum/migrations-cm: {{ include (print $.Template.BasePath "/migrations-CM.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - repair
            - migrate
          volumeMounts:
            - mountPath: /flyway/sql
              name: {{ .Values.name }}-migrations
              readOnly: true
            - mountPath: /flyway/conf
              name: {{ .Values.name }}-conf
              readOnly: true
{{- if or $configMapName $secretName }}
          envFrom:
{{- if $configMapName }}
          - configMapRef:
              name: {{ $configMapName }}
{{- end }}
{{- if $secretName }}
          - secretRef:
              name: {{ $secretName }}
{{- end }}
{{- end }}
{{- with .Values.env }}
          env:
{{ toYaml . | nindent 12 }}
{{- end }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            capabilities:
              drop: {{ .Values.securityContext.capabilities.drop }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            seccompProfile:
              type: {{ .Values.securityContext.seccompProfile.type }}
      volumes:
        - name: {{ .Values.name }}-migrations
          configMap:
            name: {{ .Values.name }}-migrations
        - name: {{ .Values.name }}-conf
          configMap:
            name: {{ .Values.name }}-conf