{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  FLYWAY_USER: {{ .Values.global.secrets.CREATEDB_POSTGRES_USER | quote }}
  FLYWAY_PASSWORD: {{ .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD | quote }}
  FLYWAY_PLACEHOLDERS_CONFIGDB_USER: {{ .Values.global.secrets.CONFIGDB_POSTGRES_USER | quote }}
  FLYWAY_PLACEHOLDERS_CONFIGDB_PASSWORD: {{ .Values.global.secrets.CONFIGDB_POSTGRES_PASSWORD | quote }}
{{- end }}