{{- if .Values.existingSecret | empty }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  FLYWAY_URL: "jdbc:postgresql://{{-  .Values.global.envvars.CREATEDB_POSTGRES_HOST -}}/{{-  .Values.global.envvars.CREATEDB_POSTGRES_DATABASE -}}"
  FLYWAY_USER: {{ .Values.global.secrets.CREATEDB_POSTGRES_USER | quote }}
  FLYWAY_PASSWORD: {{ .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD | quote }}
  FLYWAY_PLACEHOLDERS_CONFIGDB_USER: {{ .Values.global.secrets.CONFIGDB_POSTGRES_USER | quote }}
  FLYWAY_PLACEHOLDERS_CONFIGDB_PASSWORD: {{ .Values.global.secrets.CONFIGDB_POSTGRES_PASSWORD | quote }}
  FLYWAY_PLACEHOLDERS_FRONTEND_DB_USER: {{ .Values.global.secrets.FRONTEND_POSTGRES_USER | quote }}
  FLYWAY_PLACEHOLDERS_FRONTEND_DB_PASSWORD: {{ .Values.global.secrets.FRONTEND_POSTGRES_PASS | quote }}
  FLYWAY_PLACEHOLDERS_MQTT_AUTH_DB_USER: {{ .Values.global.secrets.MQTT_AUTH_POSTGRES_USER | quote }}
  FLYWAY_PLACEHOLDERS_MQTT_AUTH_DB_PASSWORD: {{ .Values.global.secrets.MQTT_AUTH_POSTGRES_PASS | quote }}
  FLYWAY_PLACEHOLDERS_S3MAP_DB_USER: {{ .Values.global.secrets.S3MAP_POSTGRES_USER | quote }}
  FLYWAY_PLACEHOLDERS_S3MAP_DB_PASSWORD: {{ .Values.global.secrets.S3MAP_POSTGRES_PASS | quote }}
{{- end }}