replicaCount: 1

image:
  repository: "registry.hzdr.de/ufz-tsm/timeio-images/tsmdl"
  tag: "latest"
  pullPolicy: Always
name: tsmdl

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""
