{{- if .Values.enabled }}
{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "{{  .Values.global.secrets.GRAFANA_USER }}"
  GF_SECURITY_ADMIN_PASSWORD: "{{  .Values.global.secrets.GRAFANA_PASSWORD}}"
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{  .Values.global.secrets.OIDC_CLIENT_ID }}"
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{  .Values.global.secrets.OIDC_CLIENT_SECRET }}"
{{- end }}
{{- end }}