apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  LOG_LEVEL: "{{ .Values.envvars.LOG_LEVEL }}"
  TOPIC: "thing_creation"
  MQTT_BROKER: "mqtt-broker:1883"
  MQTT_USER: "{{ .Values.envvars.MQTT_USER }}"
  MQTT_PASSWORD: "{{ .Values.envvars.MQTT_PASSWORD }}"
  MQTT_CLIENT_ID: ""
  MQTT_CLEAN_SESSION: "{{ .Values.envvars.MQTT_CLEAN_SESSION }}"
  MQTT_QOS: "{{ .Values.envvars.MQTT_QOS }}"
  MINIO_SECURE: "{{ .Values.envvars.MINIO_SECURE }}"
  MINIO_URL: "{{ .Values.envvars.MINIO_HOST }}"
  MINIO_ACCESS_KEY: "{{ .Values.envvars.MINIO_ROOT_USER }}"
  MINIO_SECURE_KEY: "{{ .Values.envvars.MINIO_ROOT_PASSWORD }}"
  S3MAP_DB_URL: "postgresql://{{ .Values.envvars.S3MAP_POSTGRES_USER }}:{{ .Values.envvars.S3MAP_POSTGRES_PASS }}@{{ .Values.envvars.S3MAP_POSTGRES_HOST }}/{{ .Values.envvars.S3MAP_POSTGRES_DB }}"

