ARG BASE_IMAGE_REGISTRY=python
ARG BASE_IMAGE_TAG=3.13-slim

# see https://hub.docker.com/_/python/
# e.g. python:3.13-slim
FROM ${BASE_IMAGE_REGISTRY}:${BASE_IMAGE_TAG} AS base

FROM base AS build

COPY ../requirements.txt /tmp/requirements.txt
RUN python -m venv /opt/venv
RUN /opt/venv/bin/pip install --no-cache-dir -r /tmp/requirements.txt


FROM base AS dist

# copy the python binaries (with baked-in requirement packages) to the actual stage
COPY --from=build /opt/venv opt/venv
# first serach in /opt/venv/bin for binaries (e.g. python3)
ENV PATH="/opt/venv/bin:$PATH"

RUN mkdir /app

# create a non-root user and run all further commands as 'appuser'
ARG UID=1000
RUN adduser --uid ${UID} --disabled-password appuser

RUN chown -R appuser /app
WORKDIR /app
USER appuser

