replicaCount: 1

enabled: true

image:
  repository: "registry.hzdr.de/ufz-tsm/data-source-management/timeio-dsm-frontend-rootless"
  tag: 2026-06-26-122540
  pullPolicy: Always
name: dsm-frontend
port: 8080

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 101
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

env: []

existingSecret: ""
existingConfigMap: ""
