apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  LOG_LEVEL: "{{ .Values.envvars.LOG_LEVEL }}"
  TOPIC: "thing_creation"
  MQTT_BROKER: "mqtt-broker:1883"
  MQTT_USER: "{{ .Values.envvars.MQTT_USER }}"
  MQTT_PASSWORD: "{{ .Values.envvars.MQTT_PASSWORD }}"
  MQTT_CLIENT_ID: ""
  MQTT_CLEAN_SESSION: "{{ .Values.envvars.MQTT_CLEAN_SESSION }}"
  MQTT_QOS: "{{ .Values.envvars.MQTT_QOS }}"
  DATABASE_URL: "postgresql://{{ .Values.envvars.CREATEDB_POSTGRES_USER }}:{{ .Values.envvars.CREATEDB_POSTGRES_PASSWORD }}@{{ .Values.envvars.CREATEDB_POSTGRES_HOST }}/{{ .Values.envvars.CREATEDB_POSTGRES_DATABASE }}"

