apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  LOG_LEVEL: "{{  .Values.global.secrets.LOG_LEVEL }}"
  TOPIC: "thing_creation"
  MQTT_BROKER: "mqtt-broker:1883"
  MQTT_USER: "{{  .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{  .Values.global.secrets.MQTT_PASSWORD }}"
  MQTT_CLIENT_ID: ""
  MQTT_CLEAN_SESSION: "{{  .Values.global.secrets.MQTT_CLEAN_SESSION }}"
  MQTT_QOS: "{{  .Values.global.secrets.MQTT_QOS }}"
  DATABASE_URL: "postgresql://{{  .Values.global.secrets.POSTGRES_USER }}:{{  .Values.global.secrets.POSTGRES_PASSWORD }}@{{  .Values.global.secrets.CREATEDB_POSTGRES_HOST }}/{{  .Values.global.secrets.CREATEDB_POSTGRES_DATABASE }}"

