-- ===========================================
-- Migration: Create QAQC Setting Schema (Fixed)
-- Database: PostgreSQL
-- ===========================================

-- ===========================================
-- Create Table: qaqc_setting
-- ===========================================
CREATE TABLE "qaqc_setting"
(
    "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid"           UUID                     NOT NULL,
    "name"           VARCHAR(255)             NOT NULL,
    "context_window" VARCHAR(255)             NULL,
    "project_id"     BIGINT                   NOT NULL,
    "created_by"     BIGINT                   NOT NULL,
    "created_at"     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "thing_id"       BIGINT
);

ALTER TABLE "qaqc_setting"
    ADD CONSTRAINT "fk_qaqc_setting_project" FOREIGN KEY ("project_id") REFERENCES "project" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "qaqc_setting"
    ADD CONSTRAINT "fk_qaqc_setting_user" FOREIGN KEY ("created_by") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "qaqc_setting"
    ADD CONSTRAINT "fk_qaqc_setting_thing"
        FOREIGN KEY ("thing_id") REFERENCES "thing" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- ===========================================
-- Create Table: function
-- ===========================================
CREATE TABLE "function"
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        VARCHAR(255) UNIQUE      NOT NULL,
    "description" TEXT                     NULL,
    "created_by"  BIGINT                   NOT NULL,
    "created_at"  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE "function"
    ADD CONSTRAINT "fk_function_user" FOREIGN KEY ("created_by") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;

-- ===========================================
-- Create Table: function_parameter
-- ===========================================
CREATE TABLE "function_parameter"
(
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "function_id"   BIGINT       NOT NULL,
    "name"          VARCHAR(255) NOT NULL,
    "description"   TEXT         NULL,
    "optional"      BOOLEAN      NOT NULL DEFAULT FALSE,
    "type"          VARCHAR(50)  NOT NULL CHECK ("type" IN
                                                 ('int', 'float', 'string', 'list', 'bool', 'dict', 'datastream')),
    "default_value" VARCHAR(255) NULL,
    "position"      INT          NOT NULL
);

ALTER TABLE "function_parameter"
    ADD CONSTRAINT "fk_function_parameter_function" FOREIGN KEY ("function_id") REFERENCES "function" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

-- ===========================================
-- Create Table: qaqc_setting_function
-- ===========================================
CREATE TABLE "qaqc_setting_function"
(
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "qaqc_setting_id" BIGINT       NOT NULL,
    "function_id"     BIGINT       NOT NULL,
    "name"            VARCHAR(255) NOT NULL,
    "position"        INT          NOT NULL
);

ALTER TABLE "qaqc_setting_function"
    ADD CONSTRAINT "fk_qaqc_setting_function_setting" FOREIGN KEY ("qaqc_setting_id") REFERENCES "qaqc_setting" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "qaqc_setting_function"
    ADD CONSTRAINT "fk_qaqc_setting_function_function" FOREIGN KEY ("function_id") REFERENCES "function" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

-- ===========================================
-- Create Table: qaqc_setting_function_parameter
-- ===========================================
CREATE TABLE "qaqc_setting_function_parameter"
(
    "id"                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "qaqc_setting_function_id" BIGINT       NOT NULL,
    "function_parameter_id"    BIGINT       NOT NULL,
    "value"                    VARCHAR(255) NULL -- Allow NULL values
);

ALTER TABLE "qaqc_setting_function_parameter"
    ADD CONSTRAINT "fk_qaqc_function_value_sf" FOREIGN KEY ("qaqc_setting_function_id") REFERENCES "qaqc_setting_function" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "qaqc_setting_function_parameter"
    ADD CONSTRAINT "fk_qaqc_function_value_param" FOREIGN KEY ("function_parameter_id") REFERENCES "function_parameter" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

-- ===========================================
-- Ensure Parameters Are Initialized When a Function is Assigned
-- ===========================================

CREATE OR REPLACE FUNCTION insert_function_parameters()
    RETURNS TRIGGER AS
$$
BEGIN
    INSERT INTO qaqc_setting_function_parameter (qaqc_setting_function_id, function_parameter_id, value)
    SELECT NEW.id                           AS qaqc_setting_function_id,
           fp.id                            AS function_parameter_id,
           COALESCE(fp.default_value, NULL) AS value -- Use default_value if available, else NULL
    FROM function_parameter fp
    WHERE fp.function_id = NEW.function_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically insert parameters when a function is assigned
CREATE TRIGGER trg_insert_function_parameters
    AFTER INSERT
    ON qaqc_setting_function
    FOR EACH ROW
EXECUTE FUNCTION insert_function_parameters();

-- ===========================================
-- Documentation Comments
-- ===========================================
COMMENT ON TABLE "qaqc_setting_function_parameter" IS 'Stores parameter values for QA/QC settings';
COMMENT ON TABLE "qaqc_setting_function" IS 'Links functions to specific QA/QC settings';
COMMENT ON COLUMN "qaqc_setting_function_parameter"."value" IS 'Stores the assigned value for function parameters, allowing NULL for optional parameters';
