terminal:
  image: "docker:20.10.16-dind"
  before_script:
    - "apk add --no-cache curl"
    - "apk add --no-cache postgresql"
    - "apk add --no-cache bash"
  variables:
    POSTGRES_SSLMODE: disable
  tags:
    - "hifis"
