apiVersion: v2
name: timeio
description: A Helm chart for time.IO
version: 0.0.1
dependencies:
  - name: database
    version: 0.0.1
    repository: "file://./database"
  - name: mqtt-broker
    version: 0.0.1
    repository: "file://./mqtt-broker"
  - name: proxy
    version: 0.0.1
    repository: "file://./proxy"
  - name: visualization
    version: 0.0.1
    repository: "file://./visualization"
  - name: object-storage
    version: 0.0.1
    repository: "file://./object-storage"
  - name: frontend
    version: 0.0.1
    repository: "file://./frontend"
  - name: tsmdl
    version: 0.0.1
    repository: "file://./tsmdl"
  - name: frost
    version: 0.0.1
    repository: "file://./frost"
  - name: basic-demo-scheduler
    version: 0.0.1
    repository: "file://./basic-demo-scheduler"
  - name: cron-scheduler
    version: 0.0.1
    repository: "file://./cron-scheduler"
  - name: worker-crontab-setup
    version: 0.0.1
    repository: "file://./workers/worker-crontab-setup"
  - name: worker-db-setup
    version: 0.0.1
    repository: "file://./workers/worker-db-setup"
  - name: worker-file-ingest
    version: 0.0.1
    repository: "file://./workers/worker-file-ingest"
  - name: worker-frost-setup
    version: 0.0.1
    repository: "file://./workers/worker-frost-setup"
  - name: worker-grafana-dashboard
    version: 0.0.1
    repository: "file://./workers/worker-grafana-dashboard"
  - name: worker-grafana-user-orgs
    version: 0.0.1
    repository: "file://./workers/worker-grafana-user-orgs"
  - name: worker-mqtt-ingest
    version: 0.0.1
    repository: "file://./workers/worker-mqtt-ingest"
  - name: worker-mqtt-user-creation
    version: 0.0.1
    repository: "file://./workers/worker-mqtt-user-creation"
  - name: worker-object-storage-setup
    version: 0.0.1
    repository: "file://./workers/worker-object-storage-setup"
  - name: worker-run-qaqc
    version: 0.0.1
    repository: "file://./workers/worker-run-qaqc"