apiVersion: v2
name: timeio
description: A Helm chart for time.IO
version: 0.0.1
dependencies:
  - name: database
    version: 0.0.1
    repository: "file://./core/database"
  - name: mqtt-broker
    version: 0.0.1
    repository: "file://./core/mqtt-broker"
  - name: proxy
    version: 0.0.1
    repository: "file://./core/proxy"
  - name: visualization
    version: 0.0.1
    repository: "file://./core/visualization"
  - name: object-storage
    version: 0.0.1
    repository: "file://./core/object-storage"
  - name: frontend
    version: 0.0.1
    repository: "file://./core/frontend"
  - name: tsmdl
    version: 0.0.1
    repository: "file://./core/tsmdl"
  - name: frost
    version: 0.0.1
    repository: "file://./core/frost"
  - name: basic-demo-scheduler
    version: 0.0.1
    repository: "file://./core/basic-demo-scheduler"
  - name: cron-scheduler
    version: 0.0.1
    repository: "file://./core/cron-scheduler"
  - name: worker-crontab-setup
    version: 0.0.1
    repository: "file://./worker/worker-crontab-setup"
  - name: worker-db-setup
    version: 0.0.1
    repository: "file://./worker/worker-db-setup"
  - name: worker-file-ingest
    version: 0.0.1
    repository: "file://./worker/worker-file-ingest"
  - name: worker-frost-setup
    version: 0.0.1
    repository: "file://./worker/worker-frost-setup"
  - name: worker-grafana-dashboard
    version: 0.0.1
    repository: "file://./worker/worker-grafana-dashboard"
  - name: worker-grafana-user-orgs
    version: 0.0.1
    repository: "file://./worker/worker-grafana-user-orgs"
  - name: worker-mqtt-ingest
    version: 0.0.1
    repository: "file://./worker/worker-mqtt-ingest"
  - name: worker-mqtt-user-creation
    version: 0.0.1
    repository: "file://./worker/worker-mqtt-user-creation"
  - name: worker-object-storage-setup
    version: 0.0.1
    repository: "file://./worker/worker-object-storage-setup"
  - name: worker-run-qaqc
    version: 0.0.1
    repository: "file://./worker/worker-run-qaqc"