ingress:
  enabled: true
  host: localhost
  service:
    name: proxy
    port: 80

global:
  secrets:
    RESTART: "unless-stopped"
    LOG_LEVEL: "INFO"
    UID: "1000"
    GID: "1000"
    NGINX_IMAGE_TAG: "latest"
    PROXY_HOST: "localhost"
    PROXY_URL: "http://localhost"
    PROXY_TLS_CERT_PATH: "/tmp/tsm/fullchain.pem"
    PROXY_TLS_KEY_PATH: "/tmp/tsm/privkey.pem"
    PROXY_SITE_CONFIG: "tsm.dev.conf"
    PROXY_PLAIN_PORT: "80"
    PROXY_TSL_PORT: "443"
    PROXY_MINIO_PORT: "9000"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    PGDATA: "/var/lib/postgresql/data/pgdata"
    POSTGRES_PORT: "5432"
    POSTGRES_HEALTHCHECK_INTERVAL: "10s"
    POSTGRES_EXTRA_PARAMS: ""
    POSTGRES_TLS_CERT_PATH: "/tmp/c8cf2d92-73cd-11ec-b035-54e1ad7c5c19"
    POSTGRES_TSL_KEY_PATH: "/tmp/c8cf2d92-73cd-11ec-b035-54e1ad7c5c19"
    CREATEDB_POSTGRES_USER: "postgres"
    CREATEDB_POSTGRES_PASSWORD: "postgres"
    CREATEDB_POSTGRES_HOST: "database"
    CREATEDB_POSTGRES_PORT: "5432"
    CREATEDB_POSTGRES_DATABASE: "postgres"
    MQTT_AUTH_POSTGRES_USER: "mqtt_auth"
    MQTT_AUTH_POSTGRES_PASS: "secret"
    MQTT_AUTH_POSTGRES_HOST: "database"
    MQTT_AUTH_POSTGRES_PORT: "5432"
    MQTT_AUTH_POSTGRES_DB: "postgres"
    MQTT_AUTH_PG_TLSMODE: "disable"
    MQTT_BROKER_IMAGE_TAG: "latest"
    MOSQUITTO_PORT: "0.0.0.0:1883"
    MOSQUITTO_PORT_SECURE: "0.0.0.0:8883"
    MQTT_USER: "mqtt"
    MQTT_PASSWORD: "mqtt"
    MQTT_QOS: "1"
    MQTT_CLEAN_SESSION: "True"
    MQTT_BROKER_LOG_SIZE: "100k"
    MQTT_BROKER_FILE_COUNT: "10"
    MQTT_CAT_LOG_SIZE: "100k"
    MQTT_CAT_FILE_COUNT: "10"
    MQTT_INGEST_USER: "mqtt_ingest"
    MQTT_INGEST_PASSWORD: "mqtt_ingest"
    MOSQUITTO_CONFIG: "./mosquitto/mosquitto.conf"
    MOSQUITTO_TLS_CONFIG: "./mosquitto/"
    MOSQUITTO_TLS_CERT_PATH: "/tmp/1c8f2d92-73cd-11ec-b035-54e1ad7c5c19"
    MOSQUITTO_TLS_KEY_PATH: "/tmp/1c8f2d92-73cd-11ec-b035-54e1ad7c5c19"
    MOSQUITTO_TLS_CA_PATH: "/tmp/1c8f2d92-73cd-11ec-b035-54e1ad7c5c19"
    FRONTEND_POSTGRES_HOST: "database"
    FRONTEND_POSTGRES_PORT: "5432"
    FRONTEND_POSTGRES_DB: "postgres"
    FRONTEND_POSTGRES_USER: "frontenddb"
    FRONTEND_POSTGRES_PASS: "frontenddb"
    FRONTEND_MQTT_HOST: "mqtt"
    FRONTEND_MQTT_PORT: "1883"
    FRONTEND_MQTT_USER: "frontendbus"
    FRONTEND_MQTT_PASS: "frontendbus"
    S3MAP_POSTGRES_HOST: "database"
    S3MAP_POSTGRES_PORT: "5432"
    S3MAP_POSTGRES_USER: "s3map"
    S3MAP_POSTGRES_PASS: "secret"
    S3MAP_POSTGRES_DB: "postgres"
    SMS_DB_USER: "postgres"
    SMS_DB_PASSWORD: "postgres"
    SMS_DB_PORT: "5432"
    SMS_DB_DB: "postgres"
    SMS_DB_HOST: "database"
    SMS_URL: "https://web-intern-stage.app.ufz.de/sms/"
    SMS_ACCESS_TYPE: "db"
    CV_DB_USER: "postgres"
    CV_DB_PASSWORD: "postgres"
    CV_DB_PORT: "5432"
    CV_DB_DB: "postgres"
    CV_DB_HOST: "database"
    CV_URL: "https://sms-cv.helmholtz.cloud/sms/cv/"
    CV_ACCESS_TYPE: "db"