replicaCount: 1

image:
  repository: "registry.hzdr.de/ufz-tsm/tsm-orchestration/dispatcher"
  tag: 2025-01-28-160232
  pullPolicy: Always
name: worker-object-storage-setup

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""