from sqlmodel import SQLModel, Field, Relationship, Column, Index, func
from .ingest import Ingest, IngestRead, IngestCreate
from encryption import EncryptedType


class IngestMqttRead(IngestRead):
    parser_id: int
    topic: str
    uri: str
    username: str
    password: str
    password_hashed: str
    parser: dict


class IngestMqttCreate(IngestCreate):
    # Everything for mqtt ingest specific  will be generated by the api and should not be in the payload
    parser_id: int
    username: str | None = None


class IngestMqtt(SQLModel, table=True):
    __tablename__ = "ingest_mqtt"
    __table_args__ = (
        Index("ix_ingest_mqtt_username", func.lower(Column("username")), unique=True),
    )

    ingest_id: int = Field(
        foreign_key="ingest.id", primary_key=True, ondelete="CASCADE"
    )
    topic: str
    uri: str
    username: str
    password: str = Field(sa_column=Column("password", EncryptedType, nullable=False))
    password_hashed: str

    ingest: Ingest = Relationship(back_populates="mqtt_detail")

    @property
    def ingest_type(self):
        return self.ingest.ingest_type

    @property
    def permission_group(self):
        return self.ingest.permission_group

    @property
    def uuid(self):
        return self.ingest.uuid

    @property
    def name(self):
        return self.ingest.name

    @property
    def description(self):
        return self.ingest.description
