from sqlmodel import SQLModel, Field, Relationship, Column
from typing import Optional
from .ingest import Ingest, IngestRead, IngestCreate, IngestUpdate
from encryption import EncryptedType


class IngestSftpRead(IngestRead):
    parser_id: int
    username: str
    password: str
    bucket_name: str
    fileserver_uri: str
    parser: dict
    filename_pattern: str


class IngestSftpCreate(IngestCreate):
    # Most information for sftp ingest specific will be generated by the api and should not be in the payload
    parser_id: int
    filename_pattern: str


class IngestSftpUpdate(IngestUpdate):
    filename_pattern: Optional[str] = None


class IngestSftp(SQLModel, table=True):
    __tablename__ = "ingest_sftp"

    ingest_id: int = Field(
        foreign_key="ingest.id", primary_key=True, ondelete="CASCADE"
    )
    filename_pattern: str
    username: str
    password: str = Field(sa_column=Column("password", EncryptedType, nullable=False))
    bucket_name: str
    fileserver_uri: str | None

    ingest: Ingest = Relationship(back_populates="sftp_detail")

    @property
    def parser_information(self):
        return self.ingest.parser.mqtt_information

    @property
    def ingest_type(self):
        return self.ingest.ingest_type

    @property
    def permission_group(self):
        return self.ingest.permission_group

    @property
    def uuid(self):
        return self.ingest.uuid

    @property
    def name(self):
        return self.ingest.name

    @property
    def description(self):
        return self.ingest.description
