apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  MQTT_BROKER: "mqtt-broker:1883"
  MQTT_USER: "{{ .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{ .Values.global.secrets.MQTT_PASSWORD }}"
  MQTT_CLIENT_ID: ""
  MQTT_QOS: "{{ .Values.global.secrets.MQTT_QOS }}"