#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $CREATEDB_POSTGRES_USER WITH LOGIN PASSWORD '$CREATEDB_POSTGRES_PASSWORD';
    GRANT CONNECT ON DATABASE $CREATEDB_POSTGRES_DATABASE TO $CREATEDB_POSTGRES_USER;
    ALTER ROLE $CREATEDB_POSTGRES_USER CREATEDB;
    GRANT ALL PRIVILEGES ON DATABASE $CREATEDB_POSTGRES_DATABASE TO $CREATEDB_POSTGRES_USER;
EOSQL