{{- $secretName := "" }}
{{- if .Values.global.createSecrets }}
  {{- $secretName = printf "%s-secret" .Values.name }}
{{- else }}
  {{- $secretName = index .Values.global .Values.name "existingSecret" }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        checksum/certs: {{ include (print $.Template.BasePath "/certs.yaml") . | sha256sum }}
        checksum/envvars: {{ include (print $.Template.BasePath "/envvars.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          capabilities:
            drop: {{ .Values.securityContext.capabilities.drop }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          seccompProfile:
            type: {{ .Values.securityContext.seccompProfile.type }}
        command:
        - "minio"
        - "server"
        - "--console-address"
        - ":9001"
        - "--json"
        - "/vol0"
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-envvars
        - secretRef:
            name: {{ $secretName }}
        volumeMounts:
        - mountPath: /vol0
          name: {{ .Values.name }}-pv
        - mountPath: /certs
          name: {{ .Values.name }}-certs
      volumes:
      - name: {{ .Values.name }}-pv
        persistentVolumeClaim:
          claimName: {{ .Values.name }}-data-pvc
      - name: {{ .Values.name }}-certs
        secret:
          secretName: {{ .Values.name }}-certs
