{{- if .Values.enabled }}
{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  MINIO_ROOT_USER: "{{  .Values.global.secrets.MINIO_ROOT_USER }}"
  MINIO_ROOT_PASSWORD: "{{  .Values.global.secrets.MINIO_ROOT_PASSWORD }}"
  MINIO_NOTIFY_MQTT_USERNAME_LOCAL_BROKER: "{{  .Values.global.secrets.MQTT_USER }}"
  MINIO_NOTIFY_MQTT_PASSWORD_LOCAL_BROKER: "{{  .Values.global.secrets.MQTT_PASSWORD }}"
{{- end }}
{{- end }}