#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $S3MAP_POSTGRES_USER WITH LOGIN PASSWORD '$S3MAP_POSTGRES_PASS';
    GRANT $S3MAP_POSTGRES_USER TO postgres;
    CREATE SCHEMA IF NOT EXISTS $S3MAP_POSTGRES_USER AUTHORIZATION $S3MAP_POSTGRES_USER;
    SET search_path TO $S3MAP_POSTGRES_USER;
    GRANT CONNECT ON DATABASE postgres TO $S3MAP_POSTGRES_USER;
    ALTER ROLE $S3MAP_POSTGRES_USER SET search_path to $S3MAP_POSTGRES_USER;
    GRANT USAGE ON SCHEMA $S3MAP_POSTGRES_USER TO $S3MAP_POSTGRES_USER;
    GRANT ALL ON SCHEMA $S3MAP_POSTGRES_USER TO $S3MAP_POSTGRES_USER;

    CREATE TABLE "mapping" (
        "id"           bigserial    NOT NULL PRIMARY KEY,
        "bucket_name"  varchar(256) NOT NULL UNIQUE,
        "thing_uuid"   uuid         NOT NULL,
        "thing_name"   varchar(256) NOT NULL,
        "db_url"       varchar(256) NOT NULL,
    );

    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $S3MAP_POSTGRES_USER TO $S3MAP_POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA $S3MAP_POSTGRES_USER TO $S3MAP_POSTGRES_USER;
EOSQL
