{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  OIDC_CLIENT_ID: "{{ .Values.global.secrets.KEYCLOAK_LOCAL_OIDC_CLIENT }}"
{{- end }}