replicaCount: 1

image:
  repository: "iegomez/mosquitto-go-auth"
  digest: "sha256:acd65f8566f22126e3bf3b72fe5bee8a5002ca57695f211b1904013953560c3f"
  pullPolicy: Always
name: mosquitto
port: 1883

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

env: []

db_init:
  securityContext:
    allowPrivilegeEscalation: False
    capabilities:
      drop: [ "ALL" ]
    runAsUser: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  env: []

existingSecret: ""
existingConfigMap: ""
