replicaCount: 1

image:
  repository: "iegomez/mosquitto-go-auth"
  tag: latest
  pullPolicy: Always
name: mosquitto
port: 1883

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""