<template>
  <q-page class="q-pa-lg">
    <h5 class="q-mb-none">{{ title }}</h5>
    <div class="row">
      <div class="col">
        <q-btn label="back" class="q-mb-lg" icon="chevron_left" :to="backRoute" />
      </div>
    </div>

    <q-card class="q-mb-lg" flat>
      <q-card-section>
        <q-form @submit.prevent="$emit('save')" class="q-gutter-md">
          <!-- Name Field -->
          <q-input
            filled
            class="q-mb-md"
            v-model="formData.name"
            label="Name *"
            hint="Enter a descriptive name for this parser"
            :rules="[
              (val) => !!val || 'Name is required',
              (val) => val.length <= 80 || 'Maximum 80 characters',
            ]"
          />

          <permission-group-select
            v-model="permissionGroupModel"
            :disable="disablePermissionGroup"
            :rules="[(val) => !!val || 'Permission Group is required']"
          />

          <!-- Description -->
          <q-input
            filled
            v-model="formData.description"
            label="Description"
            type="textarea"
            rows="3"
            hint="Provide additional details about this parser"
          />

          <q-select
            filled
            v-model="formData.type"
            :options="soilcanTypeOptions"
            label="SoilCan parser type *"
            :rules="[(val) => !!val || 'Type is required']"
          />

          <div>
            <q-toggle v-model="formData.header" label="Enable header" color="primary" size="md" />
            <div class="text-caption text-grey-7 q-ml-sm">
              Enable this to use the file header instead of autogenerated names. Disable it for
              automatic DMP -> time.IO migrations.
            </div>
          </div>

          <!-- Action Buttons -->
          <div class="row q-mt-lg">
            <q-space />
            <div class="col-6">
              <q-btn
                unelevated
                color="green"
                type="submit"
                :loading="isLoading"
                label="Save"
                class="full-width"
              />
            </div>
            <q-space />
          </div>
        </q-form>
      </q-card-section>
    </q-card>
  </q-page>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { SoilcanParserUpdate } from 'src/services/parser_soilcan/types';
import PermissionGroupSelect from 'components/PermissionGroupSelect.vue';

type SoilcanParserFormData = SoilcanParserUpdate & {
  permission_group_id?: number | null;
};
const props = withDefaults(
  defineProps<{
    title: string;
    isLoading: boolean;
    backRoute: string;
    disablePermissionGroup?: boolean;
    permissionGroupId?: number | null;
  }>(),
  {
    disablePermissionGroup: false,
    permissionGroupId: null,
  },
);

defineEmits<{
  save: [];
}>();

const formData = defineModel<SoilcanParserFormData>({
  default: {
    name: '',
    permission_group_id: null,
    description: null,
    type: '',
    header: false,
  },
});

const permissionGroupModel = computed({
  get() {
    return formData.value.permission_group_id ?? props.permissionGroupId;
  },
  set(value: number | null) {
    if (!props.disablePermissionGroup) {
      formData.value.permission_group_id = value;
    }
  },
});

const soilcanTypeOptions = ['operating-parameters', 'sensor-data', 'weighing-data'];
</script>

<style scoped></style>
