"""initial-setup

Revision ID: 5640935e5253
Revises:
Create Date: 2026-02-23 13:36:08.885414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "5640935e5253"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mqtt_parser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "neutron_monitor_station",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permission_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("entitlement", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entitlement"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("given_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("family_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_sub"), "user", ["sub"], unique=True)
    op.create_table(
        "database",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "read_only_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "read_only_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("permission_group_id", name="permission_group_unique"),
    )
    op.create_table(
        "ingest_external_api_bosch",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("sync_interval_in_minutes", sa.Integer(), nullable=True),
        sa.Column("endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sensor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bosch_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bosch_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("period_in_minutes", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_bosch_name_permission_group",
        "ingest_external_api_bosch",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "ingest_external_api_dwd",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("station_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("sync_interval_in_minutes", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_dwd_name_permission_group",
        "ingest_external_api_dwd",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "ingest_external_api_neutron_monitor",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sync_interval_in_minutes", sa.Integer(), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("time_resolution_in_minutes", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["neutron_monitor_station.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_nm_name_permission_group",
        "ingest_external_api_neutron_monitor",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "ingest_external_api_the_things_network",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sync_interval_in_minutes", sa.Integer(), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("endpoint_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ttn_name_permission_group",
        "ingest_external_api_the_things_network",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "ingest_external_api_tsystems",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("group", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("station_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "tsystems_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "tsystems_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("sync_interval_in_minutes", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tsystems_name_permission_group",
        "ingest_external_api_tsystems",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "ingest_external_api_uba",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("station_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("sync_interval_in_minutes", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_uba_name_permission_group",
        "ingest_external_api_uba",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "ingest_mqtt",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mqtt_parser_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "password_hashed", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mqtt_parser_id"],
            ["mqtt_parser.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mqtt_name_permission_group",
        "ingest_mqtt",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "parser_csv",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("delimiter", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("headlines_to_exclude", sa.Integer(), nullable=True),
        sa.Column("footlines_to_exclude", sa.Integer(), nullable=True),
        sa.Column("pandas_read_csv", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.JSON(), nullable=True),
        sa.Column("header", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_parser_csv_name_permission_group",
        "parser_csv",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "permission_group_user_link",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("permission_group_id", "user_id"),
    )
    op.create_table(
        "quality_control_setting",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("context_window", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_qcs_name_permission_group",
        "quality_control_setting",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "ingest_sftp",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("parser_csv_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "filename_pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bucket_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fileserver_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parser_csv_id"],
            ["parser_csv.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_s3store_name_permission_group",
        "ingest_sftp",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "parser_csv_timestamp_column",
        sa.Column("csv_parser_id", sa.Integer(), nullable=False),
        sa.Column("column", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp_format", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["csv_parser_id"], ["parser_csv.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingest_external_sftp",
        sa.Column("permission_group_id", sa.Integer(), nullable=False),
        sa.Column("parser_csv_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "filename_pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bucket_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "bucket_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "bucket_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sync_interval_in_minutes", sa.Integer(), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "ssh_private_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("ssh_public_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parser_csv_id"],
            ["parser_csv.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_group_id"],
            ["permission_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ext_sftp_name_permission_group",
        "ingest_external_sftp",
        [sa.func.lower(sa.column("name")), sa.column("permission_group_id")],
        unique=True,
    )
    op.create_table(
        "quality_control_function",
        sa.Column("quality_control_setting_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quality_control_setting_id"],
            ["quality_control_setting.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quality_control_function_argument",
        sa.Column("quality_control_function_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quality_control_function_id"],
            ["quality_control_function.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quality_control_function_argument")
    op.drop_table("quality_control_function")
    op.drop_table("parser_csv_timestamp_column")
    op.drop_table("ingest_sftp")
    op.drop_table("quality_control_setting")
    op.drop_table("permission_group_user_link")
    op.drop_table("parser_csv")
    op.drop_table("ingest_mqtt")
    op.drop_table("ingest_external_sftp")
    op.drop_table("ingest_external_api_uba")
    op.drop_table("ingest_external_api_tsystems")
    op.drop_table("ingest_external_api_the_things_network")
    op.drop_table("ingest_external_api_neutron_monitor")
    op.drop_table("ingest_external_api_dwd")
    op.drop_table("ingest_external_api_bosch")
    op.drop_table("database")
    op.drop_index(op.f("ix_user_sub"), table_name="user")
    op.drop_table("user")
    op.drop_table("permission_group")
    op.drop_table("neutron_monitor_station")
    op.drop_table("mqtt_parser")
    # ### end Alembic commands ###
