"""add parser json

Revision ID: dc5b0d446dbc
Revises: ab9ee236aa8c
Create Date: 2026-05-21 09:08:59.547982

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "dc5b0d446dbc"
down_revision: Union[str, Sequence[str], None] = "ab9ee236aa8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parser_json",
        sa.Column("parser_id", sa.Integer(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parser_id"], ["parser_detailed.parser_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("parser_id"),
    )
    op.create_table(
        "parser_json_timestamp_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parser_json_id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("format", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parser_json_id"], ["parser_json.parser_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("parser_json_timestamp_key")
    op.drop_table("parser_json")
    # ### end Alembic commands ###
