replicaCount: 1

name: proxy

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: true
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

ref:
  institute:
    link: "https://www.ufz.de"
    name: "Helmholtz-Centre for Environmental Research"
  department:
    link: "https://www.ufz.de/index.php?en=45348"
    name: "Research Data Management"

proxy:
  name: proxy
  image:
    repository: "nginxinc/nginx-unprivileged"
    tag: latest
    pullPolicy: Always

frontend:
  name: frontend
  image:
    repository: "registry.hzdr.de/ufz-tsm/tsm-frontend/tsm-frontend"
    tag: 2025-09-11-165227
    pullPolicy: Always

existingSecret: ""
