ARG BASE_IMAGE_REGISTRY=python
ARG BASE_IMAGE_TAG=3.13-slim

FROM ${BASE_IMAGE_REGISTRY}:${BASE_IMAGE_TAG} AS base

# Tkinter runtime support
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-tk \
    tk \
    && rm -rf /var/lib/apt/lists/*

FROM base AS build

COPY ../requirements.txt /tmp/requirements.txt
RUN python -m venv /opt/venv
RUN /opt/venv/bin/pip install --no-cache-dir -r /tmp/requirements.txt

FROM base AS dist

COPY --from=build /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN mkdir /app

ARG UID=1000
RUN adduser --uid ${UID} --disabled-password appuser

RUN chown -R appuser /app
WORKDIR /app
USER appuser

ENTRYPOINT ["/app/start.sh"]