apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      containers:
        - name: {{ .Values.name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          envFrom:
          - secretRef:
              name: {{ .Values.name }}-secret
          volumeMounts:
            - name: postgis-sh
              mountPath: /docker-entrypoint-initdb.d/postgis.sh
              subPath: postgis.sh
            - name: mosquitto-go-auth-sh
              mountPath: /docker-entrypoint-initdb.d/mosquitto-go-auth.sh
              subPath: mosquitto-go-auth.sh
      volumes:
        - name: postgis-sh
          configMap:
            name: {{ .Values.name }}-postgis-sh
        - name: mosquitto-go-auth-sh
          configMap:
            name: {{ .Values.name }}-mosquitto-go-auth-sh