apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.global.secrets.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.global.secrets.POSTGRES_PASSWORD }}"
  PGDATA: "{{ .Values.global.secrets.PGDATA }}"
  POSTGRES_PORT: "{{ .Values.global.secrets.POSTGRES_PORT }}"
  POSTGRES_TLS_CERT_PATH: "{{ .Values.global.secrets.POSTGRES_TLS_CERT_PATH }}"
  POSTGRES_TSL_KEY_PATH: "{{ .Values.global.secrets.POSTGRES_TSL_KEY_PATH }}"
  CREATEDB_POSTGRES_USER: "{{ .Values.global.secrets.CREATEDB_POSTGRES_USER }}"
  CREATEDB_POSTGRES_PASSWORD: "{{ .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD }}"
  CREATEDB_POSTGRES_HOST: "{{ .Values.global.secrets.CREATEDB_POSTGRES_HOST }}"
  CREATEDB_POSTGRES_PORT: "{{ .Values.global.secrets.CREATEDB_POSTGRES_PORT }}"
  CREATEDB_POSTGRES_DATABASE: "{{ .Values.global.secrets.CREATEDB_POSTGRES_DATABASE }}"
  MQTT_AUTH_POSTGRES_USER: "{{ .Values.global.secrets.MQTT_AUTH_POSTGRES_USER }}"
  MQTT_AUTH_POSTGRES_PASS: "{{ .Values.global.secrets.MQTT_AUTH_POSTGRES_PASS }}"
  MQTT_AUTH_POSTGRES_HOST: "{{ .Values.global.secrets.MQTT_AUTH_POSTGRES_HOST }}"
  MQTT_AUTH_POSTGRES_PORT: "{{ .Values.global.secrets.MQTT_AUTH_POSTGRES_PORT }}"
  MQTT_AUTH_POSTGRES_DB: "{{ .Values.global.secrets.MQTT_AUTH_POSTGRES_DB }}"
  MQTT_AUTH_PG_TLSMODE: "{{ .Values.global.secrets.MQTT_AUTH_PG_TLSMODE }}"