{{- if .Values.existingSecret | empty }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  MQTT_AUTH_POSTGRES_USER: "{{  .Values.global.secrets.MQTT_AUTH_POSTGRES_USER }}"
  MQTT_AUTH_POSTGRES_PASS: "{{  .Values.global.secrets.MQTT_AUTH_POSTGRES_PASS }}"
  MQTT_USER: "{{  .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{  .Values.global.secrets.MQTT_PASSWORD }}"
  MQTT_INGEST_USER: "{{  .Values.global.secrets.MQTT_INGEST_USER }}"
  MQTT_INGEST_PASSWORD: "{{  .Values.global.secrets.MQTT_INGEST_PASSWORD }}"
  FRONTEND_MQTT_USER: "{{  .Values.global.secrets.FRONTEND_MQTT_USER }}"
  FRONTEND_MQTT_PASS: "{{  .Values.global.secrets.FRONTEND_MQTT_PASS }}"
{{- end }}