apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}-statefulset
  labels:
    app: {{ .Values.name }}
spec:
  serviceName: {{ .Values.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "/entrypoint/docker-entrypoint.sh", "/usr/sbin/mosquitto", "-c", "/var/lib/mosquitto/mosquitto.conf"]
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}-envvars
            - secretRef:
                name: {{ .Values.existingSecret | default (printf "%s-secret" .Values.name) }}
          volumeMounts:
            - mountPath: /mosquitto-data
              name: {{ .Values.name }}-pv
            - mountPath: /entrypoint
              name: {{ .Values.name }}-entrypoint
            - mountPath: /etc/mosquitto/config
              name: {{ .Values.name }}-config
            - mountPath: /etc/mosquitto/config/tls
              name: {{ .Values.name }}-tls-config
      volumes:
        - name: {{ .Values.name }}-pv
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-pvc
        - name: {{ .Values.name }}-entrypoint
          configMap:
            name: {{ .Values.name }}-entrypoint
        - name: {{ .Values.name }}-config
          configMap:
            name: {{ .Values.name }}-config
        - name: {{ .Values.name }}-tls-config
          configMap:
            name: {{ .Values.name }}-tls-config
