apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  LOG_LEVEL: "{{ .Values.envvars.LOG_LEVEL }}"
  TOPIC: "user_login"
  MQTT_BROKER: "mqtt-broker:1883"
  MQTT_USER: "{{ .Values.envvars.MQTT_USER }}"
  MQTT_PASSWORD: "{{ .Values.envvars.MQTT_PASSWORD }}"
  MQTT_CLIENT_ID: ""
  MQTT_CLEAN_SESSION: "{{ .Values.envvars.MQTT_CLEAN_SESSION }}"
  MQTT_QOS: "{{ .Values.envvars.MQTT_QOS }}"
  GRAFANA_URL: "{{ .Values.envvars.GRAFANA_URL }}"
  GRAFANA_USER: "{{ .Values.envvars.GRAFANA_USER }}"
  GRAFANA_PASSWORD: "{{ .Values.envvars.GRAFANA_PASSWORD }}"
  ALLOWED_VOS: "{{ .Values.envvars.ALLOWED_VOS }}"