{{- if .Values.enabled }}
{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.global.secrets.DSM_API_DATABASE_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.global.secrets.DSM_API_DATABASE_PASS }}"
  MQTT_USER: "{{ .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{ .Values.global.secrets.MQTT_PASSWORD }}"
  OIDC_AUDIENCE: "{{ .Values.global.secrets.KEYCLOAK_DSM_CLIENT_ID }}"
  FERNET_ENCRYPTION_SECRET: "{{ .Values.global.secrets.FERNET_ENCRYPTION_SECRET }}"
{{- end }}
{{- end }}