--
-- Create model Thing
--
CREATE TABLE "thing"
(
    "id"          bigserial    NOT NULL PRIMARY KEY,
    "name"        varchar(200) NOT NULL,
    "uuid"        uuid         NOT NULL UNIQUE,
    "description" text         NULL,
    "properties"  jsonb        NULL
);


--
-- Create model Journal
--
CREATE TABLE "journal"
(
    "id"        bigserial                NOT NULL PRIMARY KEY,
    "timestamp" timestamp with time zone NOT NULL,
    "level"     varchar(30)              NOT NULL,
    "message"   text                     NULL,
    "extra"     jsonb                    NULL,
    "thing_id"  bigint                   NOT NULL,
    "origin"    varchar(200)             NULL,

    CONSTRAINT "journal_thing_id_fk_thing_id" FOREIGN KEY ("thing_id") REFERENCES "thing" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX "journal_thing_id" ON "journal" ("thing_id");


--
-- Create model Datastream
--
CREATE TABLE "datastream"
(
    "id"          bigserial    NOT NULL PRIMARY KEY,
    "name"        varchar(200) NOT NULL,
    "description" text         NULL,
    "properties"  jsonb        NULL,
    "position"    varchar(200) NOT NULL,
    "thing_id"    bigint       NOT NULL,
    "mutable"     boolean      NOT NULL DEFAULT false,

    CONSTRAINT "datastream_thing_id_position_9f2cfe68_uniq" UNIQUE ("thing_id", "position"),
    CONSTRAINT "datastream_thing_id_f55522a4_fk_thing_id" FOREIGN KEY ("thing_id") REFERENCES "thing" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX "datastream_thing_id_f55522a4" ON "datastream" ("thing_id");


--
-- Create model Observation
--
CREATE TABLE "observation"
(
    "id"                    bigserial                NOT NULL PRIMARY KEY,
    "phenomenon_time_start" timestamp with time zone NULL,
    "phenomenon_time_end"   timestamp with time zone NULL,
    "result_time"           timestamp with time zone NOT NULL,
    "result_type"           smallint                 NOT NULL,
    "result_number"         double precision         NULL,
    "result_string"         varchar(200)             NULL,
    "result_json"           jsonb                    NULL,
    "result_boolean"        boolean                  NULL,
    "result_latitude"       double precision         NULL,
    "result_longitude"      double precision         NULL,
    "result_altitude"       double precision         NULL,
    "result_quality"        jsonb                    NULL,
    "valid_time_start"      timestamp with time zone NULL,
    "valid_time_end"        timestamp with time zone NULL,
    "parameters"            jsonb                    NULL,
    "datastream_id"         bigint                   NOT NULL,

    CONSTRAINT "observation_datastream_id_result_time_1d043396_uniq" UNIQUE ("datastream_id", "result_time"),
    CONSTRAINT "observation_datastream_id_77f5c4fb_fk_datastream_id" FOREIGN KEY ("datastream_id") REFERENCES "datastream" ("id") DEFERRABLE INITIALLY DEFERRED
);

-- not necessary, unique constraint generates automatically an index, see above
-- CREATE INDEX "observation_datastream_id_77f5c4fb" ON "observation" ("datastream_id");

CREATE INDEX idx_observation_result_time ON observation (result_time);


--
-- Create model Relation role
--
CREATE TABLE relation_role
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    name               varchar(200) NOT NULL,
    definition         text         NULL,
    inverse_name       varchar(200) NOT NULL,
    inverse_definition text         NULL,
    description        text         NULL,
    properties         jsonb        NULL,

    CONSTRAINT relation_role_pk PRIMARY KEY (id),
    CONSTRAINT relation_role_pk_2 UNIQUE (name),
    CONSTRAINT relation_role_pk_3 UNIQUE (inverse_name)
);


--
-- Create model Related datastreams
--
CREATE TABLE related_datastream
(
    id            bigint GENERATED ALWAYS AS IDENTITY,
    datastream_id bigint NOT NULL,
    role_id       bigint NOT NULL,
    target_id     bigint NOT NULL,

    CONSTRAINT related_datastream_pk PRIMARY KEY (id),
    CONSTRAINT related_datastream_pk_2 UNIQUE (datastream_id, role_id, target_id),
    CONSTRAINT related_datastream_datastream_id_fk FOREIGN KEY (datastream_id) REFERENCES datastream (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT related_datastream_datastream_id_fk_2 FOREIGN KEY (target_id) REFERENCES datastream (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT related_datastream_relation_role_id_fk FOREIGN KEY (role_id) REFERENCES relation_role (id) DEFERRABLE INITIALLY DEFERRED
);

COMMENT ON COLUMN related_datastream.datastream_id IS 'Domain, source or set of departure of the relation.';
COMMENT ON COLUMN related_datastream.role_id IS 'The type of the relation.';
COMMENT ON COLUMN related_datastream.target_id IS 'Codomain, target  or set of destination of the relation.';


CREATE TABLE mqtt_message

(
    "id"          bigserial                NOT NULL PRIMARY KEY,
    "timestamp"   timestamp with time zone NOT NULL,
    "message"     text                     NOT NULL,
    "thing_id"    bigint                   NOT NULL,

    CONSTRAINT "mqtt_message_thing_id_fk_thing_id" FOREIGN KEY ("thing_id") REFERENCES "thing" ("id") DEFERRABLE INITIALLY DEFERRED
);


-- Create table foi_datastream_mapping
-- Cached, time-versioned mapping of main/x/y/z datastream_ids per
-- dynamic-location configuration action (SMS). Kept in sync via
-- reconcile_foi_datastream_mapping().
-- Only relevant for projects with
-- dynamic things (currently: CRNS) - empty otherwise.
--
CREATE TABLE IF NOT EXISTS foi_datastream_mapping (
    main_datastream_id bigint NOT NULL,
    x_datastream_id     bigint NOT NULL,
    y_datastream_id     bigint NOT NULL,
    z_datastream_id     bigint,
    action_id           bigint NOT NULL,
    configuration_id    bigint,
    label               text,
    valid_from          timestamp with time zone NOT NULL,
    valid_to            timestamp with time zone,
    PRIMARY KEY (main_datastream_id, valid_from)
);

CREATE INDEX IF NOT EXISTS foi_dsm_x_datastream_id ON foi_datastream_mapping (x_datastream_id);
CREATE INDEX IF NOT EXISTS foi_dsm_y_datastream_id ON foi_datastream_mapping (y_datastream_id);



-- Catalog of all distinct coordinates (= "Features of Interest").
-- One line per unique position, the feature_id is a
-- deterministic hash of (x, y, z, action_id)
-- Same position always provides the same feature_id.

CREATE TABLE IF NOT EXISTS foi_catalog_dynamic (
    feature_id  bigint PRIMARY KEY,
    is_dynamic  boolean NOT NULL DEFAULT TRUE,
    action_id   bigint,
    label       text,
    begin_date  timestamp with time zone,
    coordinates double precision[]
);


--
-- Create table foi_observation_lookup
-- One row per observation that could be assigned a FOI. Observations
-- with invalid/missing coordinates (e.g. Null Island (0,0)) get no
-- entry - they simply have no FEATURE_ID in OBSERVATIONS.

CREATE TABLE IF NOT EXISTS foi_observation_lookup (
    o_id       bigint PRIMARY KEY,
    feature_id bigint REFERENCES foi_catalog_dynamic(feature_id)
);

CREATE INDEX IF NOT EXISTS foi_observation_lookup_feature_id_idx
    ON foi_observation_lookup (feature_id);


-- Correction log: filled when an SMS configuration is changed
-- retroactively (e.g. wrong channel corrected), populated by
-- reconcile_foi_datastream_mapping(). process_foi_recompute_queue()
-- checks live with each call what actually needs to be done.

CREATE TABLE IF NOT EXISTS foi_recompute_queue (
    id                 bigserial PRIMARY KEY,
    main_datastream_id bigint NOT NULL,
    from_time          timestamp with time zone NOT NULL,
    to_time            timestamp with time zone NOT NULL,
    created_at         timestamp with time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS foi_recompute_queue_main_ds_idx ON foi_recompute_queue (main_datastream_id);


-- Progress cursor for long-running recompute
-- orders (run_recompute_until_done()). One entry per
-- named order (job_name) -- allows demolition and
-- automatic continuation at the same place.
CREATE TABLE IF NOT EXISTS recompute_progress (
    job_name text PRIMARY KEY,
    last_completed_time timestamp with time zone NOT NULL
);

-- Calculates feature ID for newly arrived observations
-- and carries them into foi_catalog_dynamic and foi_observation_lookup.
CREATE OR REPLACE FUNCTION trg_populate_foi_observation() RETURNS trigger AS
$$
BEGIN
    EXECUTE format('SET LOCAL search_path TO %I, public', TG_TABLE_SCHEMA);

    SET LOCAL enable_hashjoin = off;
    SET LOCAL enable_mergejoin = off;
-- Filter on only newly arrived observations by new_table
    WITH candidates AS (
        SELECT DISTINCT
            m.main_datastream_id,
            m.action_id,
            m.label,
            m.valid_from AS begin_date,
            o.id AS o_id,
            ox.result_number AS x,
            oy.result_number AS y,
            oz.result_number AS z
        FROM new_table n
            JOIN foi_datastream_mapping m
                ON n.datastream_id IN (m.main_datastream_id, m.x_datastream_id,
                                        m.y_datastream_id, m.z_datastream_id)
            JOIN observation o
                ON o.datastream_id = m.main_datastream_id
                AND o.result_time = n.result_time
                AND o.result_time >= m.valid_from
                AND (m.valid_to IS NULL OR o.result_time < m.valid_to)
            JOIN observation ox
                ON ox.datastream_id = m.x_datastream_id
                AND ox.result_time = o.result_time
            JOIN observation oy
                ON oy.datastream_id = m.y_datastream_id
                AND oy.result_time = o.result_time
            LEFT JOIN observation oz
                ON oz.datastream_id = m.z_datastream_id
                AND oz.result_time = o.result_time
        WHERE NOT (ox.result_number = 0 AND oy.result_number = 0)
          AND (m.z_datastream_id IS NULL OR oz.result_number IS NOT NULL)
          AND NOT EXISTS (
              SELECT 1 FROM foi_observation_lookup fol WHERE fol.o_id = o.id
          )
    ),
    computed AS MATERIALIZED (
        SELECT
            o_id, action_id, label, begin_date,
            ARRAY[x, y, COALESCE(z, 0)] AS coordinates,
            hashtextextended(
                CONCAT(ARRAY[x, y, COALESCE(z, 0)]::text, action_id, TRUE), 0
            ) AS feature_id
        FROM candidates
    ),
    inserted_foi AS (
        INSERT INTO foi_catalog_dynamic (feature_id, is_dynamic, action_id, label, begin_date, coordinates)
        SELECT feature_id, TRUE, action_id, label, begin_date, coordinates
        FROM computed
        GROUP BY feature_id, action_id, label, begin_date, coordinates
        ON CONFLICT (feature_id) DO NOTHING
    )
    INSERT INTO foi_observation_lookup (o_id, feature_id)
    SELECT o_id, feature_id FROM computed
    ON CONFLICT (o_id) DO NOTHING;

    RETURN NULL;

EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'trg_populate_foi_observation fehlgeschlagen: %', SQLERRM;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;


-- Reads the SMS configuration tables (public.sms_*) and
-- updates foi_datastream_mapping accordingly.
-- Creates orders in the foi_recompute_queue.
CREATE OR REPLACE FUNCTION reconcile_foi_datastream_mapping(
    p_datasource_id text
) RETURNS void AS
$$
DECLARE
    r RECORD;
BEGIN
--for every dla-configuration (action-id) one row
    FOR r IN
        SELECT DISTINCT
            dla.id                 AS action_id,
            dma.configuration_id,
            c.label,
            dla.begin_date,
            dla.end_date,
            dsl_main.datastream_id AS main_datastream_id,
            dsl_x.datastream_id    AS x_datastream_id,
            dsl_y.datastream_id    AS y_datastream_id,
            dsl_z.datastream_id    AS z_datastream_id
        FROM public.sms_configuration_dynamic_location_begin_action dla
                 JOIN public.sms_device_mount_action dma
                      ON dma.configuration_id = dla.configuration_id
                 JOIN public.sms_configuration c
                      ON c.id = dma.configuration_id AND c.is_public
                 JOIN public.sms_device d
                      ON d.id = dma.device_id AND d.is_public
                 JOIN public.sms_datastream_link dsl_main
                      ON dsl_main.device_mount_action_id = dma.id
                      AND dsl_main.datasource_id = p_datasource_id
                      AND dsl_main.end_date IS NULL
                 JOIN public.sms_datastream_link dsl_x
                      ON dsl_x.device_mount_action_id = dma.id
                      AND dsl_x.device_property_id = dla.x_property_id
                      AND dsl_x.end_date IS NULL
                 JOIN public.sms_datastream_link dsl_y
                      ON dsl_y.device_mount_action_id = dma.id
                      AND dsl_y.device_property_id = dla.y_property_id
                      AND dsl_y.end_date IS NULL
                 LEFT JOIN public.sms_datastream_link dsl_z
                      ON dsl_z.device_mount_action_id = dma.id
                      AND dsl_z.device_property_id = dla.z_property_id
                      AND dsl_z.end_date IS NULL

    LOOP

-- Updating foi_datastream_mapping
        IF EXISTS (
            SELECT 1 FROM foi_datastream_mapping
            WHERE main_datastream_id = r.main_datastream_id
              AND valid_from = r.begin_date
        ) THEN

            UPDATE foi_datastream_mapping m
            SET x_datastream_id = r.x_datastream_id,
                y_datastream_id = r.y_datastream_id,
                z_datastream_id = r.z_datastream_id,
                valid_to        = r.end_date
            WHERE m.main_datastream_id = r.main_datastream_id
              AND m.valid_from = r.begin_date
              AND (m.x_datastream_id, m.y_datastream_id,
                   COALESCE(m.z_datastream_id, -1),
                   COALESCE(m.valid_to, 'infinity'::timestamp with time zone))
                      IS DISTINCT FROM
                  (r.x_datastream_id, r.y_datastream_id,
                   COALESCE(r.z_datastream_id, -1),
                   COALESCE(r.end_date, 'infinity'::timestamp with time zone));

-- Updating foi_recompute_queue
            IF FOUND THEN
                IF EXISTS (
                    SELECT 1 FROM foi_recompute_queue
                    WHERE main_datastream_id = r.main_datastream_id
                      AND from_time <= COALESCE(r.end_date, now())
                      AND to_time >= r.begin_date
                ) THEN
                    UPDATE foi_recompute_queue
                    SET from_time = r.begin_date,
                        to_time   = COALESCE(r.end_date, now())
                    WHERE main_datastream_id = r.main_datastream_id
                      AND from_time <= COALESCE(r.end_date, now())
                      AND to_time >= r.begin_date;
                ELSE
                    INSERT INTO foi_recompute_queue (main_datastream_id, from_time, to_time)
                    VALUES (r.main_datastream_id, r.begin_date, COALESCE(r.end_date, now()));
                END IF;
            END IF;

        ELSE

-- new datastream or new timetable: INSERT
            INSERT INTO foi_datastream_mapping
                (main_datastream_id, x_datastream_id, y_datastream_id, z_datastream_id,
                 action_id, configuration_id, label, valid_from, valid_to)
            VALUES
                (r.main_datastream_id, r.x_datastream_id, r.y_datastream_id, r.z_datastream_id,
                 r.action_id, r.configuration_id, r.label, r.begin_date, r.end_date)
            ON CONFLICT (main_datastream_id, valid_from) DO NOTHING;

            INSERT INTO foi_recompute_queue (main_datastream_id, from_time, to_time)
            VALUES (r.main_datastream_id, r.begin_date, COALESCE(r.end_date, now()));
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql;




-- Processes an explicit time window for all channels
-- that are currently in foi_recompute_queue.
-- Updates both foi_catalog_dynamic and
-- foi_observation_lookup afterwards.
CREATE OR REPLACE FUNCTION process_foi_recompute_queue(
    p_from timestamp with time zone,
    p_to   timestamp with time zone
) RETURNS TABLE(inserted_foi bigint, updated_lookup bigint) AS
$$
DECLARE
    v_inserted_foi   bigint;
    v_updated_lookup bigint;
BEGIN
    SET LOCAL enable_hashjoin = off;
    SET LOCAL enable_mergejoin = off;
-- Filter which datastreams are affected by the change
    WITH relevant_mains AS MATERIALIZED (
        SELECT m.main_datastream_id, m.x_datastream_id, m.y_datastream_id, m.z_datastream_id,
               m.valid_from, m.valid_to, m.action_id, m.label
        FROM foi_datastream_mapping m
        WHERE EXISTS (
            SELECT 1 FROM foi_recompute_queue q
            WHERE q.main_datastream_id = m.main_datastream_id
        )
    ),
    candidates AS (
        SELECT
            m.action_id, m.label, m.valid_from AS begin_date,
            ox.result_number AS x, oy.result_number AS y, oz.result_number AS z,
            o.id AS o_id
        FROM relevant_mains m
            JOIN observation o
                ON o.datastream_id = m.main_datastream_id
                AND o.result_time BETWEEN p_from AND p_to
                AND o.result_time >= m.valid_from
                AND (m.valid_to IS NULL OR o.result_time < m.valid_to)
            JOIN observation ox ON ox.datastream_id = m.x_datastream_id AND ox.result_time = o.result_time
            JOIN observation oy ON oy.datastream_id = m.y_datastream_id AND oy.result_time = o.result_time
            LEFT JOIN observation oz ON oz.datastream_id = m.z_datastream_id AND oz.result_time = o.result_time
        WHERE NOT (ox.result_number = 0 AND oy.result_number = 0)
          AND (m.z_datastream_id IS NULL OR oz.result_number IS NOT NULL)
          AND EXISTS (SELECT 1 FROM foi_observation_lookup fol WHERE fol.o_id = o.id)
    ),
    computed AS MATERIALIZED (
        SELECT
            o_id, action_id, label, begin_date,
            ARRAY[x, y, COALESCE(z, 0)] AS coordinates,
            hashtextextended(CONCAT(ARRAY[x, y, COALESCE(z, 0)]::text, action_id, TRUE), 0) AS feature_id
        FROM candidates
    ),
    new_foi AS (
        INSERT INTO foi_catalog_dynamic (feature_id, is_dynamic, action_id, label, begin_date, coordinates)
        SELECT feature_id, TRUE, action_id, label, begin_date, coordinates
        FROM computed
        GROUP BY feature_id, action_id, label, begin_date, coordinates
        ON CONFLICT (feature_id) DO NOTHING
        RETURNING feature_id
    ),
    updated AS (
        UPDATE foi_observation_lookup fol
        SET feature_id = c.feature_id
        FROM computed c
        WHERE fol.o_id = c.o_id
          AND fol.feature_id IS DISTINCT FROM c.feature_id
        RETURNING fol.o_id
    )
    SELECT
        (SELECT count(*) FROM new_foi),
        (SELECT count(*) FROM updated)
    INTO v_inserted_foi, v_updated_lookup;

    RETURN QUERY SELECT v_inserted_foi, v_updated_lookup;
END;
$$ LANGUAGE plpgsql;



-- Clean up orphaned FOI coordinates with no related
-- observation. Runs at the end of each complete recompute.
CREATE OR REPLACE FUNCTION cleanup_orphaned_foi() RETURNS void AS
$$
BEGIN
    DELETE FROM foi_catalog_dynamic f
    WHERE NOT EXISTS (
        SELECT 1 FROM foi_observation_lookup fol WHERE fol.feature_id = f.feature_id
    );
END;
$$ LANGUAGE plpgsql;



--Steps through a time window in stages (p_chunk_interval),
-- calls process_foi_recompute_queue() per stage, with real -
-- - COMMIT and a FIXED pause in between (p_pause_seconds).
-- Progress over recompute_progress.
-- Cancel at any time, the same call automatically sets away.
CREATE OR REPLACE PROCEDURE run_recompute_until_done(
    p_job_name text,
    p_schema text,
    p_chunk_interval interval DEFAULT '30 days',
    p_pause_seconds numeric DEFAULT 10
) AS
$$
DECLARE
    v_window_start timestamp with time zone;
    v_window_end   timestamp with time zone;
    v_global_from  timestamp with time zone;
    v_global_to    timestamp with time zone;
BEGIN
    EXECUTE format('SET LOCAL search_path TO %I, public', p_schema);

    SELECT min(from_time), max(to_time) INTO v_global_from, v_global_to
    FROM foi_recompute_queue;

    IF v_global_from IS NULL THEN
        RETURN;
    END IF;

    INSERT INTO recompute_progress (job_name, last_completed_time)
    VALUES (p_job_name, v_global_from)
    ON CONFLICT (job_name) DO NOTHING;

    SELECT last_completed_time INTO v_window_start
    FROM recompute_progress WHERE job_name = p_job_name;

    WHILE v_window_start < v_global_to LOOP
        EXECUTE format('SET LOCAL search_path TO %I, public', p_schema);

        v_window_end := LEAST(v_window_start + p_chunk_interval, v_global_to);

        PERFORM process_foi_recompute_queue(v_window_start, v_window_end);

        UPDATE recompute_progress
        SET last_completed_time = v_window_end
        WHERE job_name = p_job_name;

        COMMIT;

        PERFORM pg_sleep(p_pause_seconds);

        v_window_start := v_window_end;
    END LOOP;

    BEGIN
        PERFORM cleanup_orphaned_foi();
    EXCEPTION WHEN OTHERS THEN
        RAISE WARNING 'cleanup_orphaned_foi() fehlgeschlagen: %', SQLERRM;
    END;
END;
$$ LANGUAGE plpgsql;


--Trigger on observation to keep foi_catalog_dynamic
-- and foi_observation_lookup up to date
CREATE TRIGGER observation_foi_sync_insert
AFTER INSERT ON observation
REFERENCING NEW TABLE AS new_table
FOR EACH STATEMENT
EXECUTE FUNCTION trg_populate_foi_observation();

CREATE TRIGGER observation_foi_sync_update
AFTER UPDATE ON observation
REFERENCING NEW TABLE AS new_table
FOR EACH STATEMENT
EXECUTE FUNCTION trg_populate_foi_observation();