replicaCount: 1

image:
  repository: "registry.hzdr.de/ufz-tsm/timeio-configdb-updater/configdb-updater"
  tag: "latest"
  pullPolicy: Always
name: worker-configdb-updater

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""