replicaCount: 1

enabled: true

image:
  repository: "registry.hzdr.de/ufz-tsm/tsm-orchestration/configdb-updater"
  tag: "prod-2026-04-17"
  pullPolicy: Always
name: worker-configdb-updater

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

env: []

mqtt_init:
  securityContext:
    allowPrivilegeEscalation: False
    capabilities:
      drop: [ "ALL" ]
    runAsUser: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  env: []

existingSecret: ""
existingConfigMap: ""
