replicaCount: 1

image:
  repository: "registry.hzdr.de/ufz-tsm/timeio-images/cron-scheduler"
  tag: "latest"
  pullPolicy: Always
name: cron-scheduler
securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

worker:
  image:
    repository: "registry.hzdr.de/ufz-tsm/tsm-dispatcher/dispatcher"
    tag: latest
    pullPolicy: Always
  name: worker-crontab-setup
  securityContext:
    allowPrivilegeEscalation: False
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault