replicaCount: 1

enabled: true

image:
  repository: "registry.hzdr.de/ufz-tsm/tsm-orchestration/cron-scheduler"
  tag: "prod-2025-12-17"
  pullPolicy: Always
name: cron-scheduler
securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

worker:
  image:
    repository: "registry.hzdr.de/ufz-tsm/tsm-orchestration/dispatcher"
    tag: "prod-2025-12-17"
    pullPolicy: Always
  name: worker-crontab-setup
  securityContext:
    allowPrivilegeEscalation: False
    capabilities:
      drop: ["ALL"]
    runAsUser: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault