replicaCount: 1

image:
  repository: "registry.hzdr.de/ufz-tsm/timeio-images/supercronic"
  tag: "latest"
  pullPolicy: Always
name: cron-scheduler
securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

worker:
  image:
    repository: "registry.hzdr.de/ufz-tsm/tsm-orchestration/dispatcher"
    tag: 2025-03-05-100929
    pullPolicy: Always
  name: worker-crontab-setup
  securityContext:
    allowPrivilegeEscalation: False
    capabilities:
      drop: ["ALL"]
    runAsUser: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault