CREATE TABLE "config_db"."database"(
	"id"			BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"schema"		VARCHAR(200) NOT NULL,
	"user"			VARCHAR(200) NOT NULL,
	"password"		VARCHAR(200) NOT NULL,
	"ro_user"		VARCHAR(200) NOT NULL,
	"ro_password"	VARCHAR(200) NOT NULL
);

CREATE TABLE "config_db"."project"(
	"id"			BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name"			VARCHAR(200) NOT NULL,
	"uuid"			UUID NOT NULL,
	"database_id"	BIGINT UNIQUE NOT NULL
);

ALTER TABLE "config_db"."project" ADD CONSTRAINT "fk_project_db" FOREIGN KEY ("database_id") REFERENCES "config_db"."database" ("id") DEFERRABLE INITIALLY DEFERRED;


CREATE TABLE "config_db"."qaqc"(
	"id"		        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name"		        VARCHAR(200) NOT NULL,
	"project_id" 	    BIGINT NOT NULL,
	"context_window"	VARCHAR(200) NOT NULL
);

alter TABLE "config_db"."qaqc" add constraint "fk_qaqc_project" foreign key ("project_id") references "config_db"."project" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "config_db"."qaqc_test"(
    "id"		    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "target"	    VARCHAR(200) NOT NULL,
    "qaqc_id"       BIGINT NOT NULL,
    "function"      VARCHAR(200) NOT NULL,
    "args"          jsonb NULL
);

alter TABLE "config_db"."qaqc_test" add constraint "fk_qaqc_test_qaqc" foreign key ("qaqc_id") references "config_db"."qaqc" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "config_db"."ext_api_type"(
	"id"		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" 	VARCHAR(200) NOT NULL
);

CREATE TABLE "config_db"."ext_api"(
	"id"		        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"api_type_id"	    BIGINT NOT NULL,
	"sync_interval" 	INT NOT NULL,
	"sync_enabled"	    boolean NOT NULL,
	"settings"	        jsonb NULL
);

ALTER TABLE "config_db"."ext_api" ADD CONSTRAINT "fk_ext_api_ext_api_type" FOREIGN KEY ("api_type_id") REFERENCES "config_db"."ext_api_type" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "config_db"."ext_sftp"(
	"id"			BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uri"           VARCHAR(200) NOT NULL,
	"path"		    VARCHAR(200) NOT NULL,
	"user"		    VARCHAR(200) NOT NULL,
	"password"	    VARCHAR(200) NOT NULL,
	"ssh_priv_key"	VARCHAR(200) NOT NULL,   -- TODO: find correct lenght
	"ssh_pub_key"	VARCHAR(200) NOT NULL,   -- TODO: find correct lenght
	"sync_interval"	INT NOT NULL,
	"sync_enabled"	boolean NOT NULL
);

CREATE TABLE "config_db"."mqtt_device_type"(
	"id"	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name"	VARCHAR(200) NOT NULL
);

CREATE TABLE "config_db"."mqtt"(
	"id"			        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user"			        VARCHAR(200) NOT NULL,
	"password"		        VARCHAR(200) NOT NULL,
	"password_hashed"	    VARCHAR(200) NOT NULL,      -- TODO: find correct length
	"topic"			        VARCHAR(200) NOT NULL,
	"mqtt_device_type_id"	BIGINT NOT NULL
	
);

ALTER TABLE "config_db"."mqtt" ADD CONSTRAINT "fk_mqtt_mqtt_device_type" FOREIGN KEY ("mqtt_device_type_id") REFERENCES "config_db"."mqtt_device_type" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "config_db"."file_parser_type"(
	"id"	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name"	VARCHAR(200) NOT NULL
);

CREATE TABLE "config_db"."file_parser"(
	"id"					BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"file_parser_type_id"   BIGINT NOT NULL,
	"name"	                VARCHAR(200) NOT NULL,
	"params"	            jsonb NULL
);

ALTER TABLE "config_db"."file_parser" ADD CONSTRAINT "fk_file_parser_file_parser_type" FOREIGN KEY ("file_parser_type_id") REFERENCES "config_db"."file_parser_type" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "config_db"."s3_store"(
	"id"		        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user"			    VARCHAR(200) NOT NULL,
	"password"		    VARCHAR(200) NOT NULL,
	"bucket"			VARCHAR(200) NOT NULL,
	"filename_pattern"	VARCHAR(200) NULL,
	"file_parser_id"	BIGINT UNIQUE NOT NULL
);

ALTER TABLE "config_db"."s3_store" ADD CONSTRAINT "fk_s3_store_file_parser" FOREIGN KEY ("file_parser_id") REFERENCES "config_db"."file_parser" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "config_db"."ingest_type"(
	"id"	BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name"	VARCHAR(200) NOT NULL
);

CREATE TABLE "config_db"."thing"(
	"id"		        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"uuid"		        UUID NOT NULL,
	"name"		        VARCHAR(200) NOT NULL,
	"project_id" 	    BIGINT NOT NULL,
	"ingest_type_id"	BIGINT NOT NULL,
	"s3_store_id"	    BIGINT UNIQUE NOT NULL,
	"mqtt_id"	        BIGINT UNIQUE NOT NULL,
	"ext_sftp_id"	    BIGINT UNIQUE NULL,
	"ext_api_id"	    BIGINT UNIQUE NULL
	
);

ALTER TABLE "config_db"."thing" ADD CONSTRAINT "fk_thing_project" FOREIGN KEY ("project_id") REFERENCES "config_db"."project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "config_db"."thing" ADD CONSTRAINT "fk_thing_ingest_type" FOREIGN KEY ("ingest_type_id") REFERENCES "config_db"."ingest_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "config_db"."thing" ADD CONSTRAINT "fk_thing_s3_store" FOREIGN KEY ("s3_store_id") REFERENCES "config_db"."s3_store" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "config_db"."thing" ADD CONSTRAINT "fk_thing_mqtt" FOREIGN KEY ("mqtt_id") REFERENCES "config_db"."mqtt" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "config_db"."thing" ADD CONSTRAINT "fk_thing_ext_sftp" FOREIGN KEY ("ext_sftp_id") REFERENCES "config_db"."ext_sftp" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "config_db"."thing" ADD CONSTRAINT "fk_thing_ext_api" FOREIGN KEY ("ext_api_id") REFERENCES "config_db"."ext_api" ("id") DEFERRABLE INITIALLY DEFERRED;
