SET search_path TO thing_management;

CREATE TABLE "database"
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "schema"      VARCHAR(200)  NOT NULL,
    "user"        VARCHAR(200)  NOT NULL,
    "password"    VARCHAR(200)  NOT NULL,
    "ro_user"     VARCHAR(200)  NOT NULL,
    "ro_password" VARCHAR(200)  NOT NULL
);

CREATE TABLE "mqtt"
(
    "id"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user"      VARCHAR(200) NOT NULL,
    "password"  VARCHAR(200) NOT NULL
);

CREATE TABLE "user"
(
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"          VARCHAR(200) NOT NULL,
    "password"      VARCHAR(200) NOT NULL,
    "first_name"    VARCHAR(200) NOT NULL,
    "last_name"     VARCHAR(200) NOT NULL,
    "email"         VARCHAR(254) NOT NULL

);

CREATE TABLE "project"
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"          VARCHAR(200)  NOT NULL,
    "uuid"          UUID          NOT NULL,
    "database_id"   BIGINT UNIQUE NOT NULL,
    "mqtt_id"       BIGINT UNIQUE NOT NULL
);

ALTER TABLE "project"
    ADD CONSTRAINT "fk_project_db" FOREIGN KEY ("database_id") REFERENCES "database" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "project"
    ADD CONSTRAINT "fk_project_mqtt" FOREIGN KEY ("mqtt_id") REFERENCES "mqtt" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "lnk_project_user"
(
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id"    BIGINT NOT NULL,
    "user_id"       BIGINT NOT NULL,
    UNIQUE ("project_id", "user_id")
);

ALTER TABLE "lnk_project_user"
    ADD CONSTRAINT "fk_lnk_project_user_project" FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lnk_project_user"
    ADD CONSTRAINT "fk_lnk_project_user_user" FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED;



CREATE TABLE "file_parser_type"
(
    "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE "file_parser"
(
    "id"                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "file_parser_type_id"   BIGINT       NOT NULL,
    "project_id"            BIGINT       NOT NULL,
    "name"                  VARCHAR(200) NOT NULL,
    "settings"              jsonb        NULL
);

ALTER TABLE "file_parser"
    ADD CONSTRAINT "fk_file_parser_file_parser_type" FOREIGN KEY ("file_parser_type_id") REFERENCES "file_parser_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "file_parser"
    ADD CONSTRAINT "fk_file_parser_project" FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "ingest_type"
(
    "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE "thing"
(
    "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid"              UUID            NOT NULL,
    "name"              VARCHAR(200)    NOT NULL,
    "description"       VARCHAR(1000)   NULL,
    "project_id"        BIGINT          NOT NULL,
    "ingest_type_id"    BIGINT          NOT NULL
);

ALTER TABLE "thing"
    ADD CONSTRAINT "fk_thing_project" FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "thing"
    ADD CONSTRAINT "fk_thing_ingest_type" FOREIGN KEY ("ingest_type_id") REFERENCES "ingest_type" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "rawdatastorage"
(
    "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user"              VARCHAR(200)  NOT NULL,
    "password"          VARCHAR(200)  NOT NULL,
    "bucket_name"       VARCHAR(200)  NOT NULL,
    "fileserver_uri"    VARCHAR(200)  NOT NULL,
    "thing_id"          BIGINT UNIQUE NOT NULL
);

ALTER TABLE "rawdatastorage"
    ADD CONSTRAINT "fk_rawdatastorage_thing" FOREIGN KEY ("thing_id") REFERENCES "thing" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "mqtt_device_type"
(
    "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE mqtt_ingest
(
    "id"                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "thing_id"            BIGINT UNIQUE NOT NULL,
    "user"                VARCHAR(200)  NOT NULL,
    "password"            VARCHAR(200)  NOT NULL,
    "password_hashed"     TEXT          NOT NULL,
    "topic"               VARCHAR(200)  NULL,
    "uri"                 VARCHAR(1000) NOT NULL,
    "mqtt_device_type_id" BIGINT        NULL
);

ALTER TABLE mqtt_ingest
    ADD CONSTRAINT "fk_mqtt_ingest_thing" FOREIGN KEY ("thing_id") REFERENCES "thing" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE mqtt_ingest
    ADD CONSTRAINT "fk_mqtt_ingest_mqtt_device_type" FOREIGN KEY ("mqtt_device_type_id") REFERENCES "mqtt_device_type" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "ext_api_type"
(
    "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE "ext_api"
(
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "thing_id"      BIGINT UNIQUE  NOT NULL,
    "api_type_id"   BIGINT  NOT NULL,
    "sync_interval" INT     NOT NULL,
    "sync_enabled"  boolean NOT NULL,
    "settings"      jsonb   NULL
);

ALTER TABLE "ext_api"
    ADD CONSTRAINT "fk_ext_api_ext_api_type" FOREIGN KEY ("api_type_id") REFERENCES "ext_api_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ext_api"
    ADD CONSTRAINT "fk_ext_api_thing" FOREIGN KEY ("thing_id") REFERENCES "thing" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "ext_sftp"
(
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "thing_id"      BIGINT UNIQUE NOT NULL,
    "uri"           VARCHAR(200) NOT NULL,
    "path"          VARCHAR(200) NOT NULL,
    "user"          VARCHAR(200) NOT NULL,
    "password"      VARCHAR(200) NULL,
    "ssh_priv_key"  TEXT         NOT NULL,
    "ssh_pub_key"   TEXT         NOT NULL,
    "sync_interval" INT          NOT NULL,
    "sync_enabled"  boolean      NOT NULL
);

ALTER TABLE "ext_sftp"
    ADD CONSTRAINT "fk_ext_sftp_thing" FOREIGN KEY ("thing_id") REFERENCES "thing" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE "nm_stations"
(
    "id"    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"  VARCHAR(200) NOT NULL
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA thing_management TO ${thingmanagement_user};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA thing_management TO ${thingmanagement_user};

