apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.envvars.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.envvars.POSTGRES_PASSWORD }}"
  PGDATA: "{{ .Values.envvars.PGDATA }}"
  POSTGRES_PORT: "{{ .Values.envvars.POSTGRES_PORT }}"
  POSTGRES_TLS_CERT_PATH: "{{ .Values.envvars.POSTGRES_TLS_CERT_PATH }}"
  POSTGRES_TSL_KEY_PATH: "{{ .Values.envvars.POSTGRES_TSL_KEY_PATH }}"
  CREATEDB_POSTGRES_USER: "{{ .Values.envvars.CREATEDB_POSTGRES_USER }}"
  CREATEDB_POSTGRES_PASSWORD: "{{ .Values.envvars.CREATEDB_POSTGRES_PASSWORD }}"
  CREATEDB_POSTGRES_HOST: "{{ .Values.envvars.CREATEDB_POSTGRES_HOST }}"
  CREATEDB_POSTGRES_PORT: "{{ .Values.envvars.CREATEDB_POSTGRES_PORT }}"
  CREATEDB_POSTGRES_DATABASE: "{{ .Values.envvars.CREATEDB_POSTGRES_DATABASE }}"
  MQTT_AUTH_POSTGRES_USER: "{{ .Values.envvars.MQTT_AUTH_POSTGRES_USER }}"
  MQTT_AUTH_POSTGRES_PASS: "{{ .Values.envvars.MQTT_AUTH_POSTGRES_PASS }}"
  MQTT_AUTH_POSTGRES_HOST: "{{ .Values.envvars.MQTT_AUTH_POSTGRES_HOST }}"
  MQTT_AUTH_POSTGRES_PORT: "{{ .Values.envvars.MQTT_AUTH_POSTGRES_PORT }}"
  MQTT_AUTH_POSTGRES_DB: "{{ .Values.envvars.MQTT_AUTH_POSTGRES_DB }}"
  MQTT_AUTH_PG_TLSMODE: "{{ .Values.envvars.MQTT_AUTH_PG_TLSMODE }}"
  FRONTEND_POSTGRES_HOST: "{{ .Values.envvars.FRONTEND_POSTGRES_HOST }}"
  FRONTEND_POSTGRES_PORT: "{{ .Values.envvars.FRONTEND_POSTGRES_PORT }}"
  FRONTEND_POSTGRES_DB: "{{ .Values.envvars.FRONTEND_POSTGRES_DB }}"
  FRONTEND_POSTGRES_USER: "{{ .Values.envvars.FRONTEND_POSTGRES_USER }}"
  FRONTEND_POSTGRES_PASS: "{{ .Values.envvars.FRONTEND_POSTGRES_PASS }}"
  S3MAP_POSTGRES_HOST: "{{ .Values.envvars.S3MAP_POSTGRES_HOST }}"
  S3MAP_POSTGRES_PORT: "{{ .Values.envvars.S3MAP_POSTGRES_PORT }}"
  S3MAP_POSTGRES_USER: "{{ .Values.envvars.S3MAP_POSTGRES_USER }}"
  S3MAP_POSTGRES_PASS: "{{ .Values.envvars.S3MAP_POSTGRES_PASS }}"
  S3MAP_POSTGRES_DB: "{{ .Values.envvars.S3MAP_POSTGRES_DB }}"
  SMS_DB_USER: "{{ .Values.envvars.SMS_DB_USER }}"
  SMS_DB_PASSWORD: "{{ .Values.envvars.SMS_DB_PASSWORD }}"
  SMS_DB_PORT: "{{ .Values.envvars.SMS_DB_PORT }}"
  SMS_DB_DB: "{{ .Values.envvars.SMS_DB_DB }}"
  SMS_DB_HOST: "{{ .Values.envvars.SMS_DB_HOST }}"
  SMS_URL: "{{ .Values.envvars.SMS_URL }}"
  SMS_ACCESS_TYPE: "{{ .Values.envvars.SMS_ACCESS_TYPE }}"
  CV_DB_USER: "{{ .Values.envvars.CV_DB_USER }}"
  CV_DB_PASSWORD: "{{ .Values.envvars.CV_DB_PASSWORD }}"
  CV_DB_PORT: "{{ .Values.envvars.CV_DB_PORT }}"
  CV_DB_DB: "{{ .Values.envvars.CV_DB_DB }}"
  CV_DB_HOST: "{{ .Values.envvars.CV_DB_HOST }}"
  CV_URL: "{{ .Values.envvars.CV_URL }}"
  CV_ACCESS_TYPE: "{{ .Values.envvars.CV_ACCESS_TYPE }}"