apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  POSTGRES_USER: "{{  .Values.global.secrets.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{  .Values.global.secrets.POSTGRES_PASSWORD }}"
  PGDATA: "{{  .Values.global.secrets.PGDATA }}"
  POSTGRES_PORT: "{{  .Values.global.secrets.POSTGRES_PORT }}"
  POSTGRES_TLS_CERT_PATH: "{{  .Values.global.secrets.POSTGRES_TLS_CERT_PATH }}"
  POSTGRES_TSL_KEY_PATH: "{{  .Values.global.secrets.POSTGRES_TSL_KEY_PATH }}"
  CREATEDB_POSTGRES_USER: "{{  .Values.global.secrets.CREATEDB_POSTGRES_USER }}"
  CREATEDB_POSTGRES_PASSWORD: "{{  .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD }}"
  CREATEDB_POSTGRES_HOST: "{{  .Values.global.secrets.CREATEDB_POSTGRES_HOST }}"
  CREATEDB_POSTGRES_PORT: "{{  .Values.global.secrets.CREATEDB_POSTGRES_PORT }}"
  CREATEDB_POSTGRES_DATABASE: "{{  .Values.global.secrets.CREATEDB_POSTGRES_DATABASE }}"
  MQTT_AUTH_POSTGRES_USER: "{{  .Values.global.secrets.MQTT_AUTH_POSTGRES_USER }}"
  MQTT_AUTH_POSTGRES_PASS: "{{  .Values.global.secrets.MQTT_AUTH_POSTGRES_PASS }}"
  MQTT_AUTH_POSTGRES_HOST: "{{  .Values.global.secrets.MQTT_AUTH_POSTGRES_HOST }}"
  MQTT_AUTH_POSTGRES_PORT: "{{  .Values.global.secrets.MQTT_AUTH_POSTGRES_PORT }}"
  MQTT_AUTH_POSTGRES_DB: "{{  .Values.global.secrets.MQTT_AUTH_POSTGRES_DB }}"
  MQTT_AUTH_PG_TLSMODE: "{{  .Values.global.secrets.MQTT_AUTH_PG_TLSMODE }}"
  FRONTEND_POSTGRES_HOST: "{{  .Values.global.secrets.FRONTEND_POSTGRES_HOST }}"
  FRONTEND_POSTGRES_PORT: "{{  .Values.global.secrets.FRONTEND_POSTGRES_PORT }}"
  FRONTEND_POSTGRES_DB: "{{  .Values.global.secrets.FRONTEND_POSTGRES_DB }}"
  FRONTEND_POSTGRES_USER: "{{  .Values.global.secrets.FRONTEND_POSTGRES_USER }}"
  FRONTEND_POSTGRES_PASS: "{{  .Values.global.secrets.FRONTEND_POSTGRES_PASS }}"
  S3MAP_POSTGRES_HOST: "{{  .Values.global.secrets.S3MAP_POSTGRES_HOST }}"
  S3MAP_POSTGRES_PORT: "{{  .Values.global.secrets.S3MAP_POSTGRES_PORT }}"
  S3MAP_POSTGRES_USER: "{{  .Values.global.secrets.S3MAP_POSTGRES_USER }}"
  S3MAP_POSTGRES_PASS: "{{  .Values.global.secrets.S3MAP_POSTGRES_PASS }}"
  S3MAP_POSTGRES_DB: "{{  .Values.global.secrets.S3MAP_POSTGRES_DB }}"
  SMS_DB_USER: "{{  .Values.global.secrets.SMS_DB_USER }}"
  SMS_DB_PASSWORD: "{{  .Values.global.secrets.SMS_DB_PASSWORD }}"
  SMS_DB_PORT: "{{  .Values.global.secrets.SMS_DB_PORT }}"
  SMS_DB_DB: "{{  .Values.global.secrets.SMS_DB_DB }}"
  SMS_DB_HOST: "{{  .Values.global.secrets.SMS_DB_HOST }}"
  SMS_URL: "{{  .Values.global.secrets.SMS_URL }}"
  SMS_ACCESS_TYPE: "{{  .Values.global.secrets.SMS_ACCESS_TYPE }}"
  CV_DB_USER: "{{  .Values.global.secrets.CV_DB_USER }}"
  CV_DB_PASSWORD: "{{  .Values.global.secrets.CV_DB_PASSWORD }}"
  CV_DB_PORT: "{{  .Values.global.secrets.CV_DB_PORT }}"
  CV_DB_DB: "{{  .Values.global.secrets.CV_DB_DB }}"
  CV_DB_HOST: "{{  .Values.global.secrets.CV_DB_HOST }}"
  CV_URL: "{{  .Values.global.secrets.CV_URL }}"
  CV_ACCESS_TYPE: "{{  .Values.global.secrets.CV_ACCESS_TYPE }}"