replicaCount: 1

enabled: true

image:
  repository: "docker.io/pgsty/silo"
  tag: "RELEASE.2026-08-06T00-00-00Z"
  digest: "sha256:29a498b24669cae1fed11c1a2fb2b3d73c68829a0a9c0b14e71b386671d38fac"
  pullPolicy: Always
name: object-storage

command:
  executable: "silo"

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

env: []

existingSecret: ""
existingConfigMap: ""

ftp:
  enabled: false
  port: 40021
  passivePortRange:
    enabled: false
    start: 30000
    end: 30010
  tls:
    enabled: false
    existingSecret: ""
    privateKeyKey: minio-ftp.key
    publicCertKey: minio-ftp.crt

sftp:
  enabled: false
  port: 40022
  sshPrivateKey:
    existingSecret: ""
    key: id_ed25519

certs:
  mountPath: /minio/certs
