replicaCount: 1

enabled: true

image:
  repository: "minio/minio"
  tag: "RELEASE.2025-09-07T16-13-09Z"
  pullPolicy: Always
name: object-storage

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

env: []

existingSecret: ""
existingConfigMap: ""
