replicaCount: 1

image:
  repository: "minio/minio"
  tag: latest
  pullPolicy: Always
name: object-storage

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop: ["ALL"]
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

existingSecret: ""