replicaCount: 1

image:
  repository: "registry.hzdr.de/ufz-tsm/timeio-images/database"
  tag: latest
  pullPolicy: Always
name: database
port: 5432

securityContext:
  allowPrivilegeEscalation: False
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault