apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-envvars
data:
  STA_ENDPOINT_URL: "{{ .Values.global.ingress.url }}/sta/"
  UVICORN_ARGS: ""
  ROOT_PATH: "/tsmdl"
  ORGANIZATION: "ufz"
  IDP_USERINFO_URL: {{ .Values.global.envvars.OIDC_API_URL | quote }}