{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  UFZ_DB_URL: "postgresql://{{-  .Values.global.secrets.CREATEDB_POSTGRES_USER -}}:{{-  .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD -}}@{{-  .Values.global.envvars.CREATEDB_POSTGRES_HOST -}}/{{-  .Values.global.envvars.CREATEDB_POSTGRES_DATABASE -}}"
{{- end }}