apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  serviceName: {{ .Values.name }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          capabilities:
            drop: {{ .Values.securityContext.capabilities.drop }}
          runAsUser: {{ .Values.worker.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          seccompProfile:
            type: {{ .Values.securityContext.seccompProfile.type }}
        command:
        - tini
        - --
        - /bin/sh
        - -c
        - /tmp/entrypoint/cron-entrypoint.sh
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-envvars
        - secretRef:
            name: {{ if .Values.global.createSecrets }}{{ printf "%s-secret" .Values.name }}{{ else }}{{ index .Values.global .Values.name "existingSecret" }}{{ end }}
        volumeMounts:
        - mountPath: /tmp/entrypoint/cron-entrypoint.sh
          name: {{ .Values.name }}-entrypoint
          subPath: cron-entrypoint.sh
          readOnly: true
        - mountPath: /tmp/cron/crontab.txt
          name: crontab-pv
          subPath: crontab.txt
          readOnly: true
      - name: {{ .Values.worker.name }}
        image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.worker.securityContext.allowPrivilegeEscalation }}
          capabilities:
            drop: {{ .Values.worker.securityContext.capabilities.drop }}
          runAsUser: {{ .Values.worker.securityContext.runAsUser }}
          runAsNonRoot: {{ .Values.worker.securityContext.runAsNonRoot }}
          seccompProfile:
            type: {{ .Values.worker.securityContext.seccompProfile.type }}
        command: ["python3", "setup_crontab.py"]
        envFrom:
          - configMapRef:
              name: {{ .Values.worker.name }}-envvars
          - secretRef:
              name: {{ if .Values.global.createSecrets }}{{ printf "%s-secret" .Values.worker.name }}{{ else }}{{ index .Values.global .Values.name "worker" "existingSecret" }}{{ end }}
        volumeMounts:
          - mountPath: /tmp/cron
            name: crontab-pv
      initContainers:
        - name: crontab-file-init
          image: busybox
          securityContext:
            allowPrivilegeEscalation: {{ .Values.worker.securityContext.allowPrivilegeEscalation }}
            capabilities:
              drop: {{ .Values.worker.securityContext.capabilities.drop }}
            runAsUser: {{ .Values.worker.securityContext.runAsUser }}
            runAsNonRoot: {{ .Values.worker.securityContext.runAsNonRoot }}
            seccompProfile:
              type: {{ .Values.worker.securityContext.seccompProfile.type }}
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -f /tmp/cron/crontab.txt ]; then
                touch /tmp/cron/crontab.txt
                echo "* * * * * /scripts/sync_sms_materialized_views.py > $STDOUT 2>$STDERR" > /tmp/cron/crontab.txt
              fi
          volumeMounts:
            - mountPath: /tmp/cron
              name: crontab-pv
      volumes:
      - name: {{ .Values.name }}-entrypoint
        configMap:
          name: {{ .Values.name }}-entrypoint
          defaultMode: 0775
      - name: crontab-pv
        persistentVolumeClaim:
          claimName: crontab-pvc
