{{- if .Values.existingSecret | empty }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  CREATEDB_POSTGRES_USER: "{{  .Values.global.secrets.POSTGRES_USER }}"
  CREATEDB_POSTGRES_PASSWORD: "{{  .Values.global.secrets.POSTGRES_PASSWORD }}"
  SMS_API_TOKEN: "{{ .Values.global.secrets.SMS_API_TOKEN }}"
  FTP_AUTH_DB_DSN: "postgresql://{{  .Values.global.secrets.FRONTEND_POSTGRES_USER }}:{{  .Values.global.secrets.FRONTEND_POSTGRES_PASS }}@{{  .Values.global.envvars.FRONTEND_POSTGRES_HOST }}/{{  .Values.global.envvars.FRONTEND_POSTGRES_DB }}"
{{- end }}