{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  CREATEDB_POSTGRES_USER: "{{  .Values.global.secrets.CREATEDB_POSTGRES_USER }}"
  CREATEDB_POSTGRES_PASSWORD: "{{  .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD }}"
  SMS_API_TOKEN: "{{ .Values.global.secrets.SMS_API_TOKEN }}"
  MINIO_USER: "{{ .Values.global.secrets.MINIO_ROOT_USER }}"
  MINIO_PASSWORD: "{{ .Values.global.secrets.MINIO_ROOT_PASSWORD }}"
  CONFIGDB_DSN: "postgresql://{{-  .Values.global.secrets.CREATEDB_POSTGRES_USER -}}:{{-  .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD -}}@{{-  .Values.global.envvars.CREATEDB_POSTGRES_HOST -}}/{{-  .Values.global.envvars.CREATEDB_POSTGRES_DATABASE -}}"
  MQTT_USER: "{{  .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{  .Values.global.secrets.MQTT_PASSWORD }}"
  FERNET_ENCRYPTION_SECRET: {{ .Values.global.secrets.FERNET_ENCRYPTION_SECRET | quote }}
  DATABASE_DSN: "postgresql://{{  .Values.global.secrets.CREATEDB_POSTGRES_USER }}:{{  .Values.global.secrets.CREATEDB_POSTGRES_PASSWORD }}@{{  .Values.global.envvars.CREATEDB_POSTGRES_HOST }}/{{  .Values.global.envvars.CREATEDB_POSTGRES_DATABASE }}"
{{- end }}