{{- if .Values.enabled }}
{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.worker.name }}-secret
type: Opaque
stringData:
  MQTT_USER: "{{ .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{ .Values.global.secrets.MQTT_PASSWORD }}"
  DSMDB_DSN: "postgresql://{{-  .Values.global.secrets.DSM_API_DATABASE_USER -}}:{{-  .Values.global.secrets.DSM_API_DATABASE_PASS -}}@{{-  .Values.global.envvars.CREATEDB_POSTGRES_HOST -}}:5432/{{-  .Values.global.envvars.CREATEDB_POSTGRES_DATABASE -}}"
{{- end }}
{{- end }}