{{- if .Values.enabled }}
{{- if .Values.global.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.worker.name }}-secret
type: Opaque
stringData:
  MQTT_USER: "{{  .Values.global.secrets.MQTT_USER }}"
  MQTT_PASSWORD: "{{  .Values.global.secrets.MQTT_PASSWORD }}"
  CONFIGDB_DSN: "postgresql://{{-  .Values.global.secrets.CONFIGDB_POSTGRES_USER -}}:{{-  .Values.global.secrets.CONFIGDB_POSTGRES_PASSWORD -}}@{{-  .Values.global.envvars.CONFIGDB_POSTGRES_HOST -}}/{{-  .Values.global.envvars.CONFIGDB_POSTGRES_DATABASE -}}"
{{- end }}
{{- end }}