---
combined-e2e-test:
  image: "docker:${DOCKER_IMAGE_TAG}"
  stage: "end-to-end"
  needs:
    - "build-and-push-images"
  before_script:
    # As job has `needs` dependency to the build job, we can use the .env defined there
    - "apk add --no-cache curl python3 postgresql-client jq"
    - "docker compose up -d --quiet-pull"
    - "sleep 20"
  script: ./scripts/e2e.sh
  rules:
    # Run if pipeline is triggered by a tag and build job was successful
    - if: "$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED"
      when: on_success
    # Never run if pipeline is triggered by a merge_request_event or a push on main
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main'"
      when: never
    # Run if pipeline is triggered by a push on a branch and build job was successful
    - if: "$CI_PIPELINE_SOURCE == 'push'"
      when: on_success
  tags:
    - "dind"