---

stage-tag-images-in-registry:
  stage: release
  rules:
    # Rules are evaluated in order until the first match.
    # We only want to push new images if source files changes
    # or if we manually decide to do so.

    # Run if pipeline is triggered by a push on main
    # and changes to source files or Dockerfiles were made. 
    - if: "$CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE == 'push'"
      changes:
        - .env.example
        - src/**/*
        - dispatcher/**/*
        - configdb_updater/**/*
        - init/**/*
        - tomcat/**/*
      when: always
    # Run manually if pipeline is triggered by a push on main  
    - if: "$CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE == 'push'"
      when: manual
  image: "docker:${DOCKER_IMAGE_TAG}"
  # Job has no dependencies. It is the first job to run in the post-merge pipeline
  needs: []
  before_script:
    # As job runs in post-merge pipeline, we can not use the .env of the previous stages but need to redefine it
    - cp .env.example .env
    # Retrieve name of branch that was merged into main.
    # Could be changed to something more robust than retrieving it from the `Merge commit message`
    - export BRANCH_NAME=$(git log --merges -1 --pretty=format:'%s' | sed "s/Merge branch '\(.*\)' into 'main'/\1/")
    - |
      echo "TIMEIO_INIT_IMAGE_TAG=$BRANCH_NAME" >> .env
      echo "TIMEIO_FROST_IMAGE_TAG=$BRANCH_NAME" >> .env
      echo "TIMEIO_CRON_SCHEDULER_IMAGE_TAG=$BRANCH_NAME" >> .env
      echo "TIMEIO_DISPATCHER_IMAGE_TAG=$BRANCH_NAME" >> .env
      echo "TIMEIO_CONFIGDB_UPDATER_IMAGE_TAG=$BRANCH_NAME" >> .env
    - export BUILD_DATE=$(echo -n $(date -u +%Y-%m-%d-%H%M%S))
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - export REGISTRY=$(grep TIMEIO_IMAGE_REGISTRY .env | cut -d'=' -f2)
    - echo "pulling images from branch $BRANCH_NAME"
  after_script:
    - docker logout
  script:
    - docker compose pull -q $BUILD_SERVICES
    - |
      for image in $(docker images --format '{{ .Repository }}'); do 
        docker tag $image:$BRANCH_NAME $image:latest;
        docker tag $image:$BRANCH_NAME $image:$BUILD_DATE;
        docker push $image:latest;
        docker push $image:$BUILD_DATE;
      done
    - docker images
  tags:
    - "dind"


prod-tag-images-in-registry:
  stage: release
  rules:
    # Run if pipeline is triggered by a tag and if integration and end-to-end tests were successful
    - if: "$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED"
      when: on_success
  image: "docker:${DOCKER_IMAGE_TAG}"
  before_script:
    # As job has `needs` dependency tracing back to the build job, we can use the .env defined there
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - export REGISTRY=$(grep TIMEIO_IMAGE_REGISTRY .env | cut -d'=' -f2)
    - export PROD_TAG="prod-${CI_COMMIT_TAG}"
    - echo "PROD_TAG is $PROD_TAG"
  after_script:
    - docker logout
  script:
    - docker compose pull -q $BUILD_SERVICES
    # Images built in a commit tag pipeline on main are tagged "main" by build job.
    - |
      for image in $(docker images --format '{{ .Repository }}'); do
        docker tag $image:${CI_COMMIT_TAG} $image:$PROD_TAG;
        docker push $image:$PROD_TAG;
      done
    - docker images
  tags:
    - "dind"