---

# This triggers the CI in the deployment repo [1], 
# which deploys the latest changes on the stage VM.  
# [1] https://git.ufz.de/rdm-software/timeseries-management/tsm-deployment
stage-trigger-deployment:
  stage: notify
  needs:
    - "stage-tag-images-in-registry"
  image: "docker:${DOCKER_IMAGE_TAG}"
  script:
    - apk add --no-cache curl
    - echo "triggering deployment on stage"
    - |
      curl -X POST "https://git.ufz.de/api/v4/projects/3977/trigger/pipeline" \
        -F "token=$PIPELINE_TOKEN_STAGE" \
        -F "ref=main"
    - echo "Check deployment pipeline on https://git.ufz.de/rdm-software/timeseries-management/tsm-deployment"
  rules:
    # Run if pipeline is triggered by a push on main and latest/date image tagging was successful
    - if: "$CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE == 'push'"
      when: on_success


prod-trigger-deployment:
  stage: notify
  needs:
    - "prod-tag-images-in-registry"
  image: "docker:${DOCKER_IMAGE_TAG}"
  script:
    - apk add --no-cache curl
    - echo "triggering deployment on prod"
    - |
      curl -X POST "https://git.ufz.de/api/v4/projects/4741/trigger/pipeline" \
        -F "token=$PIPELINE_TOKEN_PROD" \
        -F "ref=main" \
        -F "variables[TAG]=$CI_COMMIT_TAG"
    - echo "Check deployment pipeline on https://git.ufz.de/rdm-software/timeseries-management/tsm-prod-deployment"
  rules:
    # Always run if pipeline is triggered by a tag and prod images tagging was successful
    - if: "$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED"
      when: on_success