---
docker-image-scan:
  image: "docker:${DOCKER_IMAGE_TAG}"
  stage: "scan"
  needs:
    - "deploy-images-to-registry"
  variables:
    TRIVY_DISABLE_VEX_NOTICE: "true"
  before_script:
    # Install Trivy in the pipeline environment
    - "cp .env.example .env"
    - "apk add --no-cache curl"
    - "curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${TRIVY_VERSION}"
  script:
    - "docker compose pull -q"
    - |
      for image in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep -v "<none>"); do
        echo "Scanning $image";
        trivy image $image -q --severity CRITICAL >> critical_all.cve;
        trivy image $image -q --severity CRITICAL --ignore-unfixed >> critical_fixed.cve;
        trivy image $image -q --severity HIGH >> high_all.cve;
        trivy image $image -q --severity HIGH --ignore-unfixed >> high_fixed.cve; 
      done
    - ls -la *.cve
    - cat *.cve
  artifacts:
    paths:
      - "*.cve"
    expire_in: 30 days
  rules:
    # Always run pipeline if
    - if: "$CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE == 'push'"
      when: on_success
  tags:
    - "dind"