---

build-and-push-to-registry:
  stage: build
  image: "docker:${DOCKER_IMAGE_TAG}"
  before_script:
    - cp .env.example .env
    - echo $(date +%Y-%m-%d-%H%M%S) > .build_date
    #- echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - |
      echo "TIMEIO_INIT_IMAGE_TAG=$CI_COMMIT_REF_NAME" >> .env
      echo "TIMEIO_DATABASE_IMAGE_TAG=$CI_COMMIT_REF_NAME" >> .env
      echo "TIMEIO_FROST_IMAGE_TAG=$CI_COMMIT_REF_NAME" >> .env
      echo "TIMEIO_CRON_SCHEDULER_IMAGE_TAG=$CI_COMMIT_REF_NAME" >> .env
      echo "TIMEIO_DISPATCHER_IMAGE_TAG=$CI_COMMIT_REF_NAME" >> .env
      echo "TIMEIO_CONFIGDB_UPDATER_IMAGE_TAG=$CI_COMMIT_REF_NAME" >> .env
    #after_script:
    #- docker logout
  script:
    - docker compose build -q init database cron-scheduler frost worker-configdb-updater worker-db-setup
    - docker images -a
  artifacts:
    paths:
      - .build_date
