---
check-protected-files:
  stage: check
  script:
    - echo "Files in flyway/migrations MUST NOT be altered! Undo your changes and commit again."
    - exit 1
  rules:
    - if: "$CI_COMMIT_BRANCH != 'main' && $CI_PIPELINE_SOURCE != 'merge_request_event' && $CI_COMMIT_BEFORE_SHA !~ /^0000/"
      changes:
        - flyway/migrations/public/V0_1__*
        - flyway/migrations/public/V0_2__*
        - flyway/migrations/public/V0_3__*
        - flyway/migrations/public/V0_4_0__*
        - flyway/migrations/public/V0_4_1__*
        - flyway/migrations/public/V1_1__*
        - flyway/migrations/public/V2_1__*
        - flyway/migrations/public/V2_2__*
        - flyway/migrations/public/V2_3__*
        - flyway/migrations/public/V2_4__*
        - flyway/migrations/public/V2_5__*
        - flyway/migrations/public/V2_6__*
        - flyway/migrations/public/V2_7__*
        - flyway/migrations/public/V2_8__*
        - flyway/migrations/public/V2_9__*
        - flyway/migrations/public/V2_10__*
        - flyway/migrations/public/V2_11__*
        - flyway/migrations/public/V2_12__*
        - flyway/migrations/public/V2_13__*
        - flyway/migrations/public/V2_14__*
        - flyway/migrations/public/V2_15__*

black:
  stage: check
  image: python:3.11-slim
  before_script:
    - pip install black
  script:
    - black --check src/ tests/
  rules:
    - if: "$CI_COMMIT_BRANCH != 'main' && $CI_PIPELINE_SOURCE != 'merge_request_event'"

pytest:
  stage: check
  image: python:3.11-slim
  before_script:
    - pip install -r src/requirements.txt  pytest
  script:
    - python3 -m pytest tests
  rules:
    - if: "$CI_COMMIT_BRANCH != 'main' && $CI_PIPELINE_SOURCE != 'merge_request_event'"
