---
stages:
  - "check"
  - "build"
  - "integration"
  - "end-to-end"
  - "release"

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  # ports mapped to 127.0.0.1 will not be reachable from inside docker network
  # need to define PORT Variables here to overwrite ENVVARs from .env
  DATABASE_PORT: 5432
  MQTT_PORT: 1883
  MQTT_PORT_SECURE: 8883
  PROXY_PLAIN_PORT_MAPPING: 80:80
  PROXY_TLS_PORT_MAPPING: 443:443
  PROXY_MINIO_PORT_MAPPING: 9000:9000
  OBJECT_STORAGE_SFTP_PORT: 40022
  OBJECT_STORAGE_FTP_PORT: 40021
  OBJECT_STORAGE_FTP_PASV_PORTS_MAPPING: 30000-30010:30000-30010
  MONITORING_PORT: 8080
  DOCKER_IMAGE_TAG: 28-cli
  DOCKER_SERVICE_IMAGE_TAG: 28-dind
  TRIVY_VERSION: 0.58.2

services:
  - "docker:${DOCKER_SERVICE_IMAGE_TAG}"
