stages:
  - "lint"
  - "test"
  - "deploy"

image: "docker:20.10.16"

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - "docker:20.10.16-dind"

codestyle:
  stage: "lint"
  script:
    - "pip install --ignore-installed pipenv"
    - "pipenv run yamllint --version"
    - "pipenv run yamllint --strict --format colored ."
