---
stages:
  - "check"
  - "scan"
  - "integration"
  - "end-to-end"

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  # ports mapped to 127.0.0.1 will not be reachable from inside docker network
  # need to define PORT Variables here to overwrite ENVVARs from .env
  POSTGRES_PORT: 5432
  MOSQUITTO_PORT: 1883
  MOSQUITTO_PORT_SECURE: 8883
  PROXY_PLAIN_PORT: 80:80
  PROXY_TLS_PORT: 443:443
  PROXY_MINIO_PORT: 9000:9000
  MINIO_SFTP_PORT: 40022
  MINIO_FTP_PORT: 40021
  MINIO_FTP_PASV_PORTS: 30000-30010:30000-30010
  CADVISOR_PORT: 8080
  DOCKER_IMAGE_TAG: 24-cli
  DOCKER_SERVICE_IMAGE_TAG: 24-dind

services:
  - "docker:${DOCKER_SERVICE_IMAGE_TAG}"

check-protected-files:
  stage: check
  script:
    - echo "Files in flyway/migrations MUST NOT be altered! Undo your changes and commit again."
    - exit 1
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - flyway/migrations/V1_1__create_schema_thing_mapping.sql
        - flyway/migrations/V2_1__configdb_add_schema_and_role.sql
        - flyway/migrations/V2_2__configdb_initial_schema.sql
        - flyway/migrations/V2_3__configdb_initial_data.sql
        - flyway/migrations/V2_4__configdb_add_bosch.sql
        - flyway/migrations/V2_5__configdb_drop_S3_not_null.sql
        - flyway/migrations/V2_6__configdb_modify_qaqc_test.sql
