---
stages:
  - "lint"
  - "integration"
  - "deploy"

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - "docker:20.10.16-dind"

codestyle:
  image: "python:3.9"
  stage: "lint"
  script:
    - "pip install --ignore-installed pipenv"
    - "pip install yamllint"
    - "pipenv run yamllint --strict --format colored ."
