---
stages:
  - "check"
  - "integration"
  - "end-to-end"
  - "scan"
  - "release"
  - "notify"

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  # ports mapped to 127.0.0.1 will not be reachable from inside docker network
  # need to define PORT Variables here to overwrite ENVVARs from .env
  DATABASE_URL: 5432
  MQTT_URL: 1883
  MQTT_URL_SECURE: 8883
  PROXY_PLAIN_URL: 80
  PROXY_TLS_URL: 443
  PROXY_MINIO_URL: 9000
  OBJECT_STORAGE_SFTP_URL: 40022
  OBJECT_STORAGE_FTP_URL: 40021
  OBJECT_STORAGE_FTP_PASV_URL: 30000-30010:30000-30010
  MONITORING_URL: 8080
  DOCKER_IMAGE_TAG: 27-cli
  DOCKER_SERVICE_IMAGE_TAG: 27-dind
  TRIVY_VERSION: 0.58.2

services:
  - "docker:${DOCKER_SERVICE_IMAGE_TAG}"
