stages:
  - build
  - release

variables:
  HELM_PACKAGE_NAME: "timeio"
  PACKAGE_REGISTRY: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm"
  PACKAGE_REGISTRY_TOKEN: "${CI_JOB_TOKEN}"

  # Define the common helm_install_script
.helm_install_script: &helm_install_script
  - apk add --no-cache curl bash 
  - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  - chmod 700 ./get_helm.sh
  - ./get_helm.sh