---
stages:
  - "integration"
  - "end-to-end"

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  POSTGRES_PORT: 5432
  MOSQUITTO_PORT: 1883
  MOSQUITTO_PORT_SECURE: 8883
  PROXY_PLAIN_PORT: 80:80
  PROXY_TLS_PORT: 443:443
  PROXY_MINIO_PORT: 9000:9000
  MINIO_SFTP_PORT: 40022
  MINIO_FTP_PORT: 40021
  MINIO_FTP_PASV_PORTS: 30000-30010:30000-30010
  CADVISOR_PORT: 8080
  DOCKER_IMAGE_TAG: 24  
  DJANGO_TRUSTED_ORIGINS: http://docker:80
  PROXY_URL: http://docker:80

services:
  - "docker:${DOCKER_IMAGE_TAG}"
