---
docker-image-scan:
  image: "docker:${DOCKER_IMAGE_TAG}"
  stage: "scan"
  variables:
    TRIVY_DISABLE_VEX_NOTICE: "true"
  before_script:
    # Install Trivy in the pipeline environment
    - "apk add --no-cache curl"
    - "curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${TRIVY_VERSION}"
    - "cp .env.example .env"
  script:
    - "docker compose pull -q"
    - "docker compose build -q"
    - |
      for image in $(docker images --format "{{.Repository}}:{{.Tag}}"); do
        echo "Scanning $image";
        trivy image $image -q --severity CRITICAL >> critical_all.cve;
        trivy image $image -q --severity CRITICAL --ignore-unfixed >> critical_fixed.cve;
        trivy image $image -q --severity HIGH >> high_all.cve;
        trivy image $image -q --severity HIGH --ignore-unfixed >> high_fixed.cve; 
      done
  artifacts:
    paths:
      - "*.cve"
    expire_in: 30 days
  rules:
    # Run only when a merge request is merged into the `main` branch
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE == "merged"'
      when: always
    # Prevent the job from running in all other cases
    - when: never
  tags:
    - "dind"