---
object-storage-test:
  image: "docker:24.0.6-dind"
  stage: "end-to-end"
  before_script:
    - "apk add --no-cache curl jq iputils"
  script:
    - "cp .env.example .env"
    - "docker compose up -d --force-recreate -V --quiet-pull --build"
    - "sleep 15" 
    - "docker compose exec -T frontend python3 manage.py loaddata user.json"
    - "sleep 2"
    - "docker compose exec -T frontend python3 manage.py loaddata thing.json"
    - "sleep 2"
    - "docker compose exec -T frontend python3 manage.py dumpdata tsm.rawdatastorage > object-storage.json"
    - "export MINIO_USER=$(cat object-storage.json | jq -r '.[].fields.access_key')"
    - "echo $MINIO_USER"
    - "export MINIO_PASSWORD=$(cat object-storage.json | jq -r '.[].fields.secret_key')"
    - "echo $MINIO_PASSWORD"
    - "ping -c 4 localhost"
    - "curl -u ${MINIO_USER}:${MINIO_PASSWORD} ftp://localhost:40021 -I -s -o /dev/null || exit 1"
  tags:
    - "dind"

database-test:
  image: "docker:24.0.6-dind"
  stage: "end-to-end"
  before_script:
    - "apk add --no-cache postgresql-client jq iputils"
  script:
    - "ls -lah /certs/ca"
    - "ls -lah /certs/client"
    - "ls -lah /certs/server"
    - "cp .env.example .env"
    - "docker compose up -d --force-recreate -V --quiet-pull --build"
    - "sleep 15" 
    - "docker compose exec -T frontend python3 manage.py loaddata user.json"
    - "sleep 2"
    - "docker compose exec -T frontend python3 manage.py loaddata thing.json"
    - "sleep 2"
    - "docker compose exec -T frontend python3 manage.py dumpdata tsm.database > database.json"
    - "export DB_USER=$(cat database.json | jq -r '.[].fields.username')"
    - "echo $DB_USER"
    - "export DB_PASSWORD=$(cat database.json | jq -r '.[].fields.password')"
    - "echo $DB_PASSWORD"
    - "export DB_NAME=$(cat database.json | jq -r '.[].fields.name')"
    - "echo $DB_NAME"
    - "ping -c 4 127.0.0.1"
    - "PGPASSWORD=${DB_PASSWORD} psql -U ${DB_USER} -h localhost -d ${DB_NAME} -tAc \"SELECT * from ${DB_USER}.thing\" &>/dev/null || exit 1"
  tags:
    - "dind"

