---
visualization-e2e:
  image: "docker:24-dind"
  stage: "end-to-end"
  before_script:
    - "apk add --no-cache curl jq python3"
    - "cp .env.example .env"
    - "docker compose up -d proxy --force-recreate -V --quiet-pull"
    - "sleep 20"
  script:
    - "docker compose restart proxy"
    - "docker compose exec -T frontend python3 manage.py loaddata user.json"
    - "sleep 2"
    - "docker compose exec -T frontend python3 manage.py loaddata thing.json"
    - "sleep 2"
    - "docker compose exec -T frontend python3 manage.py dumpdata tsm.thing > thing_dump.json"

    - "THING_UID=$(cat thing_dump.json | jq -r .[].fields.thing_id) || echo nope"
    - "echo $THING_UID"
    - "GROUP_ID=$(cat thing_dump.json | jq -r .[].fields.group) || echo nope"
    - "echo $GROUP_ID"
    - "GROUP_UID=$(python3 -c \"import uuid; print(uuid.UUID(int=${GROUP_ID}))\") || echo nope"
    - "echo $GROUP_UID"
    - "curl -Is -u grafana:grafana http://docker/visualization/api/dashboards/uid/${THING_UID} || echo nope"
    - "curl -Is -u grafana:grafana http://docker/visualization/api/dashboards/uid/${GROUP_UID} || echo nope"
    - "curl -Is -u grafana:grafana http://docker/visualization/api/datasources/uid/${GROUP_UID} || echo nope"
    - "curl -s -u grafana:grafana http://docker/visualization/api/teams/search?uid=${GROUP_UID} > teams.json"
    - "TEAMS_ID=$(cat teams.json | jq -r .teams[0].orgId)"
    - "TEAMS_UID=$(python3 -c \"import uuid; print(uuid.UUID(int=${TEAMS_ID}))\") || echo nope"
    - "echo $TEAMS_UID"
    - "[ \"$TEAMS_UID\" == \"$GROUP_UID\" ] || echo nope"
  tags:
    - "dind"
