---
avro-thing-creation-e2e:
  image: "docker:24-dind"
  stage: "end-to-end"
  before_script:
    - "apk add --no-cache python3 curl jq"
    - "python3 -m ensurepip"
    - "python3 -m pip install --upgrade pip"
    - "python3 -m pip install fastavro paho-mqtt threading"
    - "cp .env.example .env"
    - "docker compose up -d --force-recreate -V --quiet-pull --build"
  script:
    - "echo yes"
  tags:
    - "dind"