---
avro-thing-creation-e2e:
  image: "docker:24-dind"
  stage: "end-to-end"
  before_script:
    - "apk add --no-cache python3"
    - "python3 -m ensurepip"
    - "python3 -m pip install --upgrade pip"
    - "python3 -m pip install fastavro paho-mqtt"
    - "cp .env.example .env"
    - "docker compose up -d --force-recreate -V --quiet-pull --build"
    - "sleep 20"
  script:
    - "echo \"Check if thing_creation message is valid\""
    - "./.gitlab/ci/avro-thing-creation.sh"
  tags:
    - "dind"