---
frost-e2e:
  image: "docker:${DOCKER_IMAGE_TAG}"
  stage: "end-to-end"
  before_script:
    - "apk add --no-cache curl jq"
    - "cp .env.example .env"
    - "docker compose up -d --force-recreate -V --quiet-pull --build"
    - "sleep 20"
  script:
    - "docker compose exec -T frontend python3 manage.py loaddata user.json"
    - "sleep 2"
    - "docker compose exec -T frontend python3 manage.py loaddata thing.json"
    - "sleep 2"
    - "docker compose exec -T frontend python3 manage.py dumpdata tsm.database > database.json"
    - "sleep 10"
    - "docker compose logs frost"
    - "export DB_USER=$(cat database.json | jq -r '.[].fields.username')"
    - "echo $DB_USER"
    - "curl -Isf http://docker/sta/${DB_USER} || exit 1"
  tags:
    - "dind"
