---
proxy-test:
  stage: "integration"
  image: "docker:20.10.16-dind"
  before_script:
    - "apk add --no-cache curl"
    - "cp .env.example .env"
    - "docker compose build -q"
    - "docker compose pull -q"
    - "docker compose up -d -V"
    - "docker compose ps"
  script:
    - "sleep 20"
    - "curl -I http://docker && echo yes || echo nope"
  tags:
    - "dind"
