---
docker-service-test:
  image: "docker:${DOCKER_IMAGE_TAG}"
  stage: "integration"
  needs: []
  before_script:
    - "apk add --no-cache bash"
    - "docker compose up -d --quiet-pull --build"
    - "docker compose logs init"
    - "sleep 20"
  script:
    - "docker ps"
    - "docker compose logs flyway"
    - "cd .gitlab/ci"
    - "chmod +x ./dockertest.sh"
    - "./dockertest.sh"
  tags:
    - "dind"

mqtt-service-test:
  image: "docker:${DOCKER_IMAGE_TAG}"
  stage: "integration"
  needs: []
  before_script:
    - "apk add --no-cache python3"
    - "python3 -m venv venv"
    - "source venv/bin/activate"
    - "python3 -m ensurepip"
    - "python3 -m pip install --upgrade pip"
    - "python3 -m pip install paho-mqtt==1.6.1"
    - "docker compose up -d --quiet-pull --build"
    - "sleep 20"
  script:
    - "chmod +x .gitlab/ci/py/mqtt-service-test.py"
    - ".gitlab/ci/py/mqtt-service-test.py || exit 1"
    - "docker compose logs mqtt-cat"
  tags:
    - "dind"

combined-integration-test:
  image: "docker:${DOCKER_IMAGE_TAG}"
  stage: "integration"
  needs: []
  before_script:
    - "export DJANGO_TRUSTED_ORIGINS='http://docker:80 http://docker'"
    - "apk add --no-cache curl postgresql-client"
    - "docker compose up -d --quiet-pull --build"
    - "sleep 20"
  script:
    - "echo 'testing object storage integration...'"
    - "curl -u minioadmin:minioadmin ftp://docker:40021 -I -s -o /dev/null || exit 1"
    - "echo 'testing database integration...'"
    - "PGPASSWORD=postgres psql -U postgres -d postgres -h docker -tAc \"SELECT version()\" || exit 1"
    - "echo 'testing proxy integration...'"
    - "curl -Isf http://docker -o /dev/null || exit 1"
    - "curl -Isf http://docker/object-storage/ -o /dev/null || exit 1"
    - "curl -Isf http://docker/visualization/ -o /dev/null || exit 1"
    - "curl -Isf http://docker/sta/ -o /dev/null || exit 1"
    - "curl -Isf http://docker/frontend || echo 'fail'"
    # so for now we curl it from inside the proxy container
    #- "docker compose exec proxy curl -Isf http://proxy/frontend -o /dev/null || exit 1"
  tags:
    - "dind"
