---
docker-service-test:
  image: "docker:20.10.16"
  stage: "integration"
  before_script:
    - "apk add --no-cache bash"
  script:
    - "mv .env.example .env"
    - "cp .env .gitlab/ci/.env"
    - "echo $GROUP_TOKEN | docker login \
      $SCHEDULER_REGISTRY -u $GROUP_USER --password-stdin"
    - "echo $GROUP_TOKEN | docker login \
     $DISPATCHER_REGISTRY -u $GROUP_USER --password-stdin"
    - "docker-compose up -d"
    - "sleep 15"
    - "docker ps"
    - "cd .gitlab/ci"
    - "chmod +x ./dockertest.sh"
    - "./dockertest.sh"
  tags:
    - "hifis"

mqtt-service-test:
  image: "docker:20.10.16"
  stage: "integration"
  script:
    - "mv .env.example .env"
    - "cp .env .gitlab/ci/.env"
    - "echo $GROUP_TOKEN | docker login \
      $SCHEDULER_REGISTRY -u $GROUP_USER --password-stdin"
    - "echo $GROUP_TOKEN | docker login \
     $DISPATCHER_REGISTRY -u $GROUP_USER --password-stdin"
    - "docker-compose up -d"
    - "sleep 15"
    - "docker-compose exec -T mqtt-broker
      bash -c $'echo `echo -n integrate && /mosquitto/pw -p cicd` >>
      /mosquitto-auth/mosquitto.passwd'"
    - "docker-compose restart mqtt-broker"
    - "sleep 30"
    - 'echo "very nice data!" | docker-compose exec -T mqtt-broker sh -c
       "mosquitto_pub -h mqtt-broker -t
       mqtt_ingest/integrate/beautiful/sensor/1 -u mqtt -P mqtt -s"'
    - 'docker-compose logs mqtt-cat'
  tags:
    - "hifis"

thing-creation-test:
  image: "docker:20.10.16-dind"
  stage: "integration"
  before_script:
    - "apk add --no-cache curl"
    - "apk add --no-cache postgresql"
    - "apk add --no-cache bash"
    - "apk add --no-cache openssl"
    - "apk add --no-cache nmap"
  #  variables:
  #    POSTGRES_SSLMODE: disable
  script:
    - "mv .env.example .env"
    - "echo 'POSTGRES_PORT=5432' >> .env"
    - "echo 'PROXY_MINIO_PORT=9000:9000' >> .env"
    - "cp .env .gitlab/ci/.env"
    - "echo $GROUP_TOKEN | docker login \
      $SCHEDULER_REGISTRY -u $GROUP_USER --password-stdin"
    - "echo $GROUP_TOKEN | docker login \
      $DISPATCHER_REGISTRY -u $GROUP_USER --password-stdin"
    - "docker-compose up -d --force-recreate -V --quiet-pull"
    - "sleep 30"
    - "docker-compose logs object-storage"
    - 'cat thing-event-msg.json | docker-compose exec -T mqtt-broker sh -c
      "mosquitto_pub -t thing_creation -u mqtt -P mqtt -s"'
    - "curl https://dl.min.io/client/mc/release/linux-amd64/mc \
      --create-dirs \
      -o $HOME/minio-binaries/mc"
    - "chmod +x $HOME/minio-binaries/mc"
    - "export PATH=$PATH:$HOME/minio-binaries/"
    - "mc alias set minio http://docker:9000 minioadmin minioadmin"
    - "mc tag list minio/thedoors-057d8bba-40b3-11ec-a337-125e5a40a849"
    - "psql 'postgresql://postgres:postgres@docker:5432?sslmode=disable' -l || true"
    - "docker-compose logs database"
    - "docker-compose ps"
    - "nmap -p 5432 docker"
    - "echo | openssl s_client -showcerts -connect docker:5432 \
      -starttls postgres"
    - "cd .gitlab/ci"
    - "chmod +x ./databasetest.sh"
    - "./databasetest.sh"
  tags:
    - "hifis"

debug-ci:
  image: "docker:20.10.16-dind"
  stage: "integration"
  script:
    - "docker-compose up -d database"
    - "docker inspect $(docker-compose ps -q database)"
    - "docker port $(docker-compose ps -q database)"
    - "ip addr"
    - "nslookup docker"
    - "hostname"
    - "hostname --all-fqdns"
  tags:
    - "hifis"
