---
docker-service-test:
  image: "docker:${DOCKER_IMAGE_TAG}"
  stage: "integration"
  needs:
    - "build-and-push-images"
  before_script:
    - "apk add --no-cache bash"
    - "docker compose up -d --quiet-pull"
    - "docker compose logs init"
    - "sleep 20"
  script:
    - "docker ps"
    - "docker compose logs flyway"
    - "cd .gitlab/ci"
    - "chmod +x ./dockertest.sh"
    - "./dockertest.sh"
  rules:
    # Always run pipeline if triggered by a tag
    - if: "$CI_COMMIT_TAG"
      when: always
    # Never run if pipeline is triggered by a merge_request_event or a push on main
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main'"
      when: never
    # Always run if pipeline is triggered by a push on a branch
    - if: "$CI_PIPELINE_SOURCE == 'push'"
      when: always
  tags:
    - "dind"

mqtt-service-test:
  image: "docker:${DOCKER_IMAGE_TAG}"
  stage: "integration"
  needs:
    - "build-and-push-images"
  before_script:
    - "apk add --no-cache python3"
    - "python3 -m venv venv"
    - "source venv/bin/activate"
    - "python3 -m ensurepip"
    - "python3 -m pip install --upgrade pip"
    - "python3 -m pip install paho-mqtt==1.6.1"
    - "docker compose up -d --quiet-pull"
    - "sleep 20"
  script:
    - "chmod +x .gitlab/ci/py/mqtt-service-test.py"
    - ".gitlab/ci/py/mqtt-service-test.py || exit 1"
    - "docker compose logs mqtt-cat"
  rules:
    # Always run pipeline if triggered by a tag
    - if: "$CI_COMMIT_TAG"
      when: on_success
    # Never run if pipeline is triggered by a merge_request_event or a push on main
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main'"
      when: never
    # Always run if pipeline is triggered by a push on a branch
    - if: "$CI_PIPELINE_SOURCE == 'push'"
      when: on_success
  tags:
    - "dind"

combined-integration-test:
  image: "docker:${DOCKER_IMAGE_TAG}"
  stage: "integration"
  needs:
    - "build-and-push-images"
  before_script:
    - "export DJANGO_TRUSTED_ORIGINS='http://docker:80 http://docker'"
    - "apk add --no-cache curl postgresql-client"
    - "docker compose up -d --quiet-pull"
    - "sleep 20"
  script:
    - "echo 'testing object storage integration...'"
    - "curl -u minioadmin:minioadmin ftp://docker:40021 -I -s -o /dev/null || exit 1"
    - "echo 'testing database integration...'"
    - "PGPASSWORD=postgres psql -U postgres -d postgres -h docker -tAc \"SELECT version()\" || exit 1"
    - "echo 'testing proxy integration...'"
    - "curl -Isf http://docker -o /dev/null || exit 1"
    - "curl -Isf http://docker/object-storage/ -o /dev/null || exit 1"
    - "curl -Isf http://docker/visualization/ -o /dev/null || exit 1"
    - "curl -Isf http://docker/sta/ -o /dev/null || exit 1"
    - "curl -Isf http://docker/frontend/ || echo nope"
  rules:
    # Always run pipeline if triggered by a tag
    - if: "$CI_COMMIT_TAG"
      when: always
    # Never run if pipeline is triggered by a merge_request_event or a push on main
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main'"
      when: never
    # Always run if pipeline is triggered by a push on a branch
    - if: "$CI_PIPELINE_SOURCE == 'push'"
      when: always
  tags:
    - "dind"
