---
proxy-test:
  stage: "integration"
  before_script:
    - "apt update"
    - "apt install curl bash jq net-tools"
  script:
    - "cp .env.example .env"
    - "docker compose up -d --force-recreate -V --quiet-pull"
    - "sleep 5"
    - "netstat -tulpn"
    - "bash .gitlab/ci/proxytest.sh"
  tags:
    - "dind"
