---
proxy-test:
  image: "docker:24.0.6-dind"
  stage: "integration"
  before_script:
    - "apk add --no-cache curl"
  script:
    - "cp .env.example .env"
    - "docker compose up -d --force-recreate -V --quiet-pull"
    - "sleep 10"
    - "docker compose restart proxy"
    - "docker compose logs proxy"
    - "docker compose ps"
    - "curl -I http://proxy && echo yes || echo no"
    - "curl -I http://docker && echo yes || echo no"
    - "curl -I http://localhost && echo yes || echo no"
    - "curl -I http://127.0.0.1 && echo yes || echo no"
    - "curl -I http://0.0.0.0 && echo yes || echo no"
  tags:
    - "dind"
