---
docker-service-test:
  image: "docker:20.10.16"
  stage: "integration"
  before_script:
    - "apk add --no-cache bash"
  script:
    - "mv .env.example .env"
    - "cp .env .gitlab/ci/.env"
    - "echo $GROUP_TOKEN | docker login \
      $SCHEDULER_REGISTRY -u $GROUP_USER --password-stdin"
    - "echo $GROUP_TOKEN | docker login \
     $DISPATCHER_REGISTRY -u $GROUP_USER --password-stdin"
    - "echo $CI_JOB_TOKEN | docker login \
     $FROST_REGISTRY -u gitlab-ci-token --password-stdin"
    - "docker-compose up -d"
    - "sleep 20"
    - "docker-compose logs init"
    - "docker ps"
    - "cd .gitlab/ci"
    - "chmod +x ./dockertest.sh"
    - "./dockertest.sh"
  tags:
    - "dind"

mqtt-service-test:
  image: "docker:20.10.16"
  stage: "integration"
  script:
    - "mv .env.example .env"
    - "cp .env .gitlab/ci/.env"
    - "echo $GROUP_TOKEN | docker login \
      $SCHEDULER_REGISTRY -u $GROUP_USER --password-stdin"
    - "echo $GROUP_TOKEN | docker login \
     $DISPATCHER_REGISTRY -u $GROUP_USER --password-stdin"
    - "echo $CI_JOB_TOKEN | docker login \
     $FROST_REGISTRY -u gitlab-ci-token --password-stdin"
    - "docker-compose up -d"
    - "sleep 20"
    - "docker-compose exec -T mqtt-broker
      bash -c $'echo `echo -n integrate && /mosquitto/pw -p cicd` >>
      /mosquitto-auth/mosquitto.passwd'"
    - "docker-compose restart mqtt-broker"
    - "sleep 30"
    - 'echo "very nice data!" | docker-compose exec -T mqtt-broker sh -c
       "mosquitto_pub -h mqtt-broker -t
       mqtt_ingest/integrate/beautiful/sensor/1 -u mqtt -P mqtt -s"'
    - 'docker-compose logs mqtt-cat'
  tags:
    - "dind"

# can probably be removed, when all components are covered by end-to-end tests
thing-creation-test:
  image: "docker:20.10.16"
  stage: "integration"
  before_script:
    - "apk add --no-cache curl postgresql bash"
  variables:
    POSTGRES_PORT: "5432"
    PROXY_MINIO_PORT: "9000:9000"
  script:
    - "cp .env.example .env"
    - "echo $GROUP_TOKEN | docker login \
      $SCHEDULER_REGISTRY -u $GROUP_USER --password-stdin"
    - "echo $GROUP_TOKEN | docker login \
      $DISPATCHER_REGISTRY -u $GROUP_USER --password-stdin"
    - "echo $CI_JOB_TOKEN | docker login \
     $FROST_REGISTRY -u gitlab-ci-token --password-stdin"
    - "docker-compose up -d --force-recreate -V --quiet-pull"
    - "sleep 20"
    - "docker-compose logs object-storage"
    - 'cat thing-event-msg.json | docker-compose exec -T mqtt-broker sh -c
      "mosquitto_pub -t thing_creation -u mqtt -P mqtt -s"'
    - "curl https://dl.min.io/client/mc/release/linux-amd64/mc \
      --create-dirs \
      -o $HOME/minio-binaries/mc"
    - "chmod +x $HOME/minio-binaries/mc"
    - "export PATH=$PATH:$HOME/minio-binaries/"
    - "mc alias set minio http://docker:9000 minioadmin minioadmin"
    - "mc tag list minio/thedoors-057d8bba-40b3-11ec-a337-125e5a40a849"
    - "psql 'postgresql://postgres:postgres@docker:5432?sslmode=disable' -l"
    - "bash .gitlab/ci/databasetest.sh"
  tags:
    - "dind"

proxy-test:
  image: "docker:20.10.16-dind"
  stage: "integration"
  before_script:
    "apk add --no-cache curl"
  script:
    - "cp .env.example .env"
    - "docker-compose up -d --force-recreate -V --quiet-pull"
    - "sleep 20"
    - "export PROXY_URL=$(grep \"PROXY_URL=\" .env | cut -d= -f2)"
    - "curl -Isf ${PROXY_URL} || exit 1"
    - "curl -Isf ${PROXY_URL}/frontend/ || exit 1"
    - "curl -Isf ${PROXY_URL}/object-storage/ || exit 1"
    - "curl -Isf ${PROXY_URL}/visualization/ || exit 1"
    - "curl -Isf ${PROXY_URL}/sta/ || exit 1"
  tags:
    - "dind"
