---
proxy-test:
  stage: "integration"
  image: docker:dind
  before_script:
    - "apk add --no-cache jq curl"
  script:
    - "cp .env.example .env"
    - "docker compose up -d --force-recreate -V --quiet-pull"
    - "sleep 5"
    - "docker compose ps"
    - "bash .gitlab/ci/proxytest.sh"
  tags:
    - "dind"
