---
proxy-test:
  stage: "integration"
  image: "docker:24.0.6-dind"
  before_script:
    - "apk add --no-cache curl iproute2"
    - "cp .env.example .env"
    - "docker compose pull -q"
    - "docker compose build -q"
    - "docker compose up -d -V"
    - "docker compose ps"
  script:
    - "ip a"
    - "sleep 30"
    - "curl -I http://docker"
  tags:
    - "dind"
