---
proxy-test:
  stage: "integration"
  image: "docker:24.0.6-dind"
  before_script:
    - "apk add --no-cache curl"
    - "cp .env.example .env"
    - "docker compose pull -q"
    - "docker compose build -q"
  script:
    - "docker info"
    - "docker compose up -d -V"
    - "docker compose ps"
    - "curl http://docker:80"
  tags:
    - "dind"
