---
proxy-test:
  stage: "integration"
  image: "docker:20.10.16-dind"
  before_script:
    - "apk add --no-cache curl"
    - "cp .env.example .env"
    - "docker system prune -af"
    - "docker-compose up -d --force-recreate -V --quiet-pull"
    - "sleep 20"
  script:
    - "curl -I http://docker && echo yes || echo nope"
  tags:
    - "dind"