---
proxy-test:
  image: "docker:24.0.6-dind"
  stage: "integration"
  before_script:
    - "apk add --no-cache curl iproute2 net-tools"
  script:
    - "cp .env.example .env"
    - "docker compose up proxy -d --force-recreate -V --quiet-pull"
    - "sleep 5"
    - "ip addr"
    - "ifconfig"
    - "PROXY_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' tsm-orchestration-proxy-1)"
    - "echo $PROXY_IP"
    - "curl -I http://${PROXY_IP}:80 && echo yes || echo no"
    - "curl -I http://${PROXY_IP} && echo yes || echo no"
  tags:
    - "dind"
