---

trigger_stage_deployment:
  stage: notify
  image: "docker:${DOCKER_IMAGE_TAG}"
  script:
    - apk add --no-cache curl
    - curl -X POST "https://git.ufz.de/api/v4/projects/3977/ref/main/trigger/pipeline" \
      -F "token=$PIPELINE_TOKEN"
#  only:
#    - main
  when: on_success
