---

# This triggers the CI in the deployment repo [1], 
# which deploys the latest changes on the stage VM.  
# [1] https://git.ufz.de/rdm-software/timeseries-management/tsm-deployment
trigger_stage_deployment:
  stage: notify
  needs:
    - "deploy-images-to-registry"
  image: "docker:${DOCKER_IMAGE_TAG}"
  script:
    - apk add --no-cache curl
    - echo "triggering deployment on stage"
    - curl -X POST "https://git.ufz.de/api/v4/projects/3977/trigger/pipeline" -F "token=$PIPELINE_TOKEN_STAGE" -F "ref=main"
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE != 'merge_request_event'"
  when: on_success


trigger_prod_deployment:
  stage: notify
  needs:
    - "deploy-prod-images-to-registry"
  image: "docker:${DOCKER_IMAGE_TAG}"
  script:
    - apk add --no-cache curl
    - echo "triggering deployment on prod"
    - echo "only echo curl command for now"
    - echo "triggering deployment pipeline"
    - echo "still need to add pipeline token production"
    - |
      curl -X POST "https://git.ufz.de/api/v4/projects/4741/trigger/pipeline" \
           -F "token=$PIPELINE_TOKEN_PROD" \
           -F "ref=main" \
           -F "variables[REF]=$CI_COMMIT_REF_NAME" \  
           -F "variables[CREATED]=1"
    - echo "deployment triggered"
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_TAG && $CI_PIPELINE_SOURCE != 'merge_request_event'"
  when: manual