---

# This triggers the CI in the deployment repo [1], 
# which deploys the latest changes on the stage VM.  
# [1] https://git.ufz.de/rdm-software/timeseries-management/tsm-deployment
trigger_stage_deployment:
  stage: notify
  needs:
    - "deploy-images-to-registry"
  image: "docker:${DOCKER_IMAGE_TAG}"
  script:
    - apk add --no-cache curl
    - curl -X POST "https://git.ufz.de/api/v4/projects/3977/trigger/pipeline" -F "token=$PIPELINE_TOKEN_STAGE" -F "ref=main"
    - echo "triggering deployment on stage"
  only:
    - main
  when: on_success
