---

deploy-images-to-registry:
  stage: release
  dependencies:
    - build
  image: "docker:${DOCKER_IMAGE_TAG}"
  before_script:
    - export BUILD_DATE=$(cat .build_date)
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - export REGISTRY=$(grep TIMEIO_IMAGE_REGISTRY .env | cut -d'=' -f2)
    - export BUILD_DATE=$(cat .build_date)
  after_script:
    - docker logout
  script:
    - docker compose pull init frost cron-scheduler worker-configdb-updater worker-db-setup
    - |
      for image in $(docker images --format '{{ .Repository }}; do 
        echo "${image}:latest";
        echo "${image}:${BUILD_DATE}";
      done
  tags:
    - "dind"
  artifacts:
    paths:
      - .build_date
