--
scan-docker-images:
  image: "docker:${DOCKER_IMAGE_TAG}"
  stage: "scan"
  #variables:
  #  TRIVY_VERSION: "0.58.2" # Current Trivy version
  before_script:
    # Install Trivy in the pipeline environment
    - apk add --no-cache curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.58.2
  script:
    - "docker compose pull -q"
    - "docker compose build -q"
    - for image in $(docker images --format "{{.Repository}}:{{.Tag}}"); do
        echo "Scanning $image ...";
        trivy image $image --severity critical --exit-code 0 >> ./trivy.out;
      done
  artifacts:
    when: on_success
    paths:
      - ./trivy.out
    rules:
      - if: $CI_COMMIT_BRANCH == "main"
        expire_in: 30 days
        when: always
      - if: $CI_COMMIT_BRANCH != "main"
        expire_in: 2 days
        when: always
  tags:
    - "dind"